/* SPDX-License-Identifier: AGPL-3.0-only */

/** The reviewed Audacity 4 default-shortcut source. */
export const AUDACITY_SHORTCUT_SOURCE = Object.freeze({
	version: '4.0.0',
	commit: '4c177d436e48c1d20f231eada44035593cb26292',
	generatedFromCommit: '2f42f1c968ad15b5ab871f3bdf56249bd311a84e',
	file: 'src/app/configs/data/shortcuts.xml',
	url: 'https://github.com/audacity/audacity/blob/4c177d436e48c1d20f231eada44035593cb26292/src/app/configs/data/shortcuts.xml',
	sha256: 'cc373976cf8755b8dcae5c4517065c3818da566e6c8372fccbae2a78f9f02f06',
});

export interface AudacityShortcutRecord {
	readonly upstreamActionId: string;
	readonly sequences: readonly string[];
	readonly autorepeat: boolean;
}

/** Audacity's shortcut reader defaults an omitted `autorepeat` element to true. */
export const AUDACITY_SHORTCUT_DEFAULT_AUTOREPEAT = true;

function shortcut(
	upstreamActionId: string,
	sequences: readonly string[],
	autorepeat = AUDACITY_SHORTCUT_DEFAULT_AUTOREPEAT,
): AudacityShortcutRecord {
	return Object.freeze({
		upstreamActionId,
		sequences: Object.freeze([...sequences]),
		autorepeat,
	});
}

/** Every non-development shortcut-bearing record, in pinned source order. */
export const AUDACITY_SHORTCUT_INVENTORY: readonly AudacityShortcutRecord[] = Object.freeze([
	shortcut('nav-next-section', ['F6', '`']),
	shortcut('nav-prev-section', ['Shift+F6', 'Shift+`']),
	shortcut('nav-next-panel', ['Tab']),
	shortcut('nav-prev-panel', ['Shift+Tab']),
	shortcut('nav-next-tab', ['Ctrl+Tab']),
	shortcut('nav-prev-tab', ['Ctrl+Shift+Tab']),
	shortcut('nav-right', ['Right']),
	shortcut('nav-left', ['Left']),
	shortcut('nav-up', ['Up']),
	shortcut('nav-down', ['Down']),
	shortcut('nav-first-control', ['Home']),
	shortcut('nav-last-control', ['End']),
	shortcut('nav-nextrow-control', ['PgDown']),
	shortcut('nav-prevrow-control', ['PgUp']),
	shortcut('action://copy', ['Ctrl+C']),
	shortcut('action://cut', ['Ctrl+X']),
	shortcut('action://paste', ['Ctrl+V']),
	shortcut('action://undo', ['Ctrl+Z']),
	shortcut('action://redo', ['Ctrl+Shift+Z']),
	shortcut('action://delete', ['Del', 'Backspace']),
	shortcut('action://cancel', ['Esc']),
	shortcut('action://enter', ['Return', 'Enter']),
	shortcut('action://trigger', ['Space']),
	shortcut('track-view-next-panel', ['Tab']),
	shortcut('track-view-prev-panel', ['Shift+Tab']),
	shortcut('track-view-item-context-menu', ['Shift+F10', 'Ctrl+Shift+F10']),
	shortcut('track-view-above-item', ['Up']),
	shortcut('track-view-below-item', ['Down']),
	shortcut('track-view-first-track', ['Ctrl+Home']),
	shortcut('track-view-last-track', ['Ctrl+End']),
	shortcut('track-view-toggle-selection', ['Ctrl+Enter', 'Ctrl+Return']),
	shortcut('track-view-range-selection', ['Shift+Enter', 'Shift+Return']),
	shortcut('track-view-extend-track-selection-prev', ['Shift+Up']),
	shortcut('track-view-extend-track-selection-next', ['Shift+Down']),
	shortcut('action://trackedit/paste-overlap', ['Ctrl+Alt+V']),
	shortcut('action://trackedit/paste-insert', ['Shift+V']),
	shortcut('action://trackedit/paste-insert-all-tracks-ripple', ['Ctrl+Alt+Shift+V']),
	shortcut('timer-record', ['Shift+T']),
	shortcut('contrast-analyser', ['Ctrl+Shift+T']),
	shortcut('sel-prev-clip', ['Alt+,']),
	shortcut('sel-next-clip', ['Alt+.']),
	shortcut('cut-per-track-ripple', ['Ctrl+Shift+X']),
	shortcut('duplicate', ['Ctrl+D']),
	shortcut('silence-audio-selection', ['Ctrl+L']),
	shortcut('trim', ['Ctrl+T']),
	shortcut('split', ['Ctrl+I']),
	shortcut('split-new', ['Ctrl+Alt+I']),
	shortcut('join', ['Ctrl+J']),
	shortcut('disjoin', ['Ctrl+Alt+J']),
	shortcut('split-tool', ['S']),
	shortcut('preferences', ['Ctrl+,']),
	shortcut('delete-per-track-ripple', ['Shift+Del', 'Shift+Backspace']),
	shortcut('delete-all-tracks-ripple', ['Ctrl+Del', 'Ctrl+Backspace']),
	shortcut('file-new', ['Ctrl+N']),
	shortcut('file-open', ['Ctrl+O']),
	shortcut('file-save', ['Ctrl+S']),
	shortcut('file-close', ['Ctrl+W']),
	shortcut('export-audio', ['Ctrl+Shift+E']),
	shortcut('project-import', ['Ctrl+Shift+I']),
	shortcut('quit', ['Ctrl+Q']),
	shortcut('label-add', ['Ctrl+B']),
	shortcut('add-label-playing', ['Ctrl+.']),
	shortcut('prev-window', ['Alt+Shift+F6']),
	shortcut('next-window', ['Alt+F6']),
	shortcut('prev-frame', ['Ctrl+Shift+F6']),
	shortcut('toggle', ['Return']),
	shortcut('toggle-alt', ['NUMPAD_ENTER']),
	shortcut('add-realtime-effects', ['E']),
	shortcut('repeat-last-effect', ['Ctrl+R']),
	shortcut('select-all', ['Ctrl+A']),
	shortcut('select-none', ['Ctrl+Shift+A']),
	shortcut('select-all-tracks', ['Ctrl+Shift+K']),
	shortcut('sel-sync-lock-tracks', ['Ctrl+Shift+Y']),
	shortcut('select-left-of-playback-position', ['[']),
	shortcut('select-right-of-playback-position', [']']),
	shortcut('select-track-start-to-cursor', ['Shift+J']),
	shortcut('select-cursor-to-track-end', ['Shift+K']),
	shortcut('zero-cross', ['Z']),
	shortcut('sel-start', ['Shift+Home']),
	shortcut('sel-end', ['Shift+End']),
	shortcut('sel-ext-left', ['Shift+Left']),
	shortcut('sel-ext-right', ['Shift+Right']),
	shortcut('sel-cntr-left', ['Ctrl+Shift+Right']),
	shortcut('sel-cntr-right', ['Ctrl+Shift+Left']),
	shortcut('curs-track-start', ['J']),
	shortcut('curs-track-end', ['K']),
	shortcut('curs-project-start', ['Home']),
	shortcut('curs-project-end', ['End']),
	shortcut('play-position-decrease', ['Left']),
	shortcut('play-position-increase', ['Right']),
	shortcut('cursor-short-jump-left', [',']),
	shortcut('cursor-short-jump-right', ['.']),
	shortcut('cursor-long-jump-left', ['Shift+,']),
	shortcut('cursor-long-jump-right', ['Shift+.']),
	shortcut('seek-left-short', ['Left']),
	shortcut('seek-right-short', ['Right']),
	shortcut('seek-left-long', ['Shift+Left']),
	shortcut('seek-right-long', ['Shift+Right']),
	shortcut('mix-and-render-to-new-track', ['Ctrl+Shift+M']),
	shortcut('mute-all-tracks', ['Ctrl+U']),
	shortcut('unmute-all-tracks', ['Ctrl+Shift+U']),
	shortcut('mute-tracks', ['Ctrl+Alt+U']),
	shortcut('unmute-tracks', ['Ctrl+Alt+Shift+U']),
	shortcut('group-clips', ['Ctrl+G']),
	shortcut('ungroup-clips', ['Ctrl+Shift+G']),
	shortcut('track-pan', ['Shift+P']),
	shortcut('track-pan-left', ['Alt+Shift+Left']),
	shortcut('track-pan-right', ['Alt+Shift+Right']),
	shortcut('track-gain', ['Shift+G']),
	shortcut('track-gain-inc', ['Alt+Shift+Up']),
	shortcut('track-gain-dec', ['Alt+Shift+Down']),
	shortcut('track-menu', ['Shift+M']),
	shortcut('track-mute', ['Shift+U']),
	shortcut('track-solo', ['Shift+S']),
	shortcut('track-close', ['Shift+C']),
	shortcut('play-stop-select', ['X']),
	shortcut('once-play-stop', ['Shift+Space']),
	shortcut('action://playback/toggle-play-pause', ['P']),
	shortcut('action://record/start', ['R']),
	shortcut('action://record/lead-in-recording', ['Shift+D']),
	shortcut('toggle-loop-region', ['L']),
	shortcut('clear-loop-region', ['Shift+Alt+L']),
	shortcut('set-loop-region-to-selection', ['Shift+L']),
	shortcut('set-loop-region-in-out', ['I']),
	shortcut('action://playback/toggle-play-stop', ['Space']),
	shortcut('action://playback/toggle-play-from-cursor', ['Shift+Space']),
	shortcut('action://record/stop', ['Space']),
	shortcut('play-one-sec', ['1']),
	shortcut('play-to-selection', ['B']),
	shortcut('play-before-selection-start', ['Shift+F5']),
	shortcut('play-after-selection-start', ['Shift+F6']),
	shortcut('play-before-selection-end', ['Shift+F7']),
	shortcut('play-after-selection-end', ['Shift+F8']),
	shortcut('play-before-and-after-selection-start', ['Ctrl+Shift+F5']),
	shortcut('play-before-and-after-selection-end', ['Ctrl+Shift+F7']),
	shortcut('play-cut-preview', ['C']),
	shortcut('move-to-prev-label', ['Alt+Left']),
	shortcut('move-to-next-label', ['Alt+Right']),
	shortcut('zoom-in', ['Ctrl+=']),
	shortcut('zoom-normal', ['Ctrl+2']),
	shortcut('zoom-out', ['Ctrl+-']),
	shortcut('zoom-sel', ['Ctrl+E']),
	shortcut('zoom-toggle', ['Shift+Z']),
	shortcut('zoom-to-fit-project', ['Ctrl+F']),
	shortcut('fit-v', ['Ctrl+Shift+F']),
	shortcut('collapse-all-tracks', ['Ctrl+Shift+C']),
	shortcut('skip-sel-start', ['Ctrl+[']),
	shortcut('skip-sel-end', ['Ctrl+]']),
	shortcut('input-device', ['Shift+I']),
	shortcut('output-device', ['Shift+O']),
	shortcut('audio-host', ['Shift+H']),
	shortcut('input-channels', ['Shift+N']),
	shortcut('select-tool', ['F1']),
	shortcut('draw-tool', ['F3']),
	shortcut('multi-tool', ['F6']),
	shortcut('prev-tool', ['A']),
	shortcut('next-tool', ['D']),
	shortcut('toggle-spectral-selection', ['Q']),
	shortcut('rename-item', ['F2']),
	shortcut('clip-pitch-speed-open', ['Ctrl+Shift+P']),
	shortcut('pitch-up', ['Alt+Up']),
	shortcut('pitch-down', ['Alt+Down']),
	shortcut('realtime-effect-move-up', ['Alt+Up']),
	shortcut('realtime-effect-move-down', ['Alt+Down']),
	shortcut('new-mono-track', ['Ctrl+Shift+N']),
	shortcut('keyboard-scrub-backwards', ['U']),
	shortcut('keyboard-scrub-forwards', ['I']),
	shortcut('track-view-item-move-left', ['Ctrl+Left']),
	shortcut('track-view-item-move-right', ['Ctrl+Right']),
	shortcut('track-view-item-extend-left', ['Shift+Left']),
	shortcut('track-view-item-extend-right', ['Shift+Right']),
	shortcut('track-view-item-reduce-left', ['Ctrl+Shift+Left']),
	shortcut('track-view-item-reduce-right', ['Ctrl+Shift+Right']),
	shortcut('track-view-item-move-up', ['Ctrl+Up']),
	shortcut('track-view-item-move-down', ['Ctrl+Down']),
]);
