/* SPDX-License-Identifier: AGPL-3.0-only */

/**
 * Shared Markdown construction for the generated handbook reference pages.
 *
 * Every generated page is a Starlight document with frontmatter, a banner that
 * warns editors off, and tables built from runtime registries. Keeping the
 * construction here means a table cell is escaped the same way on every page
 * and a new page cannot quietly invent its own frontmatter shape.
 */

export const GENERATED_BANNER = '<!-- Generated by `node scripts/docs-reference.mjs`. Do not edit. -->';

/**
 * The magnitude at which an effect manifest's numeric bound stops being a real
 * limit. `Number.MAX_VALUE` and the 32-bit float maximum both appear in the
 * Audacity parameter contract to mean "no upper limit", and printing either of
 * them as a number would read as a precise claim rather than the absence of one.
 */
const UNBOUNDED_MAGNITUDE = 3.4e38;

export function compareText(left, right) {
	return left < right ? -1 : left > right ? 1 : 0;
}

export function escapeMarkdownTableCell(value) {
	return String(value ?? '')
		.replaceAll('\\', '\\\\')
		.replaceAll('|', '\\|')
		.replace(/\r?\n/gu, ' ');
}

export function table(headers, rows) {
	const line = (cells) => `| ${cells.map(escapeMarkdownTableCell).join(' | ')} |`;
	return [
		line(headers),
		line(headers.map(() => '---')),
		...rows.map(line),
	].join('\n');
}

export function page({ title, description, order, body }) {
	return [
		'---',
		`title: ${JSON.stringify(title)}`,
		`description: ${JSON.stringify(description)}`,
		'editUrl: false',
		'sidebar:',
		`  order: ${String(order)}`,
		'---',
		'',
		GENERATED_BANNER,
		'',
		body.trim(),
		'',
	].join('\n');
}

export function productNames(products) {
	return products.map(({ name }) => name).join(', ');
}

/** Product names as a sentence reads them, rather than as a table cell does. */
export function productSentence(products) {
	const names = products.map(({ name }) => name);
	if (names.length <= 1) return names.join('');
	return `${names.slice(0, -1).join(', ')} and ${names[names.length - 1]}`;
}

export function assertProducts(products) {
	if (!Array.isArray(products) || products.length === 0) {
		throw new TypeError('At least one product profile is required.');
	}
	for (const product of products) {
		if (!product || typeof product !== 'object' || typeof product.id !== 'string' || typeof product.name !== 'string') {
			throw new TypeError('Every documentation product must have an id and name.');
		}
	}
}

/**
 * Resolve a public label for a machine identifier, or refuse to publish.
 *
 * Generated pages name runtime identifiers that were never written for readers.
 * Rather than print a raw key or invent wording at render time, each page
 * declares the labels it has reviewed; an identifier that appears in the
 * runtime without one fails the documentation gate until somebody writes it.
 */
export function reviewedLabel(labels, key, kind) {
	const label = labels[key];
	if (!label) throw new Error(`No reviewed documentation label exists for ${kind} ${key}.`);
	return label;
}

/** Whether a numeric bound is one of the manifests' "no limit" sentinels. */
export function isUnbounded(value) {
	return !Number.isFinite(value) || Math.abs(value) >= UNBOUNDED_MAGNITUDE;
}

export function formatNumber(value) {
	if (typeof value === 'boolean') return value ? 'On' : 'Off';
	if (typeof value !== 'number') return String(value ?? '');
	if (isUnbounded(value)) return value < 0 ? 'no lower limit' : 'no upper limit';
	return String(value);
}

/** A closed numeric interval, or the open form when a bound is a sentinel. */
export function formatRange(minimum, maximum) {
	if (isUnbounded(minimum) && isUnbounded(maximum)) return 'Any value';
	if (isUnbounded(maximum)) return `${formatNumber(minimum)} or more`;
	if (isUnbounded(minimum)) return `${formatNumber(maximum)} or less`;
	return `${formatNumber(minimum)} to ${formatNumber(maximum)}`;
}

/** Bytes as the whole binary units the memory floors are actually written in. */
export function formatBinaryBytes(value) {
	if (!Number.isSafeInteger(value) || value <= 0) throw new RangeError(`Unsupported byte count: ${String(value)}.`);
	const units = ['bytes', 'KiB', 'MiB', 'GiB', 'TiB'];
	let index = 0;
	let scaled = value;
	while (index < units.length - 1 && scaled >= 1024 && scaled % 1024 === 0) {
		scaled /= 1024;
		index += 1;
	}
	return `${String(scaled)} ${units[index]}`;
}
