/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false functions/worker-configuration.d.ts` (hash: 86810fe8f472e31c5c36c51a5b82be46)
interface __BaseEnv_Env {
	FREESOUND_OAUTH_DB: D1Database;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
