/* SPDX-License-Identifier: AGPL-3.0-only */

/** @type {import('electron-builder').Configuration} */
module.exports = {
	appId: 'org.soundscaper.desktop.nightly-tests',
	productName: 'Soundscaper Nightly Tests',
	artifactName: 'Soundscaper-${version}-nightly-with-tests-${os}-${arch}.${ext}',
	compression: 'normal',
	asar: true,
	npmRebuild: false,
	afterPack: './scripts/desktop-nightly-tests-after-pack.mjs',
	directories: {
		app: '.desktop-build/nightly-tests',
		buildResources: '.desktop-build/icons',
		output: 'release/desktop-nightly-tests',
	},
	files: [
		'desktop/nightly-tests-main.mjs',
		'desktop/nightly-tests-manifest.mjs',
		'scripts/lib/desktop-nightly-tests-runtime.mjs',
		'scripts/lib/desktop-nightly-tests-static-response.mjs',
		'scripts/lib/desktop-nightly-tests-product-sites.mjs',
		'scripts/lib/desktop-nightly-tests-static-route.mjs',
		'scripts/lib/desktop-nightly-tests-metrics.mjs',
		'scripts/lib/desktop-nightly-tests-packaged-runtime.mjs',
		'scripts/lib/desktop-nightly-tests-presentation.mjs',
		'scripts/collect-m3-longform-editorial-quality.mjs',
		'scripts/lib/m4-production-parity-identity.mjs',
		'scripts/lib/m4-production-parity-metrics.mjs',
		'scripts/lib/m4-production-parity-video-fixture.mjs',
		'scripts/lib/m4b2-keyframe-parity-metrics.mjs',
		'scripts/lib/strict-json-snapshot.mjs',
		'scripts/lib/quality-budget-config.mjs',
		'scripts/collect-m4-production-parity-quality.mjs',
		'scripts/collect-m4b2-keyframe-parity-quality.mjs',
		'scripts/quality-budget-evaluator.mjs',
		'scripts/quality-budget-result.mjs',
		'scripts/verify-quality-budget-result.mjs',
		'package.json',
		'!node_modules/**/*',
	],
	extraResources: [
		{
			from: '.desktop-build/nightly-tests',
			to: 'nightly-tests',
			filter: [
				'.local-browsers/**/*',
				'config/**/*',
				// The guide specs replay handbook step data, which lives outside `tests/`.
				'handbook/**/*',
				'sites/**/*',
				'licenses/**/*',
				'package.json',
				'playwright.nightly-metrics.config.mjs',
				'playwright.nightly-packaged-metrics.config.mjs',
				'playwright.nightly-tests.config.mjs',
				// The browser specs import spec-support helpers from here. The
				// launcher's own modules reach the main process through `files`
				// above, so this carries the payload's copies, not the launcher's.
				'scripts/lib/**/*',
				'scripts/*.mjs',
				'src/**/*',
				'stage-manifest.json',
				'tests/**/*',
			],
		},
		{
			from: '.desktop-build/nightly-tests/node_modules',
			to: 'nightly-tests/node_modules',
		},
		{
			from: 'release/desktop-nightly-products',
			to: 'nightly-tests/products',
		},
		{ from: 'LICENSE', to: 'licenses/Soundscaper-AGPL-3.0.txt' },
		{ from: 'LICENSES', to: 'licenses/LICENSES' },
	],
	win: {
		icon: '.desktop-build/icons/icon.png',
		target: ['portable'],
	},
	mac: {
		icon: '.desktop-build/icons/icon.png',
		identity: '-',
		hardenedRuntime: false,
		gatekeeperAssess: false,
		category: 'public.app-category.developer-tools',
		target: ['zip'],
	},
	linux: {
		icon: '.desktop-build/icons',
		executableName: 'soundscaper-nightly-tests',
		syncDesktopName: true,
		category: 'Development',
		synopsis: 'Portable Soundscaper browser test runner',
		description: 'Runs the bundled Soundscaper Playwright workflows and writes diagnostics beside the executable.',
		maintainer: 'kw.media',
		target: ['AppImage'],
	},
	publish: null,
};
