/* SPDX-License-Identifier: AGPL-3.0-only */

/**
 * Probe parity between the wasm path and the native-helper path, on media
 * generated by the same pinned core: the helper engine's full pipeline —
 * digest-verified payload, identity-verified grant, MEMFS probe, timing
 * asset encoding — must reproduce exactly what the renderer's parser
 * contract concludes from the same bytes, or the difference is a bug, not
 * an opinion.
 */

import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdtemp, open, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import test from 'node:test';
import { fileURLToPath, pathToFileURL } from 'node:url';

import { probeVideoSourceWithFfmpegCore } from '../desktop/helper-probe-engine.js';
import {
	buildFfmpegVideoTimingProbeArgs,
	parseFfmpegVideoTimingLogs,
} from '../src/common/editor/ffmpeg-video-timing-probe.ts';
import {
	isFfmpegSourceCharacteristicsLog,
	parseFfmpegVideoSourceCharacteristics,
} from '../src/common/editor/ffmpeg-video-source-characteristics.ts';
import { decodeVideoTimingAsset } from '../src/common/editor/video-timing-asset.ts';

const ROOT = resolve(fileURLToPath(new URL('..', import.meta.url)));
const CORE_JS_PATH = join(ROOT, 'node_modules/@ffmpeg/core/dist/esm/ffmpeg-core.js');
const CORE_WASM_PATH = join(ROOT, 'node_modules/@ffmpeg/core/dist/esm/ffmpeg-core.wasm');

interface LoadedCore {
	exec(...args: string[]): number;
	setLogger(logger: (entry: Readonly<{ type: string; message: string }>) => void): void;
	reset(): void;
	FS: {
		writeFile(name: string, bytes: Uint8Array): void;
		readFile(name: string): Uint8Array;
	};
}

async function loadPinnedCore(): Promise<LoadedCore> {
	(globalThis as { self?: unknown }).self ??= globalThis;
	(globalThis as { location?: unknown }).location ??= new URL(pathToFileURL(CORE_JS_PATH).href);
	const wasmBinary = await readFile(CORE_WASM_PATH);
	const module = await import(pathToFileURL(CORE_JS_PATH).href) as { default: (options: object) => Promise<LoadedCore> };
	return module.default({ wasmBinary });
}

async function engineConfig() {
	const [coreJavascript, coreWasm] = await Promise.all([readFile(CORE_JS_PATH), readFile(CORE_WASM_PATH)]);
	const digest = (bytes: Buffer) => createHash('sha256').update(bytes).digest('hex');
	return {
		coreJavascript: { path: CORE_JS_PATH, byteLength: coreJavascript.byteLength, sha256: digest(coreJavascript) },
		coreWasm: { path: CORE_WASM_PATH, byteLength: coreWasm.byteLength, sha256: digest(coreWasm) },
	};
}

async function grantFor(path: string) {
	const handle = await open(path, 'r');
	const details = await handle.stat();
	await handle.close();
	return { mediaPath: path, mediaBytes: details.size, identity: { dev: details.dev, ino: details.ino } };
}

/** The renderer path's probe over the same core: filtered logs into the shared parsers. */
function rendererEquivalentProbe(core: LoadedCore, inputName: string, bytes: Uint8Array) {
	const logs: string[] = [];
	core.setLogger(({ message }) => {
		if (typeof message !== 'string') return;
		if (message.includes('showinfo') || /config in time_base:/u.test(message)
			|| isFfmpegSourceCharacteristicsLog(message)) {
			logs.push(message);
		}
	});
	core.FS.writeFile(inputName, bytes);
	const exitCode = core.exec(...buildFfmpegVideoTimingProbeArgs(inputName));
	assert.equal(exitCode, 0);
	const timing = parseFfmpegVideoTimingLogs(logs);
	return {
		timing,
		characteristics: parseFfmpegVideoSourceCharacteristics(logs, { rate: timing.nominalRate }),
	};
}

test('native helper probe results agree exactly with the wasm parser path on shared fixtures', { timeout: 600_000 }, async (context) => {
	const temporaryRoot = await mkdtemp(join(tmpdir(), 'scape-helper-parity-'));
	context.after(() => rm(temporaryRoot, { recursive: true, force: true }));
	const core = await loadPinnedCore();
	core.setLogger(() => {});
	const fixtures = [
		{
			name: 'parity-h264.mp4',
			generate: [
				'-f', 'lavfi', '-i', 'testsrc=duration=0.5:size=64x36:rate=30',
				'-vf', 'setsar=2/3', '-c:v', 'libx264', '-preset', 'ultrafast', '-pix_fmt', 'yuv420p',
				'-movflags', '+faststart', 'parity-h264.mp4',
			],
		},
		{
			name: 'parity-vp8.webm',
			generate: [
				'-f', 'lavfi', '-i', 'testsrc=duration=0.4:size=64x36:rate=25',
				'-c:v', 'libvpx', '-b:v', '64k', 'parity-vp8.webm',
			],
		},
	];
	const config = await engineConfig();
	for (const fixture of fixtures) {
		core.reset();
		core.setLogger(() => {});
		assert.equal(core.exec(...fixture.generate), 0, `generating ${fixture.name} must succeed`);
		const bytes = core.FS.readFile(fixture.name);
		const fixturePath = join(temporaryRoot, fixture.name);
		await writeFile(fixturePath, bytes);

		core.reset();
		const renderer = rendererEquivalentProbe(core, `renderer-${fixture.name}`, bytes);
		const helper = await probeVideoSourceWithFfmpegCore({
			engineConfig: config,
			grant: await grantFor(fixturePath),
		});

		const helperTiming = decodeVideoTimingAsset(helper.timingAsset);
		assert.deepEqual(helperTiming.presentationTicks, renderer.timing.presentationTicks,
			`${fixture.name}: presentation ticks must agree between the paths`);
		assert.equal(helperTiming.timescale, renderer.timing.timescale);
		assert.equal(helperTiming.finalFrameDurationTicks, renderer.timing.finalFrameDurationTicks);
		assert.deepEqual(helper.nominalRate, {
			num: renderer.timing.nominalRate.num,
			den: renderer.timing.nominalRate.den,
		});
		assert.deepEqual(helper.characteristics, renderer.characteristics,
			`${fixture.name}: probed characteristics must agree between the paths`);
	}
});

test('native helper probe fails closed on tampered engine payloads and swapped media identity', { timeout: 600_000 }, async (context) => {
	const temporaryRoot = await mkdtemp(join(tmpdir(), 'scape-helper-mismatch-'));
	context.after(() => rm(temporaryRoot, { recursive: true, force: true }));
	const mediaPath = join(temporaryRoot, 'granted.bin');
	await writeFile(mediaPath, new Uint8Array(64));
	const config = await engineConfig();

	const tampered = {
		...config,
		coreWasm: { ...config.coreWasm, sha256: '0'.repeat(64) },
	};
	await assert.rejects(
		probeVideoSourceWithFfmpegCore({ engineConfig: tampered, grant: await grantFor(mediaPath) }),
		(error: Error & { code?: string }) => error.code === 'HELPER_ENGINE_BINARY_MISMATCH',
		'a tampered engine payload must refuse to execute',
	);

	const grant = await grantFor(mediaPath);
	await rm(mediaPath);
	await writeFile(mediaPath, new Uint8Array(128));
	await assert.rejects(
		probeVideoSourceWithFfmpegCore({ engineConfig: config, grant }),
		(error: Error & { code?: string }) => error.code === 'HELPER_GRANT_IDENTITY_MISMATCH',
		'a replaced file behind the granted path must be refused',
	);
});
