/* SPDX-License-Identifier: AGPL-3.0-only */

import assert from 'node:assert/strict';
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import test from 'node:test';

import {
	GENERATED_REFERENCE_DIRECTORY,
	escapeMarkdownTableCell,
	generateReferenceDocuments,
	renderCapabilityReference,
	renderCommandReference,
	renderFormatReference,
	syncReferenceDocuments,
} from '../scripts/lib/docs-reference-generator.mjs';

const products = Object.freeze([
	Object.freeze({
		id: 'soundscaper',
		name: 'Soundscaper',
		projectFileExtension: '.sscape',
		shortcuts: Object.freeze({ disabledCommandIds: Object.freeze([]) }),
		importChoices: Object.freeze(['scape', 'audio']),
		exportChoices: Object.freeze(['scape', 'audio', 'video']),
		capabilities: Object.freeze({ assistanceAssets: true, audioImport: true, videoEffects: false }),
	}),
	Object.freeze({
		id: 'framescaper',
		name: 'Framescaper',
		projectFileExtension: '.fscape',
		shortcuts: Object.freeze({ disabledCommandIds: Object.freeze(['generate']) }),
		importChoices: Object.freeze(['scape', 'video']),
		exportChoices: Object.freeze(['scape', 'audio', 'video']),
		capabilities: Object.freeze({ assistanceAssets: true, audioImport: true, videoEffects: true }),
	}),
]);

test('command reference includes only implemented visible commands and applies product filters', () => {
	const manifest = Object.freeze({
		'z-last': Object.freeze({
			id: 'z-last', label: 'Mix | render', status: 'implemented', menuVisible: true,
			shortcut: null, locations: Object.freeze(['File > Export | Mix']), origin: 'local',
		}),
		generate: Object.freeze({
			id: 'generator://tone', label: 'Tone', status: 'implemented',
			shortcut: 'Ctrl+G', locations: Object.freeze(['Generate']), origin: 'upstream',
		}),
		hidden: Object.freeze({
			id: 'hidden', label: 'Hidden', status: 'implemented', menuVisible: false,
			shortcut: 'H', locations: Object.freeze(['Tools']), origin: 'upstream',
		}),
		excluded: Object.freeze({
			id: 'excluded', label: 'Excluded', status: 'excluded',
			shortcut: null, locations: Object.freeze(['Tools']), origin: 'upstream',
		}),
	});
	const rendered = renderCommandReference({
		manifest,
		implementedStatus: 'implemented',
		products,
		source: {
			version: '4.0.0-beta.4',
			commit: '0123456789abcdef0123456789abcdef01234567',
			url: 'https://example.test/audacity/tree/0123456789abcdef0123456789abcdef01234567/src',
		},
		isProductCommandDisabled: (id, disabledIds) => id === 'generator://tone' && disabledIds.includes('generate'),
	});

	assert.match(rendered, /<!-- Generated by `node scripts\/docs-reference\.mjs`\. Do not edit\. -->/u);
	assert.doesNotMatch(rendered, /\n# Commands and shortcuts\n/u, 'frontmatter supplies the page heading');
	assert.match(rendered, /Audacity 4\.0\.0-beta\.4/u);
	assert.match(rendered, /0123456789ab/u);
	assert.match(rendered, /Mix \\\| render/u, 'table metacharacters are escaped');
	assert.match(rendered, /File > Export \\\| Mix/u);
	assert.match(rendered, /Tone.*Ctrl\+G.*Soundscaper.*Audacity/u);
	assert.doesNotMatch(rendered, /Tone.*Framescaper/u);
	assert.match(rendered, /Mix.*Soundscaper, Framescaper.*Soundscaper local/u);
	assert.doesNotMatch(rendered, /Hidden|Excluded/u);
	assert.doesNotMatch(rendered, /\d{4}-\d{2}-\d{2}T\d{2}:/u, 'generated output has no timestamp');
	assert.ok(rendered.indexOf('Mix') < rendered.indexOf('Tone'), 'commands are sorted by label');
});

test('format reference distinguishes built-in writers from conditional FFmpeg formats', () => {
	const rendered = renderFormatReference({
		products,
		audioFormatIds: Object.freeze(['wav', 'mp3', 'custom-ffmpeg']),
		audioFormats: Object.freeze({
			wav: Object.freeze({
				id: 'wav', label: 'WAV', backend: 'native-wav', extension: 'wav',
				container: 'WAV', codec: 'PCM', lossless: true, maximumChannels: 32,
			}),
			mp3: Object.freeze({
				id: 'mp3', label: 'MP3', backend: 'ffmpeg', extension: 'mp3',
				container: 'MP3', codec: 'libmp3lame', lossless: false, maximumChannels: 2,
				requiredEncoders: Object.freeze(['libmp3lame']), requiredMuxers: Object.freeze([Object.freeze(['mp3'])]),
			}),
			'custom-ffmpeg': Object.freeze({
				id: 'custom-ffmpeg', label: 'Custom FFmpeg', backend: 'custom-ffmpeg', extension: null,
				container: 'Custom', codec: 'Custom', lossless: null, maximumChannels: 32,
				requiredEncoders: Object.freeze([]), requiredMuxers: Object.freeze([]),
			}),
		}),
		videoFormats: Object.freeze({
			mp4: Object.freeze({
				id: 'mp4', label: 'MP4', extension: 'mp4', container: 'mp4',
				videoCodec: 'h264', audioCodec: 'aac', requiredEncoders: Object.freeze(['libx264', 'aac']),
				requiredMuxers: Object.freeze(['mp4']),
			}),
		}),
	});

	assert.match(rendered, /WAV.*Built in/u);
	assert.doesNotMatch(rendered, /\n# Export formats\n/u, 'frontmatter supplies the page heading');
	assert.match(rendered, /MP3.*FFmpeg runtime required.*libmp3lame.*mp3/u);
	assert.match(rendered, /Custom FFmpeg.*FFmpeg runtime required.*settings determine the encoder and container/u);
	assert.match(rendered, /MP4.*FFmpeg runtime required.*libx264, aac.*mp4/u);
	assert.match(rendered, /Soundscaper, Framescaper/u);
	assert.match(rendered, /the table does not promise that the FFmpeg runtime can be loaded/u);
	assert.doesNotMatch(rendered, /\d{4}-\d{2}-\d{2}T\d{2}:/u);
});

test('capability reference renders product-owned families and a reviewed feature matrix', () => {
	const rendered = renderCapabilityReference({ products });

	assert.match(rendered, /Audio import.*Enabled.*Enabled/u);
	assert.match(rendered, /Local assistance assets.*Enabled.*Enabled/u);
	assert.doesNotMatch(rendered, /\n# Product capabilities\n/u, 'frontmatter supplies the page heading');
	assert.match(rendered, /Video effects.*Not enabled.*Enabled/u);
	// One machine-level `scape` family, rendered under each product's own suffix.
	assert.match(rendered, /Soundscaper.*\.sscape, Audio/u);
	assert.match(rendered, /Framescaper.*\.fscape, Video/u);
	assert.doesNotMatch(rendered, /\| \.scape,/u);
	assert.match(rendered, /disabled capability can still be preserved/u);
	assert.match(rendered, /\[Export formats\]\(\/reference\/generated\/formats\/\)/u);
	assert.doesNotMatch(rendered, /\d{4}-\d{2}-\d{2}T\d{2}:/u);
});

test('capability reference rejects a product family with no declared suffix', () => {
	const missingExtension = products.map((product) => ({ ...product, projectFileExtension: undefined }));
	assert.throws(
		() => renderCapabilityReference({ products: missingExtension }),
		/No reviewed documentation label exists for format family scape/u,
	);
});

test('capability reference rejects a new key until its public label is reviewed', () => {
	const changedProducts = products.map((product) => ({
		...product,
		capabilities: { ...product.capabilities, undocumentedFutureFeature: true },
	}));
	assert.throws(
		() => renderCapabilityReference({ products: changedProducts }),
		/No reviewed documentation label exists for capability undocumentedFutureFeature/u,
	);
});

test('table cells escape pipes, backslashes, and line breaks deterministically', () => {
	assert.equal(escapeMarkdownTableCell('a\\b | c\nd'), 'a\\\\b \\| c d');
});

test('reference sync check reports drift without creating or changing files', async (context) => {
	const root = await mkdtemp(join(tmpdir(), 'soundscaper-docs-reference-'));
	context.after(async () => { await rm(root, { recursive: true, force: true }); });
	const existingPath = join(root, GENERATED_REFERENCE_DIRECTORY, 'commands.md');
	await mkdir(dirname(existingPath), { recursive: true });
	await writeFile(existingPath, 'old commands\n');
	const documents = new Map([
		['commands.md', 'new commands\n'],
		['formats.md', 'new formats\n'],
	]);

	const checked = await syncReferenceDocuments(root, documents, { write: false });
	assert.deepEqual(checked.stale, ['commands.md', 'formats.md']);
	assert.equal(await readFile(existingPath, 'utf8'), 'old commands\n');
	await assert.rejects(readFile(join(root, GENERATED_REFERENCE_DIRECTORY, 'formats.md'), 'utf8'), { code: 'ENOENT' });

	const written = await syncReferenceDocuments(root, documents, { write: true });
	assert.deepEqual(written.stale, ['commands.md', 'formats.md']);
	assert.equal(await readFile(existingPath, 'utf8'), 'new commands\n');
	assert.equal(
		await readFile(join(root, GENERATED_REFERENCE_DIRECTORY, 'formats.md'), 'utf8'),
		'new formats\n',
	);
	assert.deepEqual((await syncReferenceDocuments(root, documents, { write: false })).stale, []);
});

test('checked-in documentation references match the current runtime registries', async () => {
	const repositoryRoot = join(import.meta.dirname, '..');
	const result = await generateReferenceDocuments(repositoryRoot, { write: false });
	assert.equal(result.documentCount, 3);
	assert.deepEqual(result.stale, []);
});
