/* SPDX-License-Identifier: AGPL-3.0-only */

import assert from 'node:assert/strict';
import test from 'node:test';

import { GUIDE_FIXTURES, guideFixtureFile } from '../handbook/guides/fixtures.mjs';
import { SOUNDSCAPER_GUIDE_GROUPS, SOUNDSCAPER_GUIDES } from '../handbook/guides/soundscaper.mjs';
import {
	STEP_KINDS,
	check,
	describeStep,
	effect,
	importAudio,
	menu,
	mixRender,
	open,
	selectRange,
	validateGuide,
} from '../handbook/guides/steps.mjs';
import {
	categoryRoute,
	guideRoute,
	howToSchema,
	plainText,
	relatedGuides,
	renderGuidePages,
	resolveGuideLinks,
} from '../scripts/lib/docs-reference/guides.mjs';

const describe = (entry) => describeStep(entry, { fixtureFile: guideFixtureFile });
const render = () => renderGuidePages({ groups: SOUNDSCAPER_GUIDE_GROUPS, describeStep, fixtureFile: guideFixtureFile });
const pageFor = (pages, guide) => pages.get(`${guideRoute(guide, SOUNDSCAPER_GUIDE_GROUPS).split('/')[2]}/${guide.id}.md`);

test('every guide validates, has a unique id, and only imports known example files', () => {
	const ids = new Set();
	for (const guide of SOUNDSCAPER_GUIDES) {
		validateGuide(guide, GUIDE_FIXTURES);
		assert.ok(!ids.has(guide.id), `duplicate guide id ${guide.id}`);
		ids.add(guide.id);
		assert.equal(guide.steps[0].kind, 'open');
	}
	assert.ok(SOUNDSCAPER_GUIDES.length >= 20, 'the catalog covers the common Audacity tasks');
	assert.equal(SOUNDSCAPER_GUIDE_GROUPS.flatMap((group) => group.guides).length, SOUNDSCAPER_GUIDES.length);
});

test('step constructors refuse malformed input', () => {
	assert.throws(() => selectRange(0.5, 0.2), RangeError);
	assert.throws(() => selectRange(0, 2), RangeError);
	assert.throws(() => menu([]), TypeError);
	assert.throws(() => effect({ group: 'Fading', name: 'Fade In', direct: true, settings: [{ label: 'x', value: '1' }] }), RangeError);
	assert.throws(() => effect({ group: 'Fading', name: 'Fade In', settings: [{ label: 'x' }] }), TypeError);
	assert.throws(() => check({}), TypeError);
	assert.throws(() => importAudio(''), TypeError);
	assert.throws(() => validateGuide({
		id: 'Bad Id', title: 't', description: 'd', audacity: 'a', intro: 'i', steps: [open()], tips: [],
	}, GUIDE_FIXTURES), RangeError);
	assert.throws(() => validateGuide({
		id: 'no-open', title: 't', description: 'd', audacity: 'a', intro: 'i', steps: [menu(['Select', 'Select all'])], tips: [],
	}, GUIDE_FIXTURES), RangeError);
	assert.throws(() => validateGuide({
		id: 'bad-fixture', title: 't', description: 'd', audacity: 'a', intro: 'i', steps: [open(), importAudio('missing')], tips: [],
	}, GUIDE_FIXTURES), RangeError);
});

test('every step kind describes itself with the labels the browser suite clicks', () => {
	const described = new Set();
	for (const guide of SOUNDSCAPER_GUIDES) {
		for (const entry of guide.steps) {
			const sentence = describe(entry);
			assert.ok(sentence.length > 0);
			described.add(entry.kind);
		}
	}
	assert.match(describe(menu(['Select', 'Select all'])), /\*\*Select → Select all\*\*/u);
	assert.match(describe(mixRender()), /\*\*Tracks → Mix & Render\*\*.*\*\*Mix down to stereo\*\*.*\*\*Render effects\*\*.*\*\*Replace originals\*\*/u);
	assert.match(describe(effect({ group: 'Fading', name: 'Fade In', direct: true })), /\*\*Effect → Fading → Fade In\*\*/u);
	assert.match(
		describe(effect({ group: 'Volume and compression', name: 'Normalize', settings: [{ label: 'Peak amplitude', value: '-3' }] })),
		/set \*\*Peak amplitude\*\* to `-3`, then press \*\*Apply to selection\*\*/u,
	);
	assert.match(describe(importAudio('music-loop')), /`guide-music-loop\.wav`/u);
	assert.match(describe(check({ clips: 2, clip: 'Mix' })), /2 clips and a clip named \*\*Mix\*\*/u);
	assert.throws(() => describe({ kind: 'unknown' }), RangeError);
	for (const kind of STEP_KINDS) {
		if (!['note'].includes(kind)) assert.ok(described.has(kind), `no guide exercises the ${kind} step`);
	}
});

test('guide pages carry the generated banner, the Audacity aside, and every step in order', () => {
	const pages = render();
	// Every guide, one overview per category, and the index above them all.
	assert.equal(pages.size, SOUNDSCAPER_GUIDES.length + SOUNDSCAPER_GUIDE_GROUPS.length + 1);
	const index = pages.get('index.md');
	assert.match(index, /title: "Guides"/u);
	for (const guide of SOUNDSCAPER_GUIDES) {
		const page = pageFor(pages, guide);
		assert.ok(page, `missing page for ${guide.id}`);
		assert.match(page, /<!-- Generated by `node scripts\/docs-reference\.mjs`\. Do not edit\. -->/u);
		assert.match(page, new RegExp(`title: ${JSON.stringify(guide.title).replace(/[.*+?^${}()|[\]\\]/gu, '\\$&')}`, 'u'));
		assert.match(page, /:::note\[Coming from Audacity\?\]/u);
		assert.match(page, /## Steps\n\n1\. Open Soundscaper\./u);
		assert.match(page, new RegExp(`\n${String(guide.steps.length)}\\. `, 'u'));
		assert.match(page, /## Tips\n\n- /u);
		assert.match(page, /tests\/browser\/soundscaper-guides\.spec\.js/u);
		assert.match(index, new RegExp(`\\[${guide.title.replace(/[.*+?^${}()|[\]\\]/gu, '\\$&')}\\]\\(${guideRoute(guide, SOUNDSCAPER_GUIDE_GROUPS)}\\)`, 'u'));
	}
	assert.throws(() => renderGuidePages({ groups: [], describeStep, fixtureFile: guideFixtureFile }), TypeError);
});

test('guide pages link to related guides, their reference pages, and carry a HowTo schema', () => {
	const pages = render();
	for (const guide of SOUNDSCAPER_GUIDES) {
		const page = pageFor(pages, guide);
		const related = relatedGuides(guide, SOUNDSCAPER_GUIDE_GROUPS);
		assert.ok(related.length > 0, `${guide.id} has no related guides`);
		assert.ok(!related.includes(guide), 'a guide never lists itself');
		for (const entry of related) assert.ok(page.includes(`](${guideRoute(entry, SOUNDSCAPER_GUIDE_GROUPS)})`), `${guide.id} links ${entry.id}`);
		assert.match(page, /## Related guides\n\nMore \[[^\]]+\]\(\/guides\/[a-z-]+\/\) guides:\n\n- \[/u);
		const referenced = ['menu', 'mix-render', 'effect', 'export', 'nyquist', 'save', 'analyze', 'track-menu', 'rack-effect', 'noise-profile', 'export-project', 'open-project-file', 'open-audacity-project'];
		assert.equal(page.includes('## Reference\n\n- ['), guide.steps.some((entry) => referenced.includes(entry.kind)), `${guide.id} reference section`);
		if (guide.steps.some((entry) => entry.kind === 'effect')) assert.match(page, /audio-effects\/#parameters/u);
		if (guide.steps.some((entry) => entry.kind === 'export')) assert.match(page, /generated\/formats\//u);
		assert.ok(page.includes('\nhead:\n  - tag: script\n    attrs:\n      type: "application/ld+json"\n    content: "'), `${guide.id} declares the HowTo head entry`);
		const schema = howToSchema(guide, describe);
		assert.equal(schema['@type'], 'HowTo');
		assert.equal(schema.step.length, guide.steps.filter((entry) => entry.kind !== 'note').length);
		assert.ok(page.includes(JSON.stringify(JSON.stringify(schema))), 'the page head carries the schema verbatim');
	}
	// Cross-links in tips come first, ahead of the rest of the group.
	const amplify = SOUNDSCAPER_GUIDES.find((guide) => guide.id === 'make-a-recording-louder');
	assert.equal(relatedGuides(amplify, SOUNDSCAPER_GUIDE_GROUPS)[0].id, 'normalize-peaks');
	assert.equal(plainText('Choose **File → Import audio** and pick `x.wav`; see [Normalize](guide:normalize-peaks).'), 'Choose File → Import audio and pick x.wav; see Normalize.');
	const broken = { ...amplify, tips: ['[x](guide:does-not-exist)'] };
	assert.throws(() => relatedGuides(broken, [{ title: 'Broken', guides: [broken] }]), /unknown guide does-not-exist/u);
	assert.throws(() => relatedGuides(broken, SOUNDSCAPER_GUIDE_GROUPS), /not in any guide group/u);
});

test('guides are published under their category, which owns every route to them', () => {
	const pages = render();
	const index = pages.get('index.md');
	for (const group of SOUNDSCAPER_GUIDE_GROUPS) {
		const overview = pages.get(`${group.slug}/index.md`);
		assert.ok(overview, `missing overview for ${group.slug}`);
		assert.match(overview, /\n {2}label: "Overview"\n/u);
		assert.match(overview, new RegExp(`title: ${JSON.stringify(group.title)}`, 'u'));
		assert.match(index, new RegExp(`## \\[${group.title}\\]\\(${categoryRoute(group)}\\)`, 'u'));
		for (const guide of group.guides) {
			assert.equal(guideRoute(guide, SOUNDSCAPER_GUIDE_GROUPS), `/guides/${group.slug}/${guide.id}/`);
			assert.ok(pages.has(`${group.slug}/${guide.id}.md`), `${guide.id} is not under ${group.slug}`);
			assert.ok(overview.includes(`](/guides/${group.slug}/${guide.id}/)`), `${group.slug} overview omits ${guide.id}`);
		}
		// Every category page reaches the others, so no category is a dead end.
		for (const other of SOUNDSCAPER_GUIDE_GROUPS) {
			if (other !== group) assert.ok(overview.includes(`](${categoryRoute(other)})`), `${group.slug} omits ${other.slug}`);
		}
	}
	// No page may hand a reader a route the catalog did not produce.
	const routes = new Set(SOUNDSCAPER_GUIDES.map((guide) => guideRoute(guide, SOUNDSCAPER_GUIDE_GROUPS)));
	for (const group of SOUNDSCAPER_GUIDE_GROUPS) routes.add(categoryRoute(group));
	routes.add('/guides/');
	for (const [name, content] of pages) {
		for (const [, route] of content.matchAll(/\]\((\/guides\/[^)]*)\)/gu)) {
			assert.ok(routes.has(route), `${name} links unpublished route ${route}`);
		}
		assert.doesNotMatch(content, /\]\(guide:/u, `${name} left an unresolved guide link`);
	}
	assert.equal(resolveGuideLinks('see [x](guide:normalize-peaks)', SOUNDSCAPER_GUIDE_GROUPS), 'see [x](/guides/volume/normalize-peaks/)');
	assert.throws(() => resolveGuideLinks('[x](guide:nope)', SOUNDSCAPER_GUIDE_GROUPS), /unknown guide nope/u);
});
