/* SPDX-License-Identifier: AGPL-3.0-only */

import assert from 'node:assert/strict';
import test from 'node:test';

import { LESSON_FIXTURES, lessonFixtureFile } from '../handbook/lessons/fixtures.mjs';
import { SOUNDSCAPER_LESSON_GROUPS, SOUNDSCAPER_LESSONS } from '../handbook/lessons/soundscaper.mjs';
import {
	STEP_KINDS,
	check,
	describeStep,
	effect,
	importAudio,
	menu,
	mixRender,
	open,
	selectRange,
	validateLesson,
} from '../handbook/lessons/steps.mjs';
import { howToSchema, plainText, relatedLessons, renderLessonPages } from '../scripts/lib/docs-reference/lessons.mjs';

const describe = (entry) => describeStep(entry, { fixtureFile: lessonFixtureFile });

test('every lesson validates, has a unique id, and only imports known example files', () => {
	const ids = new Set();
	for (const lesson of SOUNDSCAPER_LESSONS) {
		validateLesson(lesson, LESSON_FIXTURES);
		assert.ok(!ids.has(lesson.id), `duplicate lesson id ${lesson.id}`);
		ids.add(lesson.id);
		assert.equal(lesson.steps[0].kind, 'open');
	}
	assert.ok(SOUNDSCAPER_LESSONS.length >= 20, 'the catalog covers the common Audacity tasks');
	assert.equal(SOUNDSCAPER_LESSON_GROUPS.flatMap((group) => group.lessons).length, SOUNDSCAPER_LESSONS.length);
});

test('step constructors refuse malformed input', () => {
	assert.throws(() => selectRange(0.5, 0.2), RangeError);
	assert.throws(() => selectRange(0, 2), RangeError);
	assert.throws(() => menu([]), TypeError);
	assert.throws(() => effect({ group: 'Fading', name: 'Fade In', direct: true, settings: [{ label: 'x', value: '1' }] }), RangeError);
	assert.throws(() => effect({ group: 'Fading', name: 'Fade In', settings: [{ label: 'x' }] }), TypeError);
	assert.throws(() => check({}), TypeError);
	assert.throws(() => importAudio(''), TypeError);
	assert.throws(() => validateLesson({
		id: 'Bad Id', title: 't', description: 'd', audacity: 'a', intro: 'i', steps: [open()], tips: [],
	}, LESSON_FIXTURES), RangeError);
	assert.throws(() => validateLesson({
		id: 'no-open', title: 't', description: 'd', audacity: 'a', intro: 'i', steps: [menu(['Select', 'Select all'])], tips: [],
	}, LESSON_FIXTURES), RangeError);
	assert.throws(() => validateLesson({
		id: 'bad-fixture', title: 't', description: 'd', audacity: 'a', intro: 'i', steps: [open(), importAudio('missing')], tips: [],
	}, LESSON_FIXTURES), RangeError);
});

test('every step kind describes itself with the labels the browser suite clicks', () => {
	const described = new Set();
	for (const lesson of SOUNDSCAPER_LESSONS) {
		for (const entry of lesson.steps) {
			const sentence = describe(entry);
			assert.ok(sentence.length > 0);
			described.add(entry.kind);
		}
	}
	assert.match(describe(menu(['Select', 'Select all'])), /\*\*Select → Select all\*\*/u);
	assert.match(describe(mixRender()), /\*\*Tracks → Mix & Render\*\*.*\*\*Mix down to stereo\*\*.*\*\*Render effects\*\*.*\*\*Replace originals\*\*/u);
	assert.match(describe(effect({ group: 'Fading', name: 'Fade In', direct: true })), /\*\*Effect → Fading → Fade In\*\*/u);
	assert.match(
		describe(effect({ group: 'Volume and compression', name: 'Normalize', settings: [{ label: 'Peak amplitude', value: '-3' }] })),
		/set \*\*Peak amplitude\*\* to `-3`, then press \*\*Apply to selection\*\*/u,
	);
	assert.match(describe(importAudio('music-loop')), /`lesson-music-loop\.wav`/u);
	assert.match(describe(check({ clips: 2, clip: 'Mix' })), /2 clips and a clip named \*\*Mix\*\*/u);
	assert.throws(() => describe({ kind: 'unknown' }), RangeError);
	for (const kind of STEP_KINDS) {
		if (!['note'].includes(kind)) assert.ok(described.has(kind), `no lesson exercises the ${kind} step`);
	}
});

test('lesson pages carry the generated banner, the Audacity aside, and every step in order', () => {
	const pages = renderLessonPages({ groups: SOUNDSCAPER_LESSON_GROUPS, describeStep, fixtureFile: lessonFixtureFile });
	assert.equal(pages.size, SOUNDSCAPER_LESSONS.length + 1);
	const index = pages.get('index.md');
	assert.match(index, /title: "Lessons"/u);
	for (const lesson of SOUNDSCAPER_LESSONS) {
		const page = pages.get(`${lesson.id}.md`);
		assert.ok(page, `missing page for ${lesson.id}`);
		assert.match(page, /<!-- Generated by `node scripts\/docs-reference\.mjs`\. Do not edit\. -->/u);
		assert.match(page, new RegExp(`title: ${JSON.stringify(lesson.title).replace(/[.*+?^${}()|[\]\\]/gu, '\\$&')}`, 'u'));
		assert.match(page, /:::note\[Coming from Audacity\?\]/u);
		assert.match(page, /## Steps\n\n1\. Open Soundscaper\./u);
		assert.match(page, new RegExp(`\n${String(lesson.steps.length)}\\. `, 'u'));
		assert.match(page, /## Tips\n\n- /u);
		assert.match(page, /tests\/browser\/soundscaper-lessons\.spec\.js/u);
		assert.match(index, new RegExp(`\\[${lesson.title.replace(/[.*+?^${}()|[\]\\]/gu, '\\$&')}\\]\\(/lessons/${lesson.id}/\\)`, 'u'));
	}
	assert.throws(() => renderLessonPages({ groups: [], describeStep, fixtureFile: lessonFixtureFile }), TypeError);
});

test('lesson pages link to related lessons, their reference pages, and carry a HowTo schema', () => {
	const pages = renderLessonPages({ groups: SOUNDSCAPER_LESSON_GROUPS, describeStep, fixtureFile: lessonFixtureFile });
	for (const lesson of SOUNDSCAPER_LESSONS) {
		const page = pages.get(`${lesson.id}.md`);
		const related = relatedLessons(lesson, SOUNDSCAPER_LESSON_GROUPS);
		assert.ok(related.length > 0, `${lesson.id} has no related lessons`);
		assert.ok(!related.includes(lesson), 'a lesson never lists itself');
		for (const entry of related) assert.match(page, new RegExp(`\\]\\(/lessons/${entry.id}/\\)`, 'u'));
		assert.match(page, /## Related lessons\n\n- \[/u);
		const referenced = ['menu', 'mix-render', 'effect', 'export', 'nyquist', 'save', 'analyze', 'track-menu', 'rack-effect', 'noise-profile', 'export-project', 'open-project-file', 'open-audacity-project'];
		assert.equal(page.includes('## Reference\n\n- ['), lesson.steps.some((entry) => referenced.includes(entry.kind)), `${lesson.id} reference section`);
		if (lesson.steps.some((entry) => entry.kind === 'effect')) assert.match(page, /audio-effects\/#parameters/u);
		if (lesson.steps.some((entry) => entry.kind === 'export')) assert.match(page, /generated\/formats\//u);
		assert.ok(page.includes('\nhead:\n  - tag: script\n    attrs:\n      type: "application/ld+json"\n    content: "'), `${lesson.id} declares the HowTo head entry`);
		const schema = howToSchema(lesson, describe);
		assert.equal(schema['@type'], 'HowTo');
		assert.equal(schema.step.length, lesson.steps.filter((entry) => entry.kind !== 'note').length);
		assert.ok(page.includes(JSON.stringify(JSON.stringify(schema))), 'the page head carries the schema verbatim');
	}
	// Cross-links in tips come first, ahead of the rest of the group.
	const amplify = SOUNDSCAPER_LESSONS.find((lesson) => lesson.id === 'make-a-recording-louder');
	assert.equal(relatedLessons(amplify, SOUNDSCAPER_LESSON_GROUPS)[0].id, 'normalize-peaks');
	assert.equal(plainText('Choose **File → Import audio** and pick `x.wav`; see [Normalize](/lessons/normalize-peaks/).'), 'Choose File → Import audio and pick x.wav; see Normalize.');
	const broken = { ...amplify, tips: ['[x](/lessons/does-not-exist/)'] };
	assert.throws(() => relatedLessons(broken, [{ title: 'Broken', lessons: [broken] }]), /unknown lesson does-not-exist/u);
	assert.throws(() => relatedLessons(broken, SOUNDSCAPER_LESSON_GROUPS), /not in any lesson group/u);
});
