/* SPDX-License-Identifier: AGPL-3.0-only */

import assert from 'node:assert/strict';
import test from 'node:test';

import { LESSON_FIXTURES, lessonFixtureFile } from '../handbook/lessons/fixtures.mjs';
import { SOUNDSCAPER_LESSON_GROUPS, SOUNDSCAPER_LESSONS } from '../handbook/lessons/soundscaper.mjs';
import {
	STEP_KINDS,
	check,
	describeStep,
	effect,
	importAudio,
	menu,
	open,
	selectRange,
	validateLesson,
} from '../handbook/lessons/steps.mjs';
import { renderLessonPages } from '../scripts/lib/docs-reference/lessons.mjs';

const describe = (entry) => describeStep(entry, { fixtureFile: lessonFixtureFile });

test('every lesson validates, has a unique id, and only imports known example files', () => {
	const ids = new Set();
	for (const lesson of SOUNDSCAPER_LESSONS) {
		validateLesson(lesson, LESSON_FIXTURES);
		assert.ok(!ids.has(lesson.id), `duplicate lesson id ${lesson.id}`);
		ids.add(lesson.id);
		assert.equal(lesson.steps[0].kind, 'open');
	}
	assert.ok(SOUNDSCAPER_LESSONS.length >= 20, 'the catalog covers the common Audacity tasks');
	assert.equal(SOUNDSCAPER_LESSON_GROUPS.flatMap((group) => group.lessons).length, SOUNDSCAPER_LESSONS.length);
});

test('step constructors refuse malformed input', () => {
	assert.throws(() => selectRange(0.5, 0.2), RangeError);
	assert.throws(() => selectRange(0, 2), RangeError);
	assert.throws(() => menu([]), TypeError);
	assert.throws(() => effect({ group: 'Fading', name: 'Fade In', direct: true, settings: [{ label: 'x', value: '1' }] }), RangeError);
	assert.throws(() => effect({ group: 'Fading', name: 'Fade In', settings: [{ label: 'x' }] }), TypeError);
	assert.throws(() => check({}), TypeError);
	assert.throws(() => importAudio(''), TypeError);
	assert.throws(() => validateLesson({
		id: 'Bad Id', title: 't', description: 'd', audacity: 'a', intro: 'i', steps: [open()], tips: [],
	}, LESSON_FIXTURES), RangeError);
	assert.throws(() => validateLesson({
		id: 'no-open', title: 't', description: 'd', audacity: 'a', intro: 'i', steps: [menu(['Select', 'Select all'])], tips: [],
	}, LESSON_FIXTURES), RangeError);
	assert.throws(() => validateLesson({
		id: 'bad-fixture', title: 't', description: 'd', audacity: 'a', intro: 'i', steps: [open(), importAudio('missing')], tips: [],
	}, LESSON_FIXTURES), RangeError);
});

test('every step kind describes itself with the labels the browser suite clicks', () => {
	const described = new Set();
	for (const lesson of SOUNDSCAPER_LESSONS) {
		for (const entry of lesson.steps) {
			const sentence = describe(entry);
			assert.ok(sentence.length > 0);
			described.add(entry.kind);
		}
	}
	assert.match(describe(menu(['Select', 'Select all'])), /\*\*Select → Select all\*\*/u);
	assert.match(describe(effect({ group: 'Fading', name: 'Fade In', direct: true })), /\*\*Effect → Fading → Fade In\*\*/u);
	assert.match(
		describe(effect({ group: 'Volume and compression', name: 'Normalize', settings: [{ label: 'Peak amplitude', value: '-3' }] })),
		/set \*\*Peak amplitude\*\* to `-3`, then press \*\*Apply to selection\*\*/u,
	);
	assert.match(describe(importAudio('music-loop')), /`lesson-music-loop\.wav`/u);
	assert.match(describe(check({ clips: 2, clip: 'Mix' })), /2 clips and a clip named \*\*Mix\*\*/u);
	assert.throws(() => describe({ kind: 'unknown' }), RangeError);
	for (const kind of STEP_KINDS) {
		if (!['note'].includes(kind)) assert.ok(described.has(kind), `no lesson exercises the ${kind} step`);
	}
});

test('lesson pages carry the generated banner, the Audacity aside, and every step in order', () => {
	const pages = renderLessonPages({ groups: SOUNDSCAPER_LESSON_GROUPS, describeStep, fixtureFile: lessonFixtureFile });
	assert.equal(pages.size, SOUNDSCAPER_LESSONS.length + 1);
	const index = pages.get('index.md');
	assert.match(index, /title: "Lessons"/u);
	for (const lesson of SOUNDSCAPER_LESSONS) {
		const page = pages.get(`${lesson.id}.md`);
		assert.ok(page, `missing page for ${lesson.id}`);
		assert.match(page, /<!-- Generated by `node scripts\/docs-reference\.mjs`\. Do not edit\. -->/u);
		assert.match(page, new RegExp(`title: ${JSON.stringify(lesson.title).replace(/[.*+?^${}()|[\]\\]/gu, '\\$&')}`, 'u'));
		assert.match(page, /:::note\[Coming from Audacity\?\]/u);
		assert.match(page, /## Steps\n\n1\. Open Soundscaper\./u);
		assert.match(page, new RegExp(`\n${String(lesson.steps.length)}\\. `, 'u'));
		assert.match(page, /## Tips\n\n- /u);
		assert.match(page, /tests\/browser\/soundscaper-lessons\.spec\.js/u);
		assert.match(index, new RegExp(`\\[${lesson.title.replace(/[.*+?^${}()|[\]\\]/gu, '\\$&')}\\]\\(/lessons/${lesson.id}/\\)`, 'u'));
	}
	assert.throws(() => renderLessonPages({ groups: [], describeStep, fixtureFile: lessonFixtureFile }), TypeError);
});
