/* SPDX-License-Identifier: AGPL-3.0-only */

import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import test, { after } from 'node:test';

import { buildAttestedMacroSandboxModule } from '../src/common/editor/macro-script/dynamic-source-contract.js';
import { assembleE2ECoverageCapture } from '../scripts/lib/e2e-coverage-assembler.mjs';
import {
	MACRO_DYNAMIC_COVERAGE_URL_PREFIX,
	MACRO_FIXED_COVERAGE_SOURCE_PATH,
	macroDynamicCoverageScript,
	macroDynamicSourceUrl,
} from '../scripts/lib/macro-dynamic-coverage.mjs';
import {
	cleanupE2ECoverageAssemblerFixtures,
	makeFixture,
	readJson,
	readProfiles,
	recordBrowserEvidence,
	sourceLineLengths,
	v8Entry,
	write,
	writeJson,
} from './helpers/e2e-coverage-assembler-fixture.mjs';

const MACRO_PROGRAM = 'globalThis.__fixtureMacroExecuted = true;';
const BROWSER_PROFILE = 'coverage/v8-browser/browser.json';

after(cleanupE2ECoverageAssemblerFixtures);

test('an authenticated macro inventories only its fixed wrapper source and reuses its attested map', () => {
	const fixture = makeFixture();
	const repeat = readJson(join(fixture.runRoot, BROWSER_PROFILE));
	const dynamicUrl = repeat.result.find(({ url }) => url.startsWith(MACRO_DYNAMIC_COVERAGE_URL_PREFIX))?.url;
	assert.ok(dynamicUrl);
	delete repeat['source-map-cache'][dynamicUrl];
	writeJson(join(fixture.runRoot, 'coverage/v8-browser/browser-repeat.json'), repeat);
	const assembled = assembleE2ECoverageCapture(fixture);
	const script = assembled.captureIndex.scripts.find(({ coverageUrl }) => (
		coverageUrl.includes('/dynamic/browser/soundscaper/renderer/macro-module-v1/')
	));
	assert.ok(script, 'the observed generated executable must be inventoried');
	assert.deepEqual(script.sources, [MACRO_FIXED_COVERAGE_SOURCE_PATH]);
	const fixedSource = assembled.captureIndex.sources.find(({ path }) => (
		path === MACRO_FIXED_COVERAGE_SOURCE_PATH
	));
	assert.deepEqual(fixedSource.surfaces, ['browser-chromium-soundscaper-renderer']);
	assert.equal(assembled.captureIndex.sources.some(({ path }) => path.includes('fixtureMacroExecuted')), false);

	const profiles = readProfiles(join(
		assembled.outputRoot,
		'profiles/browser-chromium-soundscaper-renderer',
	));
	const cache = profiles
		.map((profile) => profile['source-map-cache'][script.coverageUrl])
		.find(Boolean);
	assert.deepEqual(cache.data.sources, [
		`file:///__soundscaper_repo__/${MACRO_FIXED_COVERAGE_SOURCE_PATH}`,
	]);
	assert.doesNotMatch(cache.data.sourcesContent[0], /fixtureMacroExecuted/u,
		'the author-owned program must stay outside the executable source denominator');
	const executable = readFileSync(join(assembled.outputRoot, script.artifactPath), 'utf8');
	assert.match(executable, /fixtureMacroExecuted/u,
		'the exact executed bytes remain available to audit V8 offsets');
});

test('assembly refuses to let the fixed macro wrapper vanish from the union', () => {
	const fixture = makeFixture();
	const { path, profile, url } = macroProfile(fixture);
	profile.result = profile.result.filter((entry) => entry.url !== url);
	delete profile['script-source-cache'][url];
	delete profile['source-map-cache'][url];
	writeJson(path, profile);

	assert.throws(
		() => assembleE2ECoverageCapture(fixture),
		/observed no authenticated macro dynamic module/u,
	);
});

test('assembly rejects spoofed macro source bytes and source maps', () => {
	const sourceSpoof = makeFixture();
	const captured = macroProfile(sourceSpoof);
	captured.profile['script-source-cache'][captured.url] = captured.source.replace(
		MACRO_PROGRAM,
		'globalThis.__fixtureMacroExecuted = false;',
	);
	writeJson(captured.path, captured.profile);
	assert.throws(
		() => assembleE2ECoverageCapture(sourceSpoof),
		/macro dynamic source URL does not match its exact generated bytes/iu,
	);

	const mapSpoof = makeFixture();
	const mapped = macroProfile(mapSpoof);
	mapped.profile['source-map-cache'][mapped.url].data.mappings += 'A';
	writeJson(mapped.path, mapped.profile);
	assert.throws(
		() => assembleE2ECoverageCapture(mapSpoof),
		/stale macro dynamic source-map evidence/iu,
	);
});

test('assembly rejects an unknown captured packaged source even without a V8 entry', () => {
	const fixture = makeFixture();
	const path = join(fixture.runRoot, 'coverage/v8-packaged/packaged-soundscaper.json');
	const profile = readJson(path);
	profile['script-source-cache']['blob:https://attacker.invalid/unobserved'] = 'globalThis.unowned = true;';
	writeJson(path, profile);

	assert.throws(
		() => assembleE2ECoverageCapture(fixture),
		/unmapped first-party packaged script.*attacker\.invalid/iu,
	);
});

test('assembly binds the macro import to the exact digest-bound prelude asset', () => {
	const wrongUrl = makeFixture();
	replaceMacro(wrongUrl, 'http://127.0.0.1:4322/assets/app.js');
	assert.throws(
		() => assembleE2ECoverageCapture(wrongUrl),
		/does not import an exact emitted soundscaper sandbox prelude asset/iu,
	);

	const wrongBytes = makeFixture();
	const site = join(wrongBytes.evidenceRoot, 'browser/soundscaper/site');
	write(join(site, 'assets/sandbox-prelude-fixture.js'), 'globalThis.__changedPrelude = true;\n');
	recordBrowserEvidence(site, 'soundscaper', wrongBytes.expectedRevision);
	assert.throws(
		() => assembleE2ECoverageCapture(wrongBytes),
		/emitted soundscaper macro sandbox prelude bytes are stale/iu,
	);
});

test('assembly inventories and requires an observed emitted script whose map has no sources', () => {
	const fixture = makeFixture();
	const source = 'globalThis.generatedFacade = true;\n';
	const map = {
		file: 'generated-facade.js',
		mappings: '',
		names: [],
		sourceRoot: '',
		sources: [],
		sourcesContent: [],
		version: 3,
		x_soundscaper_source_sha256: [],
	};
	const site = join(fixture.evidenceRoot, 'browser/soundscaper/site');
	write(join(site, 'assets/generated-facade.js'), source);
	writeJson(join(fixture.evidenceRoot, 'browser/soundscaper/source-maps/generated-facade.js.map'), map);
	recordBrowserEvidence(site, 'soundscaper', fixture.expectedRevision);
	const profilePath = join(fixture.runRoot, BROWSER_PROFILE);
	const profile = readJson(profilePath);
	const coverageUrl = 'file:///__soundscaper_e2e__/browser/soundscaper/assets/generated-facade.js';
	profile.result.push(v8Entry(coverageUrl));
	writeJson(profilePath, profile);

	const assembled = assembleE2ECoverageCapture(fixture);
	const script = assembled.captureIndex.scripts.find(({ coverageUrl: url }) => url === coverageUrl);
	assert.ok(script, 'the nonempty emitted executable must remain in the inventory');
	assert.match(script.sources[0], /^generated\/[a-f\d]{64}\.js$/u);
	assert.equal(assembled.captureIndex.sources.find(({ path }) => path === script.sources[0])?.origin, 'artifact');

	const unobserved = makeFixture();
	const unobservedSite = join(unobserved.evidenceRoot, 'browser/soundscaper/site');
	write(join(unobservedSite, 'assets/generated-facade.js'), source);
	writeJson(
		join(unobserved.evidenceRoot, 'browser/soundscaper/source-maps/generated-facade.js.map'),
		map,
	);
	recordBrowserEvidence(unobservedSite, 'soundscaper', unobserved.expectedRevision);
	assert.throws(
		() => assembleE2ECoverageCapture(unobserved),
		/executable equivalence.*generated-facade\.js/u,
	);
});

test('assembly keeps emitted JavaScript raw when its map owns only non-executable sources', () => {
	const fixture = makeFixture();
	const source = 'globalThis.nonExecutableSourceFacade = true;\n';
	const sourcePaths = ['vendor/theme.css', 'vendor/config.json'];
	const sourceContents = ['body { color: CanvasText; }\n', '{"enabled":true}\n'];
	const map = {
		file: 'nonexec-facade.js',
		mappings: 'AAAA',
		names: [],
		sourceRoot: '',
		sources: sourcePaths.map((path) => `file:///fixture/${path}`),
		sourcesContent: sourceContents,
		version: 3,
		x_soundscaper_source_sha256: sourceContents.map(() => null),
	};
	const site = join(fixture.evidenceRoot, 'browser/soundscaper/site');
	write(join(site, 'assets/nonexec-facade.js'), source);
	writeJson(join(
		fixture.evidenceRoot,
		'browser/soundscaper/source-maps/nonexec-facade.js.map',
	), map);
	recordBrowserEvidence(site, 'soundscaper', fixture.expectedRevision);
	const profilePath = join(fixture.runRoot, BROWSER_PROFILE);
	const profile = readJson(profilePath);
	const coverageUrl = 'file:///__soundscaper_e2e__/browser/soundscaper/assets/nonexec-facade.js';
	profile.result.push(v8Entry(coverageUrl));
	writeJson(profilePath, profile);

	const assembled = assembleE2ECoverageCapture(fixture);
	const script = assembled.captureIndex.scripts.find(({ coverageUrl: url }) => url === coverageUrl);
	assert.ok(script, 'nonempty JavaScript must not disappear behind CSS/JSON mappings');
	assert.match(script.sources[0], /^generated\/[a-f\d]{64}\.js$/u);
	assert.equal(assembled.captureIndex.sources.find(({ path }) => path === script.sources[0])?.origin, 'artifact');
});

test('schema-v2 packaged profiles bind the launched app.asar path and bytes to build evidence', () => {
	for (const mutate of [
		(metadata) => { metadata.schemaVersion = 1; },
		(metadata) => { metadata.appAsar.path = '/opt/soundscaper/resources/other.asar'; },
		(metadata) => { metadata.platform = 'darwin'; },
		(metadata) => { metadata.appAsar.afterCollection.byteLength += 1; },
		(metadata) => {
			metadata.appAsar.beforeLaunch.sha256 = '0'.repeat(64);
			metadata.appAsar.afterCollection.sha256 = '0'.repeat(64);
		},
	]) {
		const fixture = makeFixture();
		const path = join(fixture.runRoot, 'coverage/v8-packaged/packaged-soundscaper.json');
		const profile = readJson(path);
		mutate(profile['soundscaper-packaged-runtime']);
		writeJson(path, profile);
		assert.throws(
			() => assembleE2ECoverageCapture(fixture),
			/invalid (?:runtime metadata|app\.asar identity)/iu,
		);
	}
});

function macroProfile(fixture) {
	const path = join(fixture.runRoot, BROWSER_PROFILE);
	const profile = readJson(path);
	const entry = profile.result.find(({ url }) => url.startsWith(MACRO_DYNAMIC_COVERAGE_URL_PREFIX));
	assert.ok(entry, 'the fixture must contain a macro dynamic entry');
	return {
		path,
		profile,
		source: profile['script-source-cache'][entry.url],
		url: entry.url,
	};
}

function replaceMacro(fixture, preludeUrl) {
	const captured = macroProfile(fixture);
	captured.profile.result = captured.profile.result.filter((entry) => entry.url !== captured.url);
	delete captured.profile['script-source-cache'][captured.url];
	delete captured.profile['source-map-cache'][captured.url];
	const source = buildAttestedMacroSandboxModule(`import ${JSON.stringify(preludeUrl)};`, MACRO_PROGRAM);
	const dynamic = macroDynamicCoverageScript({
		repositoryRoot: fixture.repositoryRoot,
		source,
		url: macroDynamicSourceUrl(source),
	});
	captured.profile.result.push(v8Entry(dynamic.coverageUrl));
	captured.profile['script-source-cache'][dynamic.coverageUrl] = source;
	captured.profile['source-map-cache'][dynamic.coverageUrl] = {
		data: dynamic.sourceMap,
		lineLengths: sourceLineLengths(source),
		url: null,
	};
	writeJson(captured.path, captured.profile);
}
