/* SPDX-License-Identifier: AGPL-3.0-only */

import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test, { after } from 'node:test';

import {
	E2E_COVERAGE_CONFIGURATION,
	analyzeE2ECoverage,
	digestE2EInventory,
	parseE2ECoverageConfiguration,
	parseE2EInventory,
	parseE2ESurfaceManifest,
	validateE2EInventoryFiles,
	validateE2EExecutableObservation,
	validateRawV8Surface,
} from '../scripts/lib/e2e-coverage-contract.mjs';
import { e2eExecutableCoverageKey } from '../scripts/lib/e2e-coverage-integrity.mjs';

const workspaces = [];

after(() => {
	for (const workspace of workspaces) rmSync(workspace, { recursive: true, force: true });
});

test('the E2E gate requires every browser and packaged Electron realm at literal 100%', () => {
	assert.deepEqual(E2E_COVERAGE_CONFIGURATION.thresholds, {
		lines: 100,
		statements: 100,
		functions: 100,
		branches: 100,
	});
	assert.deepEqual(E2E_COVERAGE_CONFIGURATION.requiredSurfaces.map(({ id }) => id), [
		'browser-chromium-framescaper-renderer',
		'browser-chromium-soundscaper-renderer',
		'nightly-electron-framescaper-main',
		'nightly-electron-framescaper-preload',
		'nightly-electron-framescaper-renderer',
		'nightly-electron-soundscaper-main',
		'nightly-electron-soundscaper-preload',
		'nightly-electron-soundscaper-renderer',
	]);
	assert.deepEqual(
		new Set(E2E_COVERAGE_CONFIGURATION.requiredSurfaces.map(({ coverageFormat }) => coverageFormat)),
		new Set(['v8']),
		'every mandatory surface must supply profiles, not only a claimed summary',
	);
	assert.match(E2E_COVERAGE_CONFIGURATION.reason, /separate from Node and unit coverage/u);
});

test('the configuration cannot weaken or omit an E2E coverage dimension', () => {
	const configuration = structuredClone(E2E_COVERAGE_CONFIGURATION);
	configuration.thresholds.branches = 99.99;
	assert.throws(() => parseE2ECoverageConfiguration(configuration), /branches threshold must be exactly 100/u);

	delete configuration.thresholds.functions;
	assert.throws(() => parseE2ECoverageConfiguration(configuration), /functions threshold must be exactly 100/u);
});

test('the executable inventory is canonical, digest-bound and owns every script', () => {
	const fixture = makeFixture();
	const inventory = parseE2EInventory(fixture.inventory, E2E_COVERAGE_CONFIGURATION);

	assert.equal(inventory.digest, digestE2EInventory(inventory));
	assert.equal(inventory.sources.length, fixture.sources.length);
	assert.equal(inventory.scripts.length, fixture.surfaces.length);

	const missingScript = withDigest({
		...fixture.inventory,
		scripts: fixture.inventory.scripts.slice(1),
	});
	assert.throws(
		() => parseE2EInventory(missingScript, E2E_COVERAGE_CONFIGURATION),
		/has no executable scripts/u,
	);

	const reordered = withDigest({
		...fixture.inventory,
		sources: [...fixture.inventory.sources].reverse(),
	});
	assert.throws(
		() => parseE2EInventory(reordered, E2E_COVERAGE_CONFIGURATION),
		/inventory sources must be sorted/u,
	);

	assert.throws(
		() => parseE2EInventory({ ...fixture.inventory, digest: sha256('wrong') }, E2E_COVERAGE_CONFIGURATION),
		/inventory digest does not match/u,
	);
});

test('repository and preserved generated sources are hash-checked against their exact bytes', () => {
	const fixture = makeFixture();
	const inventory = parseE2EInventory(fixture.inventory, E2E_COVERAGE_CONFIGURATION);

	assert.deepEqual(validateE2EInventoryFiles(inventory, fixture.workspace, fixture.artifactRoot), []);
	writeFileSync(join(fixture.artifactRoot, fixture.generatedArtifactPath), 'changed generated bytes\n');
	assert.deepEqual(validateE2EInventoryFiles(inventory, fixture.workspace, fixture.artifactRoot), [
		`Executable source ${fixture.generatedPath} is stale: its bytes do not match the inventory SHA-256.`,
	]);
});

test('surface manifests bind their revision, inventory and inventoried script hashes', () => {
	const fixture = makeFixture();
	const inventory = parseE2EInventory(fixture.inventory, E2E_COVERAGE_CONFIGURATION);
	const surface = fixture.surfaces[0];
	const manifest = surfaceManifest(fixture, surface);

	assert.equal(parseE2ESurfaceManifest(manifest, inventory, E2E_COVERAGE_CONFIGURATION).surface, surface);
	assert.throws(
		() => parseE2ESurfaceManifest({ ...manifest, sourceRevision: 'f'.repeat(40) }, inventory, E2E_COVERAGE_CONFIGURATION),
		/source revision does not match/u,
	);
	assert.throws(
		() => parseE2ESurfaceManifest({ ...manifest, inventoryDigest: sha256('other') }, inventory, E2E_COVERAGE_CONFIGURATION),
		/inventory digest does not match/u,
	);
	assert.throws(
		() => parseE2ESurfaceManifest({ ...manifest, inventoriedScripts: [] }, inventory, E2E_COVERAGE_CONFIGURATION),
		/did not attest every inventoried script/u,
	);
	assert.throws(
		() => parseE2ESurfaceManifest({
			...manifest,
			coverage: { format: 'istanbul', path: 'coverage-final.json' },
		}, inventory, E2E_COVERAGE_CONFIGURATION),
		/must name a safe Istanbul file or V8 directory/u,
	);
});

test('a raw V8 surface contributes to the union without requiring duplicate scripts', () => {
	const fixture = makeFixture();
	const surface = fixture.surfaces[0];
	const original = fixture.inventory.scripts.find((candidate) => candidate.surface === surface);
	const inventory = parseE2EInventory(withDigest({
		...fixture.inventory,
		scripts: [...fixture.inventory.scripts, {
			...original,
			id: `${surface}/zz-duplicate.js`,
			coverageUrl: `file:///__soundscaper_e2e__/${surface}/zz-duplicate.js`,
		}].sort((left, right) => left.id.localeCompare(right.id)),
	}), E2E_COVERAGE_CONFIGURATION);
	const script = inventory.scripts.find((candidate) => candidate.surface === surface);

	assert.deepEqual(validateRawV8Surface([{ result: [v8Entry(script.coverageUrl)] }], surface, inventory), []);
	assert.deepEqual(validateE2EExecutableObservation(
		[script.coverageUrl],
		inventory.scripts.filter((candidate) => candidate.surface === surface),
	), [], 'one observed URL satisfies a byte-and-map-identical executable class');
	assert.deepEqual(validateRawV8Surface([], surface, inventory), [
		`${surface} supplied no raw V8 coverage profiles.`,
	]);
	assert.deepEqual(validateRawV8Surface([{ result: [v8Entry('file:///unexpected.js')] }], surface, inventory), [
		`${surface} supplied no admitted executable coverage entries.`,
		`${surface} reported un-inventoried executable script file:///unexpected.js.`,
	]);
	const duplicate = inventory.scripts.find(({ id }) => id.endsWith('/zz-duplicate.js'));
	const distinct = {
		...duplicate,
		sourceMapSha256: sha256('distinct map'),
	};
	distinct.coverageKey = e2eExecutableCoverageKey(distinct);
	assert.match(
		validateE2EExecutableObservation([script.coverageUrl], [script, distinct]).join('\n'),
		/did not execute executable equivalence.*zz-duplicate/u,
	);
});

test('coverage from all required surfaces merges to a literal four-metric 100%', () => {
	const fixture = makeFixture({ sharedBrowserSource: true });
	const inventory = parseE2EInventory(fixture.inventory, E2E_COVERAGE_CONFIGURATION);
	const { manifests, coverageBySurface } = completeEvidence(fixture, inventory);
	const browserSurfaces = fixture.surfaces.slice(0, 2);
	const sharedPath = fixture.sources.find((source) => (
		browserSurfaces.every((surface) => source.surfaces.includes(surface))
	)).path;

	coverageBySurface[browserSurfaces[0]][sharedPath] = fileCoverage(sharedPath, {
		statements: [1, 0],
		functions: [1],
		branches: [[1, 0]],
	});
	coverageBySurface[browserSurfaces[1]][sharedPath] = fileCoverage(sharedPath, {
		statements: [0, 1],
		functions: [0],
		branches: [[0, 1]],
	});

	const result = analyzeE2ECoverage({
		configuration: E2E_COVERAGE_CONFIGURATION,
		inventory,
		surfaceManifests: manifests,
		coverageBySurface,
		expectedRevision: fixture.inventory.sourceRevision,
	});

	assert.deepEqual(result.failures, []);
	for (const metric of ['lines', 'statements', 'functions', 'branches']) {
		assert.equal(result.metrics[metric].percentage, 100);
		assert.equal(result.metrics[metric].covered, result.metrics[metric].total);
	}
});

test('one uncovered statement, function or branch fails the E2E union instead of rounding to 100%', () => {
	const fixture = makeFixture();
	const inventory = parseE2EInventory(fixture.inventory, E2E_COVERAGE_CONFIGURATION);
	const { manifests, coverageBySurface } = completeEvidence(fixture, inventory);
	const surface = fixture.surfaces[0];
	const path = fixture.sources.find((source) => source.surfaces.includes(surface)).path;
	coverageBySurface[surface][path] = fileCoverage(path, {
		statements: [1, 0],
		functions: [0],
		branches: [[1, 0]],
	});

	const result = analyzeE2ECoverage({
		configuration: E2E_COVERAGE_CONFIGURATION,
		inventory,
		surfaceManifests: manifests,
		coverageBySurface,
		expectedRevision: fixture.inventory.sourceRevision,
	});

	assert.equal(result.metrics.statements.percentage < 100, true);
	assert.equal(result.metrics.functions.percentage < 100, true);
	assert.equal(result.metrics.branches.percentage < 100, true);
	assert.match(result.failures.join('\n'), /statements coverage is .* below the required 100%/u);
	assert.match(result.failures.join('\n'), /functions coverage is .* below the required 100%/u);
	assert.match(result.failures.join('\n'), /branches coverage is .* below the required 100%/u);
});

test('missing surfaces, missing inventory sources and generic Node coverage fail closed', () => {
	const fixture = makeFixture();
	const inventory = parseE2EInventory(fixture.inventory, E2E_COVERAGE_CONFIGURATION);
	const { manifests, coverageBySurface } = completeEvidence(fixture, inventory);
	delete manifests[fixture.surfaces[0]];
	const missingPath = fixture.sources.find((source) => source.surfaces.includes(fixture.surfaces[1])).path;
	delete coverageBySurface[fixture.surfaces[1]][missingPath];
	coverageBySurface[fixture.surfaces[2]]['tests/unit-only.test.js'] = fileCoverage('tests/unit-only.test.js');

	const result = analyzeE2ECoverage({
		configuration: E2E_COVERAGE_CONFIGURATION,
		inventory,
		surfaceManifests: manifests,
		coverageBySurface,
		expectedRevision: fixture.inventory.sourceRevision,
	});

	assert.match(result.failures.join('\n'), /is missing its surface manifest/u);
	assert.match(result.failures.join('\n'), /reported no coverage for executable source/u);
	assert.match(result.failures.join('\n'), /un-inventoried source tests\/unit-only\.test\.js/u);
});

test('incompatible coverage maps and stale revisions cannot be combined', () => {
	const fixture = makeFixture({ sharedBrowserSource: true });
	const inventory = parseE2EInventory(fixture.inventory, E2E_COVERAGE_CONFIGURATION);
	const { manifests, coverageBySurface } = completeEvidence(fixture, inventory);
	const path = fixture.sources.find((source) => fixture.surfaces.slice(0, 2).every((surface) => (
		source.surfaces.includes(surface)
	))).path;
	coverageBySurface[fixture.surfaces[1]][path] = fileCoverage(path, { startLine: 20 });
	manifests[fixture.surfaces[2]] = { ...manifests[fixture.surfaces[2]], sourceRevision: 'f'.repeat(40) };

	const result = analyzeE2ECoverage({
		configuration: E2E_COVERAGE_CONFIGURATION,
		inventory,
		surfaceManifests: manifests,
		coverageBySurface,
		expectedRevision: 'a'.repeat(40),
	});

	assert.match(result.failures.join('\n'), /inventory revision .* does not match the checked-out revision/u);
	assert.match(result.failures.join('\n'), /source revision does not match the inventory/u);
	assert.match(result.failures.join('\n'), /incompatible coverage maps/u);
});

function makeFixture({ sharedBrowserSource = false } = {}) {
	const workspace = mkdtempSync(join(tmpdir(), 'soundscaper-e2e-contract-'));
	workspaces.push(workspace);
	const artifactRoot = join(workspace, 'coverage/e2e');
	mkdirSync(join(workspace, 'src'), { recursive: true });
	mkdirSync(join(artifactRoot, 'executables'), { recursive: true });
	const surfaces = E2E_COVERAGE_CONFIGURATION.requiredSurfaces.map(({ id }) => id);
	const generatedPath = 'generated/nightly-electron-soundscaper-main/main.mjs';
	const generatedArtifactPath = 'executables/soundscaper/main.mjs';
	mkdirSync(join(artifactRoot, 'executables/soundscaper'), { recursive: true });
	const sources = surfaces.map((surface, index) => {
		if (index === 2) {
			writeFileSync(join(artifactRoot, generatedArtifactPath), 'export const packaged = true;\n');
			return {
				path: generatedPath,
				origin: 'artifact',
				artifactPath: generatedArtifactPath,
				sha256: sha256('export const packaged = true;\n'),
				surfaces: [surface],
			};
		}
		const path = `src/surface-${index}.js`;
		const body = `export const surface${index} = true;\n`;
		writeFileSync(join(workspace, path), body);
		return { path, origin: 'repository', sha256: sha256(body), surfaces: [surface] };
	});
	if (sharedBrowserSource) {
		sources[0].surfaces = surfaces.slice(0, 2);
		sources.splice(1, 1);
	}
	const scripts = surfaces.map((surface, index) => {
		const path = `executables/script-${index}.js`;
		const body = `globalThis.surface${index} = true;\n`;
		writeFileSync(join(artifactRoot, path), body);
		const source = sources.find((candidate) => candidate.surfaces.includes(surface));
		const script = {
			id: `${surface}/script-${index}.js`,
			surface,
			artifactPath: path,
			coverageUrl: `file:///__soundscaper_e2e__/${surface}/script-${index}.js`,
			sha256: sha256(body),
			sourceMapSha256: null,
			sources: [source.path],
		};
		return {
			...script,
			coverageKey: e2eExecutableCoverageKey(script),
		};
	});
	const sourceRevision = commitFixtureRepository(workspace);
	const unsigned = {
		schemaVersion: 1,
		kind: 'soundscaper-e2e-executable-inventory',
		sourceRevision,
		sources: [...sources].sort((left, right) => left.path.localeCompare(right.path)),
		scripts: [...scripts].sort((left, right) => left.id.localeCompare(right.id)),
	};
	return {
		workspace,
		artifactRoot,
		surfaces,
		sources: unsigned.sources,
		inventory: withDigest(unsigned),
		generatedPath,
		generatedArtifactPath,
	};
}

function completeEvidence(fixture, inventory) {
	const manifests = {};
	const coverageBySurface = {};
	for (const surface of fixture.surfaces) {
		manifests[surface] = surfaceManifest(fixture, surface);
		coverageBySurface[surface] = {};
		for (const source of inventory.sources.filter((candidate) => candidate.surfaces.includes(surface))) {
			coverageBySurface[surface][source.path] = fileCoverage(source.path);
		}
	}
	return { manifests, coverageBySurface };
}

function surfaceManifest(fixture, surface) {
	return {
		schemaVersion: 1,
		kind: 'soundscaper-e2e-coverage-surface',
		surface,
		sourceRevision: fixture.inventory.sourceRevision,
		inventoryDigest: fixture.inventory.digest,
		coverage: {
			format: 'v8',
			path: 'v8',
			files: [{ path: 'profile.json', byteLength: 3, sha256: sha256('{}\n') }],
		},
		inventoriedScripts: fixture.inventory.scripts
			.filter((script) => script.surface === surface)
			.map(({ id, sha256: digest }) => ({ id, sha256: digest })),
	};
}

function fileCoverage(path, { statements = [1], functions = [1], branches = [[1, 1]], startLine = 1 } = {}) {
	const statementMap = Object.fromEntries(statements.map((_, index) => [
		String(index),
		location(startLine + index),
	]));
	return {
		path,
		statementMap,
		fnMap: Object.fromEntries(functions.map((_, index) => [String(index), {
			name: `function${index}`,
			decl: location(startLine + index),
			loc: location(startLine + index),
			line: startLine + index,
		}])),
		branchMap: Object.fromEntries(branches.map((counts, index) => [String(index), {
			type: 'if',
			line: startLine + index,
			loc: location(startLine + index),
			locations: counts.map(() => location(startLine + index)),
		}])),
		s: Object.fromEntries(statements.map((count, index) => [String(index), count])),
		f: Object.fromEntries(functions.map((count, index) => [String(index), count])),
		b: Object.fromEntries(branches.map((counts, index) => [String(index), counts])),
	};
}

function location(line) {
	return { start: { line, column: 0 }, end: { line, column: 10 } };
}

function v8Entry(url) {
	return {
		scriptId: '1',
		url,
		functions: [{ functionName: '', isBlockCoverage: true, ranges: [{ startOffset: 0, endOffset: 1, count: 1 }] }],
	};
}

function withDigest(inventory) {
	return { ...inventory, digest: digestE2EInventory(inventory) };
}

function sha256(value) {
	return `sha256:${createHash('sha256').update(value).digest('hex')}`;
}

function commitFixtureRepository(repositoryRoot) {
	for (const args of [
		['init', '--quiet'],
		['config', 'user.name', 'Coverage Fixture'],
		['config', 'user.email', 'coverage@example.invalid'],
		['add', 'src'],
		['commit', '--quiet', '-m', 'fixture'],
	]) {
		const outcome = spawnSync('git', args, { cwd: repositoryRoot, encoding: 'utf8' });
		assert.equal(outcome.status, 0, outcome.stderr);
	}
	return spawnSync('git', ['rev-parse', 'HEAD'], { cwd: repositoryRoot, encoding: 'utf8' }).stdout.trim();
}
