/* SPDX-License-Identifier: AGPL-3.0-only */

import assert from 'node:assert/strict';
import { resolve } from 'node:path';
import test from 'node:test';

import v8ToIstanbul from 'v8-to-istanbul';

import {
	buildMacroSandboxModule,
} from '../src/common/editor/macro-script/sandbox-client.ts';
import {
	MACRO_SANDBOX_SOURCE_URL_PREFIX,
} from '../src/common/editor/macro-script/dynamic-source-contract.js';
import {
	MACRO_FIXED_COVERAGE_SOURCE_PATH,
	attestMacroDynamicSource,
	macroDynamicCoverageScript,
} from '../scripts/lib/macro-dynamic-coverage.mjs';

const REPOSITORY_ROOT = resolve(import.meta.dirname, '..');
const PRELUDE = 'import "https://soundscaper.org/assets/sandbox-prelude-abc123.js";';
const PROGRAM = [
	'const sourceURLLookalike = "//# sourceURL=soundscaper-macro://module-v1/spoof";',
	'await sound.select.all();',
].join('\n');

test('a macro module names exact recipe and author-program digests', () => {
	const source = buildMacroSandboxModule(PRELUDE, PROGRAM);
	const sourceURL = finalSourceURL(source);

	assert.match(
		sourceURL,
		new RegExp(`^${escapeRegExp(MACRO_SANDBOX_SOURCE_URL_PREFIX)}[a-f0-9]{64}/[a-f0-9]{64}\\.mjs$`, 'u'),
	);
	const attested = attestMacroDynamicSource(sourceURL, source);
	assert.equal(attested.program, PROGRAM);
	assert.equal(attested.preludeModuleUrl, 'https://soundscaper.org/assets/sandbox-prelude-abc123.js');
	assert.equal(attested.preludeSource, PRELUDE);
	assert.equal(source.slice(attested.programStart, attested.programEnd), PROGRAM);
	assert.equal(attested.sourceURL, sourceURL);
});

test('macro attestation rejects a spoofed name, body, or recipe', () => {
	const source = buildMacroSandboxModule(PRELUDE, PROGRAM);
	const sourceURL = finalSourceURL(source);
	const alternate = buildMacroSandboxModule(PRELUDE, 'await sound.select.none();');

	assert.throws(
		() => attestMacroDynamicSource(sourceURL, alternate),
		/macro dynamic source URL does not match its exact generated bytes/iu,
	);
	assert.throws(
		() => attestMacroDynamicSource(sourceURL, source.replace(PRELUDE, 'globalThis.untrusted = true;')),
		/macro dynamic source (?:URL does not match its exact generated bytes|has no canonical static prelude import)/iu,
	);
	assert.throws(
		() => attestMacroDynamicSource(
			'soundscaper-macro://unknown-v2/' + '0'.repeat(64) + '/' + '1'.repeat(64) + '.mjs',
			source,
		),
		/unsupported macro dynamic source identity/iu,
	);
	const nonCanonicalURL = sourceURL.replace(
		'soundscaper-macro://',
		'SOUNDSCAPER-MACRO://',
	);
	assert.throws(
		() => attestMacroDynamicSource(nonCanonicalURL, source.replace(sourceURL, nonCanonicalURL)),
		/unsupported macro dynamic source identity/iu,
	);
});

test('macro dynamic coverage maps fixed lines and leaves only the author span unmapped', () => {
	const source = buildMacroSandboxModule(PRELUDE, PROGRAM);
	const sourceURL = finalSourceURL(source);
	const resolved = macroDynamicCoverageScript({
		repositoryRoot: REPOSITORY_ROOT,
		source,
		url: sourceURL,
	});

	assert.ok(resolved);
	assert.match(resolved.coverageUrl, /^file:\/\/\/__soundscaper_e2e__\/dynamic\/macro-module-v1\//u);
	assert.equal(resolved.source, source);
	assert.deepEqual(resolved.sourceMap.sources, [
		`file:///__soundscaper_repo__/${MACRO_FIXED_COVERAGE_SOURCE_PATH}`,
	]);
	assert.equal(resolved.sourceMap.sourcesContent.length, 1);
	assert.doesNotMatch(resolved.sourceMap.sourcesContent[0], /await sound\.select\.all/u,
		'the author-owned program must not enter the first-party denominator');

	const generatedMappings = resolved.sourceMap.mappings.split(';');
	const closeLine = 3 + (PROGRAM.match(/\n/gu)?.length ?? 0);
	assert.notEqual(generatedMappings[0], '', 'the fixed function wrapper is mapped');
	assert.notEqual(generatedMappings[1], '', 'the fixed strict directive is mapped');
	assert.deepEqual(
		generatedMappings.slice(2, closeLine),
		Array.from({ length: closeLine - 2 }, () => ''),
		'every generated line occupied by the authored program is unmapped',
	);
	for (const line of [closeLine, closeLine + 1, closeLine + 2]) {
		assert.notEqual(generatedMappings[line], '', `fixed generated line ${String(line + 1)} is mapped`);
	}
	assert.equal(generatedMappings[closeLine + 3], '', 'the sourceURL directive is not executable source');
});

test('the synthetic map counts the fixed wrapper without counting an uncovered author span', async () => {
	const source = buildMacroSandboxModule(PRELUDE, PROGRAM);
	const resolved = macroDynamicCoverageScript({
		repositoryRoot: REPOSITORY_ROOT,
		source,
		url: finalSourceURL(source),
	});
	assert.ok(resolved);
	const converter = v8ToIstanbul('/tmp/soundscaper-macro-module-v1.js', 0, {
		originalSource: resolved.sourceMap.sourcesContent[0],
		source,
		sourceMap: { sourcemap: resolved.sourceMap },
	});
	await converter.load();
	converter.applyCoverage([
		{
			functionName: '',
			isBlockCoverage: true,
			ranges: [{ startOffset: 0, endOffset: source.length, count: 1 }],
		},
		{
			functionName: '__macroMain',
			isBlockCoverage: true,
			ranges: [
				{ startOffset: 0, endOffset: resolved.attestation.programEnd + 3, count: 1 },
				{
					startOffset: resolved.attestation.programStart,
					endOffset: resolved.attestation.programEnd,
					count: 0,
				},
			],
		},
	]);
	const coverage = Object.values(converter.toIstanbul())[0];
	assert.ok(coverage, 'the fixed wrapper must produce Istanbul coverage');
	assert.ok(Object.values(coverage.s).every((count) => count > 0),
		'the deliberately uncovered author span must not reduce fixed-wrapper statement coverage');
	assert.ok(Object.values(coverage.f).every((count) => count > 0),
		'the generated macro entry function must count as executed');
});

test('non-macro script identities are left for the ordinary resolver', () => {
	assert.equal(macroDynamicCoverageScript({
		repositoryRoot: REPOSITORY_ROOT,
		source: 'void 0;',
		url: 'https://soundscaper.org/assets/app.js',
	}), null);
});

function finalSourceURL(source: string): string {
	const match = /\/\/[#@] sourceURL=(\S+)\n$/u.exec(source);
	assert.ok(match, 'the macro module must end with its source identity');
	return match[1];
}

function escapeRegExp(value: string): string {
	return value.replace(/[.*+?^${}()|[\]\\]/gu, '\\$&');
}
