import { SHARED_CAPABILITIES } from '../common/product-capabilities.js';
import { PRODUCT_IDENTITIES } from '../common/product-identities.js';

export const SOUNDSCAPER_PROFILE = {
	...PRODUCT_IDENTITIES.soundscaper,
	description: 'A local-first multitrack audio editor for the web and desktop.',
	enabledCommands: ['project', 'timeline', 'transport', 'audio-mix', 'audio-record', 'audio-generate', 'audio-effects', 'audio-spectral', 'audio-analysis', 'audio-macros', 'video-basic', 'export-audio', 'export-video'],
	panels: ['project-bin', 'track-list', 'mixer', 'effects', 'analysis', 'recording-meter', 'playback-meter'],
	importChoices: ['scape', 'audacity-project', 'audio', 'video', 'labels'],
	exportChoices: ['scape', 'aup4-audio-only', 'audio', 'video', 'labels', 'stems'],
	shortcuts: { disabledCommandIds: ['workspace-video-editor', 'video-effect-add'] },
	applicationFeatures: {},
	capabilities: {
		...SHARED_CAPABILITIES,
		assistanceAssets: true,
		audioRecording: true,
		audioGenerators: true,
		audioEffects: true,
		audioSpectralEditing: true,
		audioAnalysis: true,
		audioMacros: true,
		audioSampleEditing: true,
		audioAutomation: true,
		audioMixerGraph: true,
		audioTrackFreeze: true,
		videoEffects: false,
		videoAdjustmentLayers: false,
		videoCompositing: false,
		videoFreeze: false,
		videoGenerators: false,
		videoGeometry: false,
		videoKeyframes: false,
		videoMasksMattes: false,
		multicamera: false,
		musicalTimeline: true,
		nestedSequences: false,
		ofxEffects: false,
		timelineAnnotations: true,
		trackFolders: true,
		takeComp: true,
		timelineImages: false,
		audioWarp: true,
		sequenceTiming: true,
		videoRetime: false,
		videoCaptions: false,
		videoColorManagement: false,
		videoDenoise: false,
		videoGrading: false,
		videoMotionTracking: false,
		videoStabilization: false,
		videoStills: false,
		videoTimingAssets: true,
		videoTransitionDissolve: false,
		videoTransitions: false,
		sourceCharacteristics: true,
		masteringSequences: true,
		immersiveAdm: true,
	},
	desktop: {
		appId: 'org.soundscaper.desktop',
		scheme: 'soundscaper-app',
		sessionPartition: 'persist:soundscaper-v29',
		executableName: 'soundscaper',
		category: 'AudioVideo;Audio',
	},
};
