import { SHARED_CAPABILITIES } from '../common/product-capabilities.js';

export const FRAMESCAPER_PROFILE = {
	id: 'framescaper',
	name: 'Framescaper',
	description: 'A local-first video editor for the web and desktop.',
	basePath: '/framescaper',
	defaultWorkspace: 'video-editor',
	enabledCommands: ['project', 'timeline', 'transport', 'audio-mix', 'video-basic', 'video-effects', 'video-compositing', 'export-audio', 'export-video'],
	panels: ['project-bin', 'track-list', 'mixer', 'video-preview', 'source-monitor', 'video-effects', 'playback-meter'],
	importChoices: ['scape', 'audacity-project', 'audio', 'video', 'labels'],
	exportChoices: ['scape', 'audio', 'video', 'labels'],
	shortcuts: { disabledCommandIds: ['record', 'generate', 'selection-effect', 'spectral-edit', 'analyze', 'manage-macros', 'nyquist-prompt'] },
	applicationFeatures: { framescaperCapture: false, framescaperWebVcr: false },
	capabilities: {
		...SHARED_CAPABILITIES,
		audioRecording: false,
		audioGenerators: false,
		audioEffects: false,
		audioSpectralEditing: false,
		audioAnalysis: false,
		audioMacros: false,
		audioSampleEditing: false,
		audioAutomation: true,
		audioMixerGraph: true,
		audioTrackFreeze: false,
		videoEffects: true,
		videoAdjustmentLayers: true,
		videoCompositing: true,
		videoFreeze: true,
		videoGenerators: true,
		videoGeometry: true,
		videoKeyframes: true,
		videoMasksMattes: true,
		multicamera: true,
		musicalTimeline: false,
		nestedSequences: true,
		// V28 owns OFX authoring/state; execution remains a default-off desktop service gate.
		ofxEffects: true,
		timelineAnnotations: false,
		trackFolders: false,
		takeComp: false,
		audioWarp: false,
		sequenceTiming: true,
		videoRetime: true,
		videoCaptions: true,
		videoColorManagement: true,
		videoDenoise: true,
		videoGrading: true,
		videoMotionTracking: true,
		videoStabilization: true,
		videoStills: true,
		videoTimingAssets: true,
		videoTransitionDissolve: true,
		videoTransitions: true,
		sourceCharacteristics: true,
		masteringSequences: false,
		immersiveAdm: false,
	},
	desktop: {
		appId: 'org.framescaper.desktop',
		scheme: 'framescaper-app',
		sessionPartition: 'persist:framescaper-v1',
		executableName: 'framescaper',
		category: 'AudioVideo;Video',
	},
};
