// Generated from Audacity 3.7.7 bundled Nyquist plug-ins.
// The adjacent .ny files remain byte-for-byte copies of the pinned upstream sources.

export const NYQUIST_BUNDLED_PLUGIN_CATALOG = [
	{
		"id": "nyquist:adjustable-fade",
		"actionId": "nyquist:adjustable-fade",
		"fileName": "adjustable-fade.ny",
		"sourceCommit": "5ef610ed23260d6d648175735bb16b32536eb30b",
		"sha256": "8a2debdc1f446b3a63497aaedb7f4bcfaf5d567cbaeacdd34b714544ab8a064a",
		"category": "legacy",
		"name": "Adjustable Fade",
		"type": "process",
		"role": "process",
		"declaredTypes": ["process"],
		"isTool": false,
		"spectral": false,
		"author": "Steve Daulton",
		"release": "3.0.4-2",
		"copyright": "GNU General Public License v2.0 or later",
		"mergeClips": null,
		"restoreSplits": null,
		"debugButton": false,
		"debugEnabled": false,
		"debugFlags": [],
		"preview": ["linear","selection"],
		"controls": [{"variable":"TYPE","type":"choice","kind":"choice","label":"Fade Type","unit":"","defaultValue":0,"min":null,"max":null,"options":[{"value":0,"symbol":"Up","label":"Fade Up"},{"value":1,"symbol":"Down","label":"Fade Down"},{"value":2,"symbol":"SCurveUp","label":"S-Curve Up"},{"value":3,"symbol":"SCurveDown","label":"S-Curve Down"}],"fileFilters":null,"line":19},{"variable":"CURVE","type":"real","kind":"number","label":"Mid-fade Adjust (%)","unit":"","defaultValue":0,"min":-100,"max":100,"options":[],"fileFilters":null,"line":23},{"variable":"UNITS","type":"choice","kind":"choice","label":"Start/End as","unit":"","defaultValue":0,"min":null,"max":null,"options":[{"value":0,"symbol":"Percent","label":"% of Original"},{"value":1,"symbol":"dB","label":"dB Gain"}],"fileFilters":null,"line":24},{"variable":"GAIN0","type":"float-text","kind":"number","label":"Start (or end)","unit":"","defaultValue":0,"min":null,"max":null,"options":[],"fileFilters":null,"line":26},{"variable":"GAIN1","type":"float-text","kind":"number","label":"End (or start)","unit":"","defaultValue":100,"min":null,"max":null,"options":[],"fileFilters":null,"line":27},{"variable":"PRESET","type":"choice","kind":"choice","label":"Handy Presets (override controls)","unit":"","defaultValue":0,"min":null,"max":null,"options":[{"value":0,"symbol":"None","label":"None Selected"},{"value":1,"symbol":"LinearIn","label":"Linear In"},{"value":2,"symbol":"LinearOut","label":"Linear Out"},{"value":3,"symbol":"ExponentialIn","label":"Exponential In"},{"value":4,"symbol":"ExponentialOut","label":"Exponential Out"},{"value":5,"symbol":"LogarithmicIn","label":"Logarithmic In"},{"value":6,"symbol":"LogarithmicOut","label":"Logarithmic Out"},{"value":7,"symbol":"RoundedIn","label":"Rounded In"},{"value":8,"symbol":"RoundedOut","label":"Rounded Out"},{"value":9,"symbol":"CosineIn","label":"Cosine In"},{"value":10,"symbol":"CosineOut","label":"Cosine Out"},{"value":11,"symbol":"SCurveIn","label":"S-Curve In"},{"value":12,"symbol":"SCurveOut","label":"S-Curve Out"}],"fileFilters":null,"line":28}],
		"sourceUrl": new URL("./adjustable-fade.ny", import.meta.url).href,
	},
	{
		"id": "nyquist:beat",
		"actionId": "nyquist:beat",
		"fileName": "beat.ny",
		"sourceCommit": "5ef610ed23260d6d648175735bb16b32536eb30b",
		"sha256": "d31bace148e6c536f95deb81dae118f5d1be884c40155f0c1435c32e5050faaa",
		"category": "analyze",
		"name": "Beat Finder",
		"type": "analyze",
		"role": "analyze",
		"declaredTypes": ["analyze"],
		"isTool": false,
		"spectral": false,
		"author": "Audacity",
		"release": "2.3.2-2",
		"copyright": "GNU General Public License v2.0",
		"mergeClips": null,
		"restoreSplits": null,
		"debugButton": false,
		"debugEnabled": false,
		"debugFlags": [],
		"preview": [],
		"controls": [{"variable":"THRESVAL","type":"int","kind":"number","label":"Threshold Percentage","unit":"","defaultValue":65,"min":5,"max":100,"options":[],"fileFilters":null,"line":17}],
		"sourceUrl": new URL("./beat.ny", import.meta.url).href,
	},
	{
		"id": "nyquist:clipfix",
		"actionId": "nyquist:clipfix",
		"fileName": "clipfix.ny",
		"sourceCommit": "5ef610ed23260d6d648175735bb16b32536eb30b",
		"sha256": "ab12ecd52719e636aa326315b019004367db1545f5a473e20f84c7f3850838e2",
		"category": "legacy",
		"name": "Clip Fix",
		"type": "process",
		"role": "process",
		"declaredTypes": ["process"],
		"isTool": false,
		"spectral": false,
		"author": "Benjamin Schwartz and Steve Daulton",
		"release": "2.3.0-2",
		"copyright": "GNU General Public License v2.0",
		"mergeClips": null,
		"restoreSplits": null,
		"debugButton": false,
		"debugEnabled": false,
		"debugFlags": [],
		"preview": ["enabled"],
		"controls": [{"variable":"THRESHOLD","type":"float","kind":"number","label":"Threshold of Clipping (%)","unit":"","defaultValue":95,"min":0,"max":100,"options":[],"fileFilters":null,"line":26},{"variable":"GAIN","type":"float","kind":"number","label":"Reduce amplitude to allow for restored peaks (dB)","unit":"","defaultValue":-9,"min":-30,"max":0,"options":[],"fileFilters":null,"line":27}],
		"sourceUrl": new URL("./clipfix.ny", import.meta.url).href,
	},
	{
		"id": "nyquist:crossfadeclips",
		"actionId": "nyquist:crossfadeclips",
		"fileName": "crossfadeclips.ny",
		"sourceCommit": "5ef610ed23260d6d648175735bb16b32536eb30b",
		"sha256": "dd95f4f1d757ef01d398f877785df7cd45bce8bcab10c00bd6039bef70a7448c",
		"category": "legacy",
		"name": "Crossfade Clips",
		"type": "process",
		"role": "process",
		"declaredTypes": ["process"],
		"isTool": false,
		"spectral": false,
		"author": "Steve Daulton",
		"release": "3.0.4-1",
		"copyright": "GNU General Public License v2.0 or later",
		"mergeClips": 1,
		"restoreSplits": 0,
		"debugButton": null,
		"debugEnabled": true,
		"debugFlags": [],
		"preview": [],
		"controls": [],
		"sourceUrl": new URL("./crossfadeclips.ny", import.meta.url).href,
	},
	{
		"id": "nyquist:crossfadetracks",
		"actionId": "nyquist:crossfadetracks",
		"fileName": "crossfadetracks.ny",
		"sourceCommit": "5ef610ed23260d6d648175735bb16b32536eb30b",
		"sha256": "c56b5a2adea5ed60c04be07e04eca6959e64993932397c1f74eb44d666987e0a",
		"category": "legacy",
		"name": "Crossfade Tracks",
		"type": "process",
		"role": "process",
		"declaredTypes": ["process"],
		"isTool": false,
		"spectral": false,
		"author": "Steve Daulton",
		"release": "3.0.4-2",
		"copyright": "GNU General Public License v2.0 or later",
		"mergeClips": null,
		"restoreSplits": null,
		"debugButton": "disabled",
		"debugEnabled": false,
		"debugFlags": [],
		"preview": ["selection"],
		"controls": [{"variable":"TYPE","type":"choice","kind":"choice","label":"Fade TYPE","unit":"","defaultValue":0,"min":null,"max":null,"options":[{"value":0,"symbol":"ConstantGain","label":"Constant Gain"},{"value":1,"symbol":"ConstantPower1","label":"Constant Power 1"},{"value":2,"symbol":"ConstantPower2","label":"Constant Power 2"},{"value":3,"symbol":"CustomCurve","label":"Custom Curve"}],"fileFilters":null,"line":17},{"variable":"CURVE","type":"real","kind":"number","label":"Custom curve","unit":"","defaultValue":0,"min":0,"max":1,"options":[],"fileFilters":null,"line":22},{"variable":"DIRECTION","type":"choice","kind":"choice","label":"Fade direction","unit":"","defaultValue":0,"min":null,"max":null,"options":[{"value":0,"symbol":"Automatic","label":"Automatic"},{"value":1,"symbol":"OutIn","label":"Alternating Out / In"},{"value":2,"symbol":"InOut","label":"Alternating In / Out"}],"fileFilters":null,"line":23}],
		"sourceUrl": new URL("./crossfadetracks.ny", import.meta.url).href,
	},
	{
		"id": "nyquist:delay",
		"actionId": "nyquist:delay",
		"fileName": "delay.ny",
		"sourceCommit": "5ef610ed23260d6d648175735bb16b32536eb30b",
		"sha256": "78be9261157bb82feff10bf5ae3e9df56f99ffd8c12916ba0867acc99daba546",
		"category": "legacy",
		"name": "Delay",
		"type": "process",
		"role": "process",
		"declaredTypes": ["process"],
		"isTool": false,
		"spectral": false,
		"author": "Steve Daulton",
		"release": "2.4.2-2",
		"copyright": "GNU General Public License v2.0",
		"mergeClips": null,
		"restoreSplits": null,
		"debugButton": false,
		"debugEnabled": false,
		"debugFlags": [],
		"preview": ["linear"],
		"controls": [{"variable":"DELAY-TYPE","type":"choice","kind":"choice","label":"Delay type","unit":"","defaultValue":0,"min":null,"max":null,"options":[{"value":0,"symbol":"Regular","label":"Regular"},{"value":1,"symbol":"BouncingBall","label":"Bouncing Ball"},{"value":2,"symbol":"ReverseBouncingBall","label":"Reverse Bouncing Ball"}],"fileFilters":null,"line":20},{"variable":"DGAIN","type":"real","kind":"number","label":"Delay level per echo (dB)","unit":"","defaultValue":-6,"min":-30,"max":1,"options":[],"fileFilters":null,"line":23},{"variable":"DELAY","type":"real","kind":"number","label":"Delay time (seconds)","unit":"","defaultValue":0.3,"min":0,"max":5,"options":[],"fileFilters":null,"line":24},{"variable":"PITCH-TYPE","type":"choice","kind":"choice","label":"Pitch change effect","unit":"","defaultValue":0,"min":null,"max":null,"options":[{"value":0,"symbol":"PitchTempo","label":"Pitch/Tempo"},{"value":1,"symbol":"LQPitchShift","label":"Low-quality Pitch Shift"},{"value":2,"symbol":"HQPitchShift","label":"High-quality Pitch Shift"}],"fileFilters":null,"line":25},{"variable":"SHIFT","type":"real","kind":"number","label":"Pitch change per echo (semitones)","unit":"","defaultValue":0,"min":-2,"max":2,"options":[],"fileFilters":null,"line":28},{"variable":"NUMBER","type":"int","kind":"number","label":"Number of echoes","unit":"","defaultValue":5,"min":1,"max":30,"options":[],"fileFilters":null,"line":29},{"variable":"CONSTRAIN","type":"choice","kind":"choice","label":"Allow duration to change","unit":"","defaultValue":0,"min":null,"max":null,"options":[{"value":0,"symbol":"Yes","label":"Yes"},{"value":1,"symbol":"No","label":"No"}],"fileFilters":null,"line":30}],
		"sourceUrl": new URL("./delay.ny", import.meta.url).href,
	},
	{
		"id": "nyquist:highpass",
		"actionId": "nyquist:highpass",
		"fileName": "highpass.ny",
		"sourceCommit": "5ef610ed23260d6d648175735bb16b32536eb30b",
		"sha256": "41413e36642e45886166053c5d0d44746fa28126e316d5e8d2686dd65355aacb",
		"category": "legacy",
		"name": "High-Pass Filter",
		"type": "process",
		"role": "process",
		"declaredTypes": ["process"],
		"isTool": false,
		"spectral": false,
		"author": "Dominic Mazzoni",
		"release": "2.3.0-2",
		"copyright": "GNU General Public License v2.0",
		"mergeClips": null,
		"restoreSplits": null,
		"debugButton": "disabled",
		"debugEnabled": false,
		"debugFlags": [],
		"preview": ["linear"],
		"controls": [{"variable":"FREQUENCY","type":"float-text","kind":"number","label":"Frequency (Hz)","unit":"","defaultValue":1000,"min":0,"max":null,"options":[],"fileFilters":null,"line":18},{"variable":"ROLLOFF","type":"choice","kind":"choice","label":"Roll-off (dB per octave)","unit":"","defaultValue":0,"min":null,"max":null,"options":[{"value":0,"symbol":"dB6","label":"6 dB"},{"value":1,"symbol":"dB12","label":"12 dB"},{"value":2,"symbol":"dB24","label":"24 dB"},{"value":3,"symbol":"dB36","label":"36 dB"},{"value":4,"symbol":"dB48","label":"48 dB"}],"fileFilters":null,"line":19}],
		"sourceUrl": new URL("./highpass.ny", import.meta.url).href,
	},
	{
		"id": "nyquist:label-sounds",
		"actionId": "nyquist:label-sounds",
		"fileName": "label-sounds.ny",
		"sourceCommit": "5ef610ed23260d6d648175735bb16b32536eb30b",
		"sha256": "6156db861a5d7dffde52b700b021f256177933cb132277c157fbc141385fb7ec",
		"category": "analyze",
		"name": "Label Sounds",
		"type": "analyze",
		"role": "analyze",
		"declaredTypes": ["analyze"],
		"isTool": false,
		"spectral": false,
		"author": "Steve Daulton",
		"release": "3.0.4-2",
		"copyright": "GNU General Public License v2.0 or later",
		"mergeClips": null,
		"restoreSplits": null,
		"debugButton": false,
		"debugEnabled": false,
		"debugFlags": [],
		"preview": [],
		"controls": [{"variable":"THRESHOLD","type":"float","kind":"number","label":"Threshold level (dB)","unit":"","defaultValue":-30,"min":-100,"max":0,"options":[],"fileFilters":null,"line":18},{"variable":"MEASUREMENT","type":"choice","kind":"choice","label":"Threshold measurement","unit":"","defaultValue":0,"min":null,"max":null,"options":[{"value":0,"symbol":"peak","label":"Peak level"},{"value":1,"symbol":"avg","label":"Average level"},{"value":2,"symbol":"rms","label":"RMS level"}],"fileFilters":null,"line":19},{"variable":"SIL-DUR","type":"time","kind":"number","label":"Minimum silence duration","unit":"","defaultValue":1,"min":0.01,"max":3600,"options":[],"fileFilters":null,"line":22},{"variable":"SND-DUR","type":"time","kind":"number","label":"Minimum label interval","unit":"","defaultValue":1,"min":0.01,"max":7200,"options":[],"fileFilters":null,"line":23},{"variable":"TYPE","type":"choice","kind":"choice","label":"Label type","unit":"","defaultValue":2,"min":null,"max":null,"options":[{"value":0,"symbol":"before","label":"Point before sound"},{"value":1,"symbol":"after","label":"Point after sound"},{"value":2,"symbol":"around","label":"Region around sounds"},{"value":3,"symbol":"between","label":"Region between sounds"}],"fileFilters":null,"line":24},{"variable":"PRE-OFFSET","type":"time","kind":"number","label":"Maximum leading silence","unit":"","defaultValue":0,"min":0,"max":null,"options":[],"fileFilters":null,"line":28},{"variable":"POST-OFFSET","type":"time","kind":"number","label":"Maximum trailing silence","unit":"","defaultValue":0,"min":0,"max":null,"options":[],"fileFilters":null,"line":29},{"variable":"TEXT","type":"string","kind":"string","label":"Label text","unit":"","defaultValue":"Sound ##1","options":[],"fileFilters":null,"line":31}],
		"sourceUrl": new URL("./label-sounds.ny", import.meta.url).href,
	},
	{
		"id": "nyquist:legacy-limiter",
		"actionId": "nyquist:legacy-limiter",
		"fileName": "legacy-limiter.ny",
		"sourceCommit": "5ef610ed23260d6d648175735bb16b32536eb30b",
		"sha256": "569db79cbe832c3cf9d2158e37e04aa9dd05c777f8ffce93a2c5ffeccf801838",
		"category": "legacy",
		"name": "Legacy Limiter",
		"type": "process",
		"role": "process",
		"declaredTypes": ["process"],
		"isTool": false,
		"spectral": false,
		"author": "Steve Daulton",
		"release": "3.0.4-2",
		"copyright": "GNU General Public License v2.0 or later",
		"mergeClips": null,
		"restoreSplits": null,
		"debugButton": false,
		"debugEnabled": false,
		"debugFlags": [],
		"preview": ["enabled"],
		"controls": [{"variable":"TYPE","type":"choice","kind":"choice","label":"Type","unit":"","defaultValue":0,"min":null,"max":null,"options":[{"value":0,"symbol":"SoftLimit","label":"Soft Limit"},{"value":1,"symbol":"HardLimit","label":"Hard Limit"},{"value":2,"symbol":"SoftClip","label":"Soft Clip"},{"value":3,"symbol":"HardClip","label":"Hard Clip"}],"fileFilters":null,"line":20},{"variable":"GAIN-L","type":"real","kind":"number","label":"Input Gain (dB)\nmono/Left","unit":"","defaultValue":0,"min":0,"max":10,"options":[],"fileFilters":null,"line":28},{"variable":"GAIN-R","type":"real","kind":"number","label":"Input Gain (dB)\nRight channel","unit":"","defaultValue":0,"min":0,"max":10,"options":[],"fileFilters":null,"line":31},{"variable":"THRESH","type":"real","kind":"number","label":"Limit to (dB)","unit":"","defaultValue":-3,"min":-10,"max":0,"options":[],"fileFilters":null,"line":34},{"variable":"HOLD","type":"real","kind":"number","label":"Hold (ms)","unit":"","defaultValue":10,"min":1,"max":50,"options":[],"fileFilters":null,"line":35},{"variable":"MAKEUP","type":"choice","kind":"choice","label":"Apply Make-up Gain","unit":"","defaultValue":0,"min":null,"max":null,"options":[{"value":0,"symbol":"No","label":"No"},{"value":1,"symbol":"Yes","label":"Yes"}],"fileFilters":null,"line":36}],
		"sourceUrl": new URL("./legacy-limiter.ny", import.meta.url).href,
	},
	{
		"id": "nyquist:lowpass",
		"actionId": "nyquist:lowpass",
		"fileName": "lowpass.ny",
		"sourceCommit": "5ef610ed23260d6d648175735bb16b32536eb30b",
		"sha256": "a9cae350be81009b0c12e36d1a9e06e174d0fde2a33485a9d4e26b989681f7de",
		"category": "legacy",
		"name": "Low-Pass Filter",
		"type": "process",
		"role": "process",
		"declaredTypes": ["process"],
		"isTool": false,
		"spectral": false,
		"author": "Dominic Mazzoni",
		"release": "2.3.0-2",
		"copyright": "GNU General Public License v2.0",
		"mergeClips": null,
		"restoreSplits": null,
		"debugButton": "disabled",
		"debugEnabled": false,
		"debugFlags": [],
		"preview": ["linear"],
		"controls": [{"variable":"FREQUENCY","type":"float-text","kind":"number","label":"Frequency (Hz)","unit":"","defaultValue":1000,"min":0,"max":null,"options":[],"fileFilters":null,"line":18},{"variable":"ROLLOFF","type":"choice","kind":"choice","label":"Roll-off (dB per octave)","unit":"","defaultValue":0,"min":null,"max":null,"options":[{"value":0,"symbol":"dB6","label":"6 dB"},{"value":1,"symbol":"dB12","label":"12 dB"},{"value":2,"symbol":"dB24","label":"24 dB"},{"value":3,"symbol":"dB36","label":"36 dB"},{"value":4,"symbol":"dB48","label":"48 dB"}],"fileFilters":null,"line":19}],
		"sourceUrl": new URL("./lowpass.ny", import.meta.url).href,
	},
	{
		"id": "nyquist:rms",
		"actionId": "nyquist:rms",
		"fileName": "rms.ny",
		"sourceCommit": "5ef610ed23260d6d648175735bb16b32536eb30b",
		"sha256": "1f589c2f02e59574a4b7df27ed74968508b695bc019a3a936ed5b88339f481c7",
		"category": "analyze",
		"name": "Measure RMS",
		"type": "analyze",
		"role": "analyze",
		"declaredTypes": ["analyze"],
		"isTool": false,
		"spectral": false,
		"author": "Steve Daulton",
		"release": "2.3.1-1",
		"copyright": "GNU General Public License v2.0 or later",
		"mergeClips": null,
		"restoreSplits": null,
		"debugButton": false,
		"debugEnabled": false,
		"debugFlags": [],
		"preview": [],
		"controls": [],
		"sourceUrl": new URL("./rms.ny", import.meta.url).href,
	},
	{
		"id": "nyquist:noisegate",
		"actionId": "nyquist:noisegate",
		"fileName": "noisegate.ny",
		"sourceCommit": "5ef610ed23260d6d648175735bb16b32536eb30b",
		"sha256": "1bc9b5a5ace717b0c24c4ec8a7b20ebf3abcc6c727fbf1df7352552ce39344b8",
		"category": "legacy",
		"name": "Noise Gate",
		"type": "process",
		"role": "process",
		"declaredTypes": ["process"],
		"isTool": false,
		"spectral": false,
		"author": "Steve Daulton",
		"release": "3.0.4-2",
		"copyright": "GNU General Public License v2.0 or later",
		"mergeClips": null,
		"restoreSplits": null,
		"debugButton": false,
		"debugEnabled": false,
		"debugFlags": [],
		"preview": ["enabled"],
		"controls": [{"variable":"MODE","type":"choice","kind":"choice","label":"Select Function","unit":"","defaultValue":0,"min":null,"max":null,"options":[{"value":0,"symbol":"Gate","label":"Gate"},{"value":1,"symbol":"Analyze","label":"Analyze Noise Level"}],"fileFilters":null,"line":18},{"variable":"STEREO-LINK","type":"choice","kind":"choice","label":"Stereo Linking","unit":"","defaultValue":0,"min":null,"max":null,"options":[{"value":0,"symbol":"LinkStereo","label":"Link Stereo Tracks"},{"value":1,"symbol":"DoNotLink","label":"Don't Link Stereo"}],"fileFilters":null,"line":20},{"variable":"THRESHOLD","type":"float","kind":"number","label":"Gate threshold (dB)","unit":"","defaultValue":-40,"min":-96,"max":-6,"options":[],"fileFilters":null,"line":23},{"variable":"GATE-FREQ","type":"float","kind":"number","label":"Gate frequencies above (kHz)","unit":"","defaultValue":0,"min":0,"max":10,"options":[],"fileFilters":null,"line":24},{"variable":"LEVEL-REDUCTION","type":"float","kind":"number","label":"Level reduction (dB)","unit":"","defaultValue":-24,"min":-100,"max":0,"options":[],"fileFilters":null,"line":25},{"variable":"ATTACK","type":"float","kind":"number","label":"Attack (ms)","unit":"","defaultValue":10,"min":1,"max":1000,"options":[],"fileFilters":null,"line":26},{"variable":"HOLD","type":"float","kind":"number","label":"Hold (ms)","unit":"","defaultValue":50,"min":0,"max":2000,"options":[],"fileFilters":null,"line":27},{"variable":"DECAY","type":"float","kind":"number","label":"Decay (ms)","unit":"","defaultValue":100,"min":10,"max":4000,"options":[],"fileFilters":null,"line":28}],
		"sourceUrl": new URL("./noisegate.ny", import.meta.url).href,
	},
	{
		"id": "nyquist:notch",
		"actionId": "nyquist:notch",
		"fileName": "notch.ny",
		"sourceCommit": "5ef610ed23260d6d648175735bb16b32536eb30b",
		"sha256": "98bb5ada98255d4887e6d586fe978718dde1b4df5ce1975cc5018ec8e783658a",
		"category": "legacy",
		"name": "Notch Filter",
		"type": "process",
		"role": "process",
		"declaredTypes": ["process"],
		"isTool": false,
		"spectral": false,
		"author": "Steve Daulton and Bill Wharrie",
		"release": "2.3.0-2",
		"copyright": "GNU General Public License v2.0 or later",
		"mergeClips": null,
		"restoreSplits": null,
		"debugButton": false,
		"debugEnabled": false,
		"debugFlags": [],
		"preview": ["linear"],
		"controls": [{"variable":"FREQUENCY","type":"float-text","kind":"number","label":"Frequency (Hz)","unit":"","defaultValue":60,"min":0,"max":null,"options":[],"fileFilters":null,"line":19},{"variable":"Q","type":"float-text","kind":"number","label":"Q (higher value reduces width)","unit":"","defaultValue":1,"min":0.1,"max":1000,"options":[],"fileFilters":null,"line":20}],
		"sourceUrl": new URL("./notch.ny", import.meta.url).href,
	},
	{
		"id": "nyquist:pluck",
		"actionId": "nyquist:pluck",
		"fileName": "pluck.ny",
		"sourceCommit": "5ef610ed23260d6d648175735bb16b32536eb30b",
		"sha256": "4510413ed4081f05c8ba1e8a42de387bea96795f7ddcd97d9224b5ee93249581",
		"category": "generate",
		"name": "Pluck",
		"type": "generate",
		"role": "generate",
		"declaredTypes": ["generate"],
		"isTool": false,
		"spectral": false,
		"author": "David R.Sky",
		"release": "2.4.2",
		"copyright": "GNU General Public License v2.0",
		"mergeClips": null,
		"restoreSplits": null,
		"debugButton": false,
		"debugEnabled": false,
		"debugFlags": [],
		"preview": ["linear"],
		"controls": [{"variable":"PITCH","type":"int","kind":"number","label":"Pluck MIDI pitch","unit":"","defaultValue":60,"min":1,"max":120,"options":[],"fileFilters":null,"line":21},{"variable":"FADE","type":"choice","kind":"choice","label":"Fade-out type","unit":"","defaultValue":0,"min":null,"max":null,"options":[{"value":0,"symbol":"Abrupt","label":"Abrupt"},{"value":1,"symbol":"Gradual","label":"Gradual"}],"fileFilters":null,"line":22},{"variable":"DUR","type":"time","kind":"number","label":"Duration (60s max)","unit":"","defaultValue":1,"min":0,"max":60,"options":[],"fileFilters":null,"line":23}],
		"sourceUrl": new URL("./pluck.ny", import.meta.url).href,
	},
	{
		"id": "nyquist:equalabel",
		"actionId": "nyquist:equalabel",
		"fileName": "equalabel.ny",
		"sourceCommit": "5ef610ed23260d6d648175735bb16b32536eb30b",
		"sha256": "4051913fd46b30d2a5aff758428935dbcfd2d91815642ae02dc966f29fb195a3",
		"category": "analyze",
		"name": "Regular Interval Labels",
		"type": "tool",
		"role": "analyze",
		"declaredTypes": ["tool","analyze"],
		"isTool": true,
		"spectral": false,
		"author": "Steve Daulton",
		"release": "2.3.1-2",
		"copyright": "GNU General Public License v2.0 or later",
		"mergeClips": null,
		"restoreSplits": null,
		"debugButton": false,
		"debugEnabled": false,
		"debugFlags": ["trace"],
		"preview": [],
		"controls": [{"variable":"MODE","type":"choice","kind":"choice","label":"Create labels based on","unit":"","defaultValue":0,"min":null,"max":null,"options":[{"value":0,"symbol":"Both","label":"Number and Interval"},{"value":1,"symbol":"Number","label":"Number of Labels"},{"value":2,"symbol":"Interval","label":"Label Interval"}],"fileFilters":null,"line":27},{"variable":"TOTALNUM","type":"int-text","kind":"number","label":"Number of labels","unit":"","defaultValue":10,"min":1,"max":1000,"options":[],"fileFilters":null,"line":30},{"variable":"INTERVAL","type":"float-text","kind":"number","label":"Label interval (seconds)","unit":"","defaultValue":10,"min":0.001,"max":3600,"options":[],"fileFilters":null,"line":31},{"variable":"REGION","type":"float-text","kind":"number","label":"Length of label region (seconds)","unit":"","defaultValue":0,"min":0,"max":3600,"options":[],"fileFilters":null,"line":32},{"variable":"ADJUST","type":"choice","kind":"choice","label":"Adjust label interval to fit length","unit":"","defaultValue":0,"min":null,"max":null,"options":[{"value":0,"symbol":"No","label":"No"},{"value":1,"symbol":"Yes","label":"Yes"}],"fileFilters":null,"line":33},{"variable":"LABELTEXT","type":"string","kind":"string","label":"Label text","unit":"","defaultValue":"Label","options":[],"fileFilters":null,"line":35},{"variable":"ZEROS","type":"choice","kind":"choice","label":"Minimum number of digits in label","unit":"","defaultValue":2,"min":null,"max":null,"options":[{"value":0,"symbol":"TextOnly","label":"None - Text Only"},{"value":1,"symbol":"OneBefore","label":"1 (Before Label)"},{"value":2,"symbol":"TwoBefore","label":"2 (Before Label)"},{"value":3,"symbol":"ThreeBefore","label":"3 (Before Label)"},{"value":4,"symbol":"OneAfter","label":"1 (After Label)"},{"value":5,"symbol":"TwoAfter","label":"2 (After Label)"},{"value":6,"symbol":"ThreeAfter","label":"3 (After Label)"}],"fileFilters":null,"line":36},{"variable":"FIRSTNUM","type":"int-text","kind":"number","label":"Begin numbering from","unit":"","defaultValue":1,"min":0,"max":null,"options":[],"fileFilters":null,"line":43},{"variable":"VERBOSE","type":"choice","kind":"choice","label":"Message on completion","unit":"","defaultValue":0,"min":null,"max":null,"options":[{"value":0,"symbol":"Details","label":"Details"},{"value":1,"symbol":"Warnings","label":"Warnings only"},{"value":2,"symbol":"None","label":"None"}],"fileFilters":null,"line":44}],
		"sourceUrl": new URL("./equalabel.ny", import.meta.url).href,
	},
	{
		"id": "nyquist:rhythmtrack",
		"actionId": "nyquist:rhythmtrack",
		"fileName": "rhythmtrack.ny",
		"sourceCommit": "5ef610ed23260d6d648175735bb16b32536eb30b",
		"sha256": "d612e8fc22b7cec114a1caee2cb996d94b63899fd43e557112b36b7672cd38c2",
		"category": "generate",
		"name": "Rhythm Track",
		"type": "generate",
		"role": "generate",
		"declaredTypes": ["generate"],
		"isTool": false,
		"spectral": false,
		"author": "Dominic Mazzoni, David R. Sky and Steve Daulton",
		"release": "3.0.0-2",
		"copyright": "GNU General Public License v2.0",
		"mergeClips": null,
		"restoreSplits": null,
		"debugButton": false,
		"debugEnabled": false,
		"debugFlags": [],
		"preview": ["linear"],
		"controls": [{"variable":"TEMPO","type":"real","kind":"number","label":"Tempo (bpm)","unit":"30 - 300 beats/minute","defaultValue":120,"min":30,"max":300,"options":[],"fileFilters":null,"line":23},{"variable":"TIMESIG","type":"int","kind":"number","label":"Beats per bar","unit":"1 - 20 beats/measure","defaultValue":4,"min":1,"max":20,"options":[],"fileFilters":null,"line":24},{"variable":"SWING","type":"float","kind":"number","label":"Swing amount","unit":"+/- 1","defaultValue":0,"min":-1,"max":1,"options":[],"fileFilters":null,"line":25},{"variable":null,"type":"text","kind":"text","label":"Set 'Number of bars' to zero to enable the 'Rhythm track duration'.","unit":"","defaultValue":null,"min":null,"max":null,"options":[],"line":26},{"variable":"BARS","type":"int","kind":"number","label":"Number of bars","unit":"1 - 1000 bars","defaultValue":16,"min":0,"max":1000,"options":[],"fileFilters":null,"line":27},{"variable":"CLICK-TRACK-DUR","type":"time","kind":"number","label":"Rhythm track duration","unit":"Used if 'Number of bars' = 0","defaultValue":0,"min":0,"max":null,"options":[],"fileFilters":null,"line":28},{"variable":"OFFSET","type":"time","kind":"number","label":"Start time offset","unit":"Silence before first beat","defaultValue":0,"min":0,"max":null,"options":[],"fileFilters":null,"line":29},{"variable":"CLICK-TYPE","type":"choice","kind":"choice","label":"Beat sound","unit":"","defaultValue":0,"min":null,"max":null,"options":[{"value":0,"symbol":"Metronome","label":"Metronome Tick"},{"value":1,"symbol":"Ping (short)","label":"Ping (short)"},{"value":2,"symbol":"Ping (long)","label":"Ping (long)"},{"value":3,"symbol":"Cowbell","label":"Cowbell"},{"value":4,"symbol":"ResonantNoise","label":"Resonant Noise"},{"value":5,"symbol":"NoiseClick","label":"Noise Click"},{"value":6,"symbol":"Drip (short)","label":"Drip (short)"},{"value":7,"symbol":"Drip (long)","label":"Drip (long)"}],"fileFilters":null,"line":30},{"variable":"HIGH","type":"int","kind":"number","label":"MIDI pitch of strong beat","unit":"18 - 116","defaultValue":84,"min":18,"max":116,"options":[],"fileFilters":null,"line":39},{"variable":"LOW","type":"int","kind":"number","label":"MIDI pitch of weak beat","unit":"18 - 116","defaultValue":80,"min":18,"max":116,"options":[],"fileFilters":null,"line":40}],
		"sourceUrl": new URL("./rhythmtrack.ny", import.meta.url).href,
	},
	{
		"id": "nyquist:rissetdrum",
		"actionId": "nyquist:rissetdrum",
		"fileName": "rissetdrum.ny",
		"sourceCommit": "5ef610ed23260d6d648175735bb16b32536eb30b",
		"sha256": "e5056c353988310a0ba4967702fbd125fc863129e41f5aa5d074b3504459ac30",
		"category": "generate",
		"name": "Risset Drum",
		"type": "generate",
		"role": "generate",
		"declaredTypes": ["generate"],
		"isTool": false,
		"spectral": false,
		"author": "Steven Jones",
		"release": "2.3.0-2",
		"copyright": "GNU General Public License v2.0 or later",
		"mergeClips": null,
		"restoreSplits": null,
		"debugButton": false,
		"debugEnabled": false,
		"debugFlags": [],
		"preview": ["linear"],
		"controls": [{"variable":"FREQ","type":"real","kind":"number","label":"Frequency (Hz)","unit":"","defaultValue":100,"min":50,"max":2000,"options":[],"fileFilters":null,"line":22},{"variable":"DECAY","type":"real","kind":"number","label":"Decay (seconds)","unit":"","defaultValue":2,"min":0.1,"max":60,"options":[],"fileFilters":null,"line":23},{"variable":"CF","type":"real","kind":"number","label":"Center frequency of noise (Hz)","unit":"","defaultValue":500,"min":100,"max":5000,"options":[],"fileFilters":null,"line":24},{"variable":"BW","type":"real","kind":"number","label":"Width of noise band (Hz)","unit":"","defaultValue":400,"min":10,"max":1000,"options":[],"fileFilters":null,"line":25},{"variable":"NOISE","type":"real","kind":"number","label":"Amount of noise in mix (percent)","unit":"","defaultValue":25,"min":0,"max":100,"options":[],"fileFilters":null,"line":26},{"variable":"GAIN","type":"real","kind":"number","label":"Amplitude (0 - 1)","unit":"","defaultValue":0.8,"min":0,"max":1,"options":[],"fileFilters":null,"line":27}],
		"sourceUrl": new URL("./rissetdrum.ny", import.meta.url).href,
	},
	{
		"id": "nyquist:shelffilter",
		"actionId": "nyquist:shelffilter",
		"fileName": "ShelfFilter.ny",
		"sourceCommit": "5ef610ed23260d6d648175735bb16b32536eb30b",
		"sha256": "b73d31f7d3328359bc930a635bae1f143e66d39fc4a5d2abd812cb129a2323ec",
		"category": "legacy",
		"name": "Shelf Filter",
		"type": "process",
		"role": "process",
		"declaredTypes": ["process"],
		"isTool": false,
		"spectral": false,
		"author": "Steve Daulton",
		"release": "2.4.0-1",
		"copyright": "GNU General Public License v2.0",
		"mergeClips": null,
		"restoreSplits": null,
		"debugButton": "disabled",
		"debugEnabled": false,
		"debugFlags": [],
		"preview": ["linear"],
		"controls": [{"variable":"TYPE","type":"choice","kind":"choice","label":"Filter type","unit":"","defaultValue":0,"min":null,"max":null,"options":[{"value":0,"symbol":"Low","label":"Low-shelf"},{"value":1,"symbol":"High","label":"High-shelf"}],"fileFilters":null,"line":18},{"variable":"HZ","type":"int","kind":"number","label":"Frequency (Hz)","unit":"","defaultValue":1000,"min":10,"max":10000,"options":[],"fileFilters":null,"line":20},{"variable":"GAIN","type":"int","kind":"number","label":"Amount (dB)","unit":"","defaultValue":-6,"min":-72,"max":72,"options":[],"fileFilters":null,"line":21}],
		"sourceUrl": new URL("./ShelfFilter.ny", import.meta.url).href,
	},
	{
		"id": "nyquist:spectral-delete",
		"actionId": "nyquist:spectral-delete",
		"fileName": "spectral-delete.ny",
		"sourceCommit": "5ef610ed23260d6d648175735bb16b32536eb30b",
		"sha256": "3062c228b1badceec081580c6a3f10219556310ed62453e95e148d4766e3613b",
		"category": "legacy",
		"name": "Spectral Delete",
		"type": "process",
		"role": "process",
		"declaredTypes": ["process","spectral"],
		"isTool": false,
		"spectral": true,
		"author": "Steve Daulton",
		"release": "3.0.4-1",
		"copyright": "GNU General Public License v2.0 or later",
		"mergeClips": null,
		"restoreSplits": null,
		"debugButton": null,
		"debugEnabled": true,
		"debugFlags": [],
		"preview": [],
		"controls": [],
		"sourceUrl": new URL("./spectral-delete.ny", import.meta.url).href,
	},
	{
		"id": "nyquist:spectraleditmulti",
		"actionId": "nyquist:spectraleditmulti",
		"fileName": "SpectralEditMulti.ny",
		"sourceCommit": "5ef610ed23260d6d648175735bb16b32536eb30b",
		"sha256": "520d210daddbbebbdc89ab55287fc928a761b109dfeef22b55e3d12cd9fe2cb5",
		"category": "legacy",
		"name": "Spectral Edit Multi Tool",
		"type": "process",
		"role": "process",
		"declaredTypes": ["process","spectral"],
		"isTool": false,
		"spectral": true,
		"author": "Paul Licameli",
		"release": "2.3.0-1",
		"copyright": "GNU General Public License v2.0",
		"mergeClips": null,
		"restoreSplits": null,
		"debugButton": null,
		"debugEnabled": true,
		"debugFlags": [],
		"preview": [],
		"controls": [],
		"sourceUrl": new URL("./SpectralEditMulti.ny", import.meta.url).href,
	},
	{
		"id": "nyquist:spectraleditparametriceq",
		"actionId": "nyquist:spectraleditparametriceq",
		"fileName": "SpectralEditParametricEQ.ny",
		"sourceCommit": "5ef610ed23260d6d648175735bb16b32536eb30b",
		"sha256": "63bf6ab2e95a2fbf0c35f51325b5dc709c8df93ba9852a49429de8bf7b3055b0",
		"category": "legacy",
		"name": "Spectral Edit Parametric EQ",
		"type": "process",
		"role": "process",
		"declaredTypes": ["process","spectral"],
		"isTool": false,
		"spectral": true,
		"author": "Paul Licameli",
		"release": "2.3.0-2",
		"copyright": "GNU General Public License v2.0",
		"mergeClips": null,
		"restoreSplits": null,
		"debugButton": false,
		"debugEnabled": false,
		"debugFlags": [],
		"preview": ["linear"],
		"controls": [{"variable":"CONTROL-GAIN","type":"real","kind":"number","label":"Gain (dB)","unit":"","defaultValue":0,"min":-24,"max":24,"options":[],"fileFilters":null,"line":21}],
		"sourceUrl": new URL("./SpectralEditParametricEQ.ny", import.meta.url).href,
	},
	{
		"id": "nyquist:spectraleditshelves",
		"actionId": "nyquist:spectraleditshelves",
		"fileName": "SpectralEditShelves.ny",
		"sourceCommit": "5ef610ed23260d6d648175735bb16b32536eb30b",
		"sha256": "4c9c3f5a90acc387532984c4a45976d04354b3c4bcf8d2abfb577f099f2e9818",
		"category": "legacy",
		"name": "Spectral Edit Shelves",
		"type": "process",
		"role": "process",
		"declaredTypes": ["process","spectral"],
		"isTool": false,
		"spectral": true,
		"author": "Paul Licameli",
		"release": "2.3.0-2",
		"copyright": "GNU General Public License v2.0 or later",
		"mergeClips": null,
		"restoreSplits": null,
		"debugButton": false,
		"debugEnabled": false,
		"debugFlags": [],
		"preview": ["linear"],
		"controls": [{"variable":"CONTROL-GAIN","type":"real","kind":"number","label":"Gain (dB)","unit":"","defaultValue":0,"min":-24,"max":24,"options":[],"fileFilters":null,"line":21}],
		"sourceUrl": new URL("./SpectralEditShelves.ny", import.meta.url).href,
	},
	{
		"id": "nyquist:studiofadeout",
		"actionId": "nyquist:studiofadeout",
		"fileName": "StudioFadeOut.ny",
		"sourceCommit": "5ef610ed23260d6d648175735bb16b32536eb30b",
		"sha256": "a369b7e560c42113f2753c510108ed219f13ec93c3ab2e48f94a77550a1c3446",
		"category": "legacy",
		"name": "Studio Fade Out",
		"type": "process",
		"role": "process",
		"declaredTypes": ["process"],
		"isTool": false,
		"spectral": false,
		"author": "Steve Daulton",
		"release": "3.7.4",
		"copyright": "GNU General Public License v2.0 or later",
		"mergeClips": null,
		"restoreSplits": null,
		"debugButton": null,
		"debugEnabled": true,
		"debugFlags": [],
		"preview": [],
		"controls": [],
		"sourceUrl": new URL("./StudioFadeOut.ny", import.meta.url).href,
	},
	{
		"id": "nyquist:tremolo",
		"actionId": "nyquist:tremolo",
		"fileName": "tremolo.ny",
		"sourceCommit": "5ef610ed23260d6d648175735bb16b32536eb30b",
		"sha256": "56efcf1cf9f86a6ca5d10ebe50f514cac16b4876f39e725745b732660ca77735",
		"category": "legacy",
		"name": "Tremolo",
		"type": "process",
		"role": "process",
		"declaredTypes": ["process"],
		"isTool": false,
		"spectral": false,
		"author": "Steve Daulton",
		"release": "2.4.0",
		"copyright": "GNU General Public License v2.0 or later",
		"mergeClips": null,
		"restoreSplits": null,
		"debugButton": "disabled",
		"debugEnabled": false,
		"debugFlags": [],
		"preview": ["linear"],
		"controls": [{"variable":"WAVE","type":"choice","kind":"choice","label":"Waveform type","unit":"","defaultValue":0,"min":null,"max":null,"options":[{"value":0,"symbol":"Sine","label":"Sine"},{"value":1,"symbol":"Triangle","label":"Triangle"},{"value":2,"symbol":"Sawtooth","label":"Sawtooth"},{"value":3,"symbol":"InverseSawtooth","label":"Inverse Sawtooth"},{"value":4,"symbol":"Square","label":"Square"}],"fileFilters":null,"line":21},{"variable":"PHASE","type":"int","kind":"number","label":"Starting phase (degrees)","unit":"","defaultValue":0,"min":-180,"max":180,"options":[],"fileFilters":null,"line":27},{"variable":"WET","type":"int","kind":"number","label":"Wet level (percent)","unit":"","defaultValue":40,"min":1,"max":100,"options":[],"fileFilters":null,"line":28},{"variable":"LFO","type":"float-text","kind":"number","label":"Frequency (Hz)","unit":"","defaultValue":4,"min":0.001,"max":1000,"options":[],"fileFilters":null,"line":29}],
		"sourceUrl": new URL("./tremolo.ny", import.meta.url).href,
	},
	{
		"id": "nyquist:vocoder",
		"actionId": "nyquist:vocoder",
		"fileName": "vocoder.ny",
		"sourceCommit": "5ef610ed23260d6d648175735bb16b32536eb30b",
		"sha256": "f8ba3fad7df6dd814c0007aef202f4a886dee816828e3cb2758431876e228bdf",
		"category": "legacy",
		"name": "Vocoder",
		"type": "process",
		"role": "process",
		"declaredTypes": ["process"],
		"isTool": false,
		"spectral": false,
		"author": "Edgar-RFT and Steve Daulton",
		"release": "3.1.2-1",
		"copyright": "GNU General Public License v2.0",
		"mergeClips": null,
		"restoreSplits": null,
		"debugButton": false,
		"debugEnabled": false,
		"debugFlags": [],
		"preview": ["enabled"],
		"controls": [{"variable":"DST","type":"float","kind":"number","label":"Distance: (1 to 120, default = 20)","unit":"","defaultValue":20,"min":1,"max":120,"options":[],"fileFilters":null,"line":23},{"variable":"MST","type":"choice","kind":"choice","label":"Output choice","unit":"","defaultValue":0,"min":null,"max":null,"options":[{"value":0,"symbol":"BothChannels","label":"Both Channels"},{"value":1,"symbol":"RightOnly","label":"Right Only"}],"fileFilters":null,"line":24},{"variable":"BANDS","type":"int","kind":"number","label":"Number of vocoder bands","unit":"","defaultValue":40,"min":10,"max":240,"options":[],"fileFilters":null,"line":26},{"variable":"TRACK-VL","type":"float","kind":"number","label":"Amplitude of carrier wave (percent)","unit":"","defaultValue":100,"min":0,"max":100,"options":[],"fileFilters":null,"line":27},{"variable":"NOISE-VL","type":"float","kind":"number","label":"Amplitude of white noise (percent)","unit":"","defaultValue":0,"min":0,"max":100,"options":[],"fileFilters":null,"line":28},{"variable":"RADAR-VL","type":"float","kind":"number","label":"Amplitude of Radar Needles (percent)","unit":"","defaultValue":0,"min":0,"max":100,"options":[],"fileFilters":null,"line":29},{"variable":"RADAR-F","type":"float","kind":"number","label":"Frequency of Radar Needles (Hz)","unit":"","defaultValue":30,"min":1,"max":100,"options":[],"fileFilters":null,"line":30}],
		"sourceUrl": new URL("./vocoder.ny", import.meta.url).href,
	},
];
