/* SPDX-License-Identifier: AGPL-3.0-only */

import { assertEditorPreferenceActionOwner, type EditorPreferenceActionOwner } from '../preferences/preference-action-group.ts';
import type { EditorActionFunctions } from './editor-action-functions.ts';
import type { EditorActionResources } from './editor-action-resources.ts';
import {
	assertEditorLabelActionGroup,
	type EditorLabelActionGroup,
} from './label-action-group.ts';
import {
	assertEditorSelectionActionGroup,
	type EditorSelectionActionGroup,
} from './selection-action-group.ts';
import {
	assertEditorProjectBinActionGroup,
	type EditorProjectBinActionGroup,
} from './project-bin-action-group.ts';
export type { EditorActionResources } from './editor-action-resources.ts';

type MissingEditorActionFunctionNames<Names extends readonly PropertyKey[]> =
	Exclude<keyof EditorActionFunctions, Names[number]>;

function defineEditorActionFunctionNames<const Names extends readonly (keyof EditorActionFunctions)[]>(
	names: Names & (MissingEditorActionFunctionNames<Names> extends never
		? unknown
		: { readonly __missingEditorActionFunctions: MissingEditorActionFunctionNames<Names> }),
): Names {
	return names;
}

export const EDITOR_ACTION_FUNCTION_NAMES = defineEditorActionFunctionNames([
	'setSourceSelection', 'loadSourceAudio', 'loadSourceAudioWindow',
	'addEffect',
	'addLabelTrack',
	'addTrack',
	'addVideoClipEffect',
	'addVideoTrackPair',
	'adjustAllTrackHeights',
	'adjustTrackHeight',
	'applyAudacityEffectFromController',
	'applyEffectPreset',
	'applySamplePencil',
	'applySpectralSelection',
	'assertProjectHandoffAllowed',
	'beginMacroTransaction',
	'beginParametricEqGesture',
	'beginRackEffectGesture',
	'beginVideoEffectGesture',
	'bypassVideoClipEffect',
	'cancelAudacityEffectPreview',
	'cancelEffectMacro',
	'cancelNyquistEvaluation',
	'cancelParametricEqGesture',
	'cancelPlaybackCachePreparation',
	'cancelRackEffectGesture',
	'cancelSampleEdit',
	'cancelTimedRecording',
	'cancelVideoEffectGesture',
	'captureRackNoiseProfileFromController',
	'captureSelectedNoiseProfile',
	'claimProjectLock',
	'cleanupDerivativeCache',
	'cleanupDisposableStorage',
	'clearLocalData',
	'clearLoopRegion',
	'clearRecentProjects',
	'closeProjectTab',
	'commit',
	'commitParametricEqGesture',
	'commitRackEffectGesture',
	'commitVideoEffectGesture',
	'configureDisplayInput',
	'continueLoudnessMeasurement',
	'copyEffectStack',
	'copyRackEffect',
	'createStableId',
	'currentAudacityEffectParams',
	'deleteEffectPreset',
	'deleteProject',
	'discardTakeCycleRecording',
	'disjoinSelectedClip',
	'dismissAup4CompatibilitySummary',
	'duplicateProject',
	'duplicateTrack',
	'exportEffectPreset',
	'exportVideo',
	'findClip',
	'findTrack',
	'flushProject',
	'generateSelectionSilence',
	'generateSignal',
	'getClipVisualData',
	'getProject',
	'getVideoSourceVisualData',
	'getVisibleClips',
	'handleClipAction',
	'handleEdit',
	'handleError',
	'handleExportAction',
	'handlePlayAtSpeed',
	'handleTransport',
	'hasMissingTimelineSources',
	'importEffectPresets',
	'importFiles',
	'inspectScape',
	'listAudioEditorEffectPresets',
	'listProjects',
	'makeStereoTrack',
	'materializeFreesoundUploadClip',
	'mixAndRenderTracks',
	'moveClips',
	'moveClipsToNewTrack',
	'moveTrack',
	'newProject',
	'normalizePlaybackFrame',
	'openAudacityProject',
	'openAup4',
	'openDawproject',
	'openSesx',
	'openProject',
	'openScape',
	'openScapeFile',
	'overwriteClips',
	'pasteEffectStack',
	'pauseLoudnessMeasurement',
	'persistSetting',
	'prepareAudacityEffectFromController',
	'prepareProjectHandoff',
	'previewAudacityEffectFromController',
	'previewParametricEq',
	'previewRackEffect',
	'previewVideoEffectGesture',
	'projectSampleRate',
	'publishDocumentSnapshot',
	'recoverTakeCycleRecording',
	'refreshAudioDevices',
	'refreshRecordingInputs',
	'refreshStorageUsage',
	'releaseInputs',
	'releaseVideoSourceVisual',
	'reloadVideoSourceVisual',
	'removeVideoClipEffect',
	'renameProject',
	'renderClipPitchSpeed',
	'reorderTrack',
	'reorderVideoClipEffect',
	'repeatLastAudacityEffect',
	'repeatLastGenerator',
	'reportVideoPreviewPressure',
	'requestFrequencyWaveform',
	'requestInputAccess',
	'requestStoragePersistence',
	'requestWaveformPcmWindow',
	'resampleClip',
	'resampleTrack',
	'resetClipPitchSpeed',
	'resetLoudnessMeasurement',
	'resizeTrackHeight',
	'revertFactorySettings',
	'runEffectMacro',
	'runNyquistEvaluation',
	'saveAup3',
	'saveAup4',
	'saveDawproject',
	'saveEffectPreset',
	'saveNow',
	'saveScape',
	'scheduleTimedRecording',
	'sessionTab',
	'setAllTracksView',
	'setAudacityControlTrack',
	'setAudacityEffectParamsFromController',
	'setAudacityEffectType',
	'setAudioOutputDevice',
	'setAutoFitTrackHeight',
	'setClipTimePitch',
	'setLatencyOffset',
	'setLoopRegion',
	'setLoopRegionInOut',
	'setLoopRegionToSelection',
	'setMicrophoneMetering',
	'setMonitoring',
	'setPlayAtSpeedRate',
	'setPreferredInputChannelCount',
	'setPreferredInputDevice',
	'setRecordingInputGain',
	'setRecordingSourceLatency',
	'setRecordingTrackInput',
	'setRetainInputs',
	'setSampleEditMode',
	'setSelectionToLoopRegion',
	'setStatus',
	'setTimelineView',
	'setTimelineViewportWidth',
	'setTrackChannelHeightRatio',
	'setTrackDisplayMode',
	'setTrackRate',
	'setVisibleTrackHeights',
	'setZoom',
	'smoothSelectedSamples',
	'splitAtFrame',
	'splitStereoTrack',
	'startRecording',
	'startSoundActivatedRecording',
	'startRecordingOnNewTrack',
	'startTakeCycleRecording',
	'stopRecording',
	'stretchClip',
	'swapTrackChannels',
	'switchProject',
	'timelineDurationFrames',
	'toggleLeadInRecording',
	'toggleMetronome',
	'togglePinnedPlayhead',
	'toggleRecordingPause',
	'toggleRmsWaveform',
	'toggleRulerPlayback',
	'toggleSelectionFollowsLoop',
	'toggleStretchToTempo',
	'toggleScrollViewToPlayhead',
	'toggleVerticalRulers',
	'toggleVideoClipEffect',
	'trimClips',
	'updatePreferences',
	'updateRackEffect',
	'updateVideoClipEffect',
	'updateZoom',
]);


export type EditorActionRuntime = EditorActionResources & EditorActionFunctions & Readonly<{
	labels: EditorLabelActionGroup;
	preferenceActions: EditorPreferenceActionOwner;
	projectBin: EditorProjectBinActionGroup;
	selection: EditorSelectionActionGroup;
}>;
export type RestrictToCapability = <Args extends unknown[], Result>(
	capability: string, action: (...args: Args) => Result,
) => (...args: Args) => Result;

/** Fail at assembly, with the missing port's name, rather than on a later menu action. */
export function assertEditorActionRuntime(scope: EditorActionRuntime): void {
	for (const name of EDITOR_ACTION_FUNCTION_NAMES) {
		if (typeof scope[name] !== 'function') throw new TypeError(`Missing editor action dependency: ${name}.`);
	}
	assertEditorLabelActionGroup(scope.labels);
	assertEditorPreferenceActionOwner(scope.preferenceActions);
	assertEditorProjectBinActionGroup(scope.projectBin);
	assertEditorSelectionActionGroup(scope.selection);
}
