/* SPDX-License-Identifier: AGPL-3.0-only */

import {
	resolveCopyCatalogOverrides,
} from './copy-catalog-overrides.ts';

export const FRAMESCAPER_NATIVE_SERVICES_COPY = Object.freeze({
	importImageSequence: 'Image sequence…',
	addToRenderQueue: 'Add to render queue…',
	externalDisplay: 'External display',
	externalDisplayNone: 'None',
	externalDisplayUnavailable: 'No non-primary display available',
	backgroundJobs: 'Background jobs…',
	watchFolders: 'Watch folders…',
	proxies: 'Proxies',
	proxyGenerate: 'Generate…',
	proxyAttach: 'Attach…',
	proxyDetach: 'Detach',
	proxyRelink: 'Relink…',
	nativeMediaPreferences: 'Native media and scratch…',
	videoEffects: 'Video effects',
	ofxAdd: 'Add OFX…',
	ofxManage: 'Manage OFX…',
	ofxInteract: 'Open OFX Interact…',
	nativeServices: 'Framescaper native services',
	refresh: 'Refresh status',
	working: 'Working…',
	operationComplete: 'Operation complete.',
	runtimeUnavailable: 'Native media runtime is unavailable in this build.',
	nativeMediaDisabled: 'Native media is switched off.',
	capabilityUnavailable: 'This operation is unavailable until its runtime and project gates pass.',
	projectActionRun: 'Continue',
	projectActionReady: 'The exact project and runtime gates passed.',
	projectActionComplete: 'The project operation completed.',
	frameRateNumerator: 'Frame rate numerator',
	frameRateDenominator: 'Frame rate denominator',
	renderDeliveryFormat: 'Delivery format',
	renderDeliveryMov: 'ProRes 422 HQ (MOV)',
	renderDeliveryPng: 'PNG image sequence',
	renderDeliveryTiff: 'TIFF image sequence',
	renderDeliveryOpenExr: 'OpenEXR image sequence',
	renderImageSequenceSettings: 'Image-sequence settings',
	renderPreserveAlpha: 'Preserve alpha',
	noQueueJobs: 'There are no background jobs.',
	queueState: 'State',
	queueProgress: 'Progress',
	queuePause: 'Pause',
	queueResume: 'Resume',
	queueCancel: 'Cancel',
	queueRetry: 'Retry',
	queueRegenerateCarrier: 'Regenerate carrier and resume',
	queueReauthorizeRoot: 'Reauthorize destination folder…',
	queueWebCoreRequired: 'Native export could not continue. Use File > Export Video… for the existing Web Core export path.',
	queueRemove: 'Remove',
	queueMoveEarlier: 'Move earlier',
	queueMoveLater: 'Move later',
	noWatchFolders: 'No watch folders are configured.',
	watchCreate: 'Add watch folder',
	watchReconcile: 'Reconcile now',
	watchEnable: 'Enable',
	watchDisable: 'Disable',
	watchRemove: 'Remove',
	watchExtensions: 'File extensions',
	watchImportMode: 'Import mode',
	watchGenerateProxies: 'Generate proxies',
	watchProjectUnavailable: 'Open an editable project before creating a watch rule.',
	watchRootUnavailable: 'Authorize a folder before creating a watch rule.',
	watchLinked: 'Link originals',
	watchCopied: 'Copy originals',
	preferenceStatus: 'Native service preferences',
	nativeMediaMaster: 'Native media master',
	hardwareDecode: 'Hardware decode',
	hardwareEncode: 'Hardware encode',
	ofxConsent: 'OpenFX consent',
	ofxScan: 'Scan plug-in…',
	ofxPlugins: 'Scanned OpenFX plug-ins',
	ofxNoPlugins: 'No OpenFX plug-ins have been scanned in this session.',
	ofxEnable: 'Enable',
	ofxRevoke: 'Revoke',
	ofxClearQuarantine: 'Clear quarantine',
	ofxOperationComplete: 'OpenFX operation complete.',
	ofxRuntimeUnavailable: 'The authenticated OpenFX runtime is unavailable.',
	ofxLoading: 'Loading OpenFX plug-ins…',
	ofxNoCompatibleTarget: 'No enabled OpenFX plug-in has a compatible project target.',
	ofxAuthoring: 'Authoring OpenFX effect…',
	ofxAdded: 'OpenFX effect added.',
	ofxPlugin: 'Plug-in',
	ofxContext: 'Context',
	ofxProjectTarget: 'Project target',
	ofxNamedInputs: 'Named inputs',
	ofxParameters: 'Parameters',
	ofxParameterKind: '{name} ({type})',
	ofxParameterJson: '{name} ({type} JSON)',
	ofxKeyframesJson: 'Keyframes for {name} (JSON)',
	ofxCustomEncoding: 'Custom encoding for {name}',
	ofxAuthor: 'Add OpenFX effect',
	ofxInteractHeading: 'OpenFX Interact Suite V1',
	ofxInteractLoading: 'Loading authored OpenFX effect instances…',
	ofxInteractUnavailable: 'The offscreen OpenFX Interact transport is unavailable.',
	ofxInteractNoPlugins: 'No authored OpenFX effect instance is available for Interact.',
	ofxInteractInstance: 'Authored effect instance',
	ofxInteractReady: 'The 64 by 64 offscreen Interact surface is ready.',
	ofxInteractWorking: 'Sending normalized Interact actions…',
	ofxInteractRedrawn: 'The plug-in requested and completed an offscreen redraw.',
	ofxInteractSequenceExhausted: 'The Interact action sequence is exhausted.',
	ofxInteractInstructions: 'Focus the canvas, then use pointer or keyboard actions. No vendor window opens.',
	ofxInteractTarget: 'Interact target',
	ofxInteractOverlay: 'Overlay Interact',
	ofxInteractCustom: 'Custom parameter Interact',
	ofxInteractCanvas: 'OpenFX 64 by 64 offscreen Interact canvas',
	preferenceControlUnavailable: 'This desktop build can report this switch but cannot change it.',
	capabilityStatus: 'Runtime capability status',
	noCapabilityReport: 'Detailed runtime capability evidence is unavailable.',
	nativeRoots: 'Authorized output folders',
	noNativeRoots: 'No output folders are authorized.',
	rootAuthorize: 'Authorize folder…',
	rootRevalidate: 'Revalidate',
	rootRevoke: 'Revoke',
	rootRevoked: 'revoked',
	rootAvailable: 'authorized',
	scratchCleanup: 'Clean verified scratch',
});

export type FramescaperNativeServicesCopy = Readonly<{
	[Key in keyof typeof FRAMESCAPER_NATIVE_SERVICES_COPY]: string;
}>;

/** Resolve optional host localization without requiring a shared catalog change. */
export function resolveFramescaperNativeServicesCopy(
	copy: Readonly<Record<string, string | undefined>> = {},
): FramescaperNativeServicesCopy {
	return resolveCopyCatalogOverrides(FRAMESCAPER_NATIVE_SERVICES_COPY, copy);
}
