/* SPDX-License-Identifier: AGPL-3.0-only */

import {
	resolveCopyCatalogOverrides,
} from './copy-catalog-overrides.ts';

export const SOUNDSCAPER_PRODUCTION_COPY = Object.freeze({
	productionAudio: 'Production audio',
	productionAudioWorkflows: 'Production audio workflows',
	automation: 'Automation',
	editAutomationLanes: 'Edit lanes…',
	automationMode: 'Mode',
	automationRead: 'Read',
	automationTrim: 'Trim',
	automationTouch: 'Touch',
	automationLatch: 'Latch',
	automationWrite: 'Write',
	routingGraph: 'Routing graph…',
	routing: 'Routing graph',
	freeze: 'Freeze',
	freezeFresh: 'Freeze (fresh)',
	freezeStale: 'Freeze (stale)',
	freezeVerifying: 'Freeze (verifying)',
	freezeUnknown: 'Freeze (status unknown)',
	freezeTrack: 'Freeze track',
	refreshFrozenTrack: 'Refresh frozen track',
	unfreezeTrack: 'Unfreeze track',
	commitFrozenTrack: 'Commit frozen track',
	restoration: 'Restoration…',
	restorationTab: 'Restoration',
	productionMeters: 'Production meters…',
	metersTab: 'Meters',
	reviewedEffects: 'Reviewed effects…',
	reviewedEffectsTab: 'Reviewed effects',
	readOnly: 'Read-only projects can be inspected, but production changes are disabled.',
	locked: 'Unlock the selected audio track to make production changes.',
	busy: 'Wait for the current editor task to finish.',
	noSelection: 'Select an audio track to edit this workflow.',
	unsupported: 'This production workflow is unavailable.',
	laneEditor: 'Lane editor',
	selectedTrack: 'Selected track',
	selectedLane: 'Automation lane',
	automationParameter: 'Parameter',
	automationUnit: 'Unit',
	automationRange: 'Range',
	automationStep: 'Step',
	automationTaper: 'Taper',
	automationTimebase: 'Timebase',
	automationSamples: 'Absolute samples',
	automationBeats: 'Musical beats',
	automationPointPosition: 'Point {index} position',
	automationPointNumerator: 'Point {index} beat numerator',
	automationPointDenominator: 'Point {index} beat denominator',
	automationPointValue: 'Point {index} value',
	automationSegmentCurve: 'Segment {index} curve',
	automationCurveHold: 'Hold',
	automationCurveLinear: 'Linear',
	automationCurveEased: 'Eased',
	automationCurveBezier: 'Bézier (advanced JSON)',
	automationStructuredUpdated: 'Structured lane draft updated. Apply the lane to commit it.',
	automationStructuredInvalid: 'Structured lane editing requires a valid canonical lane document.',
	automationValueRefused: 'The automation value is outside the descriptor range.',
	automationPositionRefused: 'The automation point position must be canonical and non-negative.',
	automationAdvanced: 'Advanced canonical JSON',
	laneDocument: 'Canonical lane document',
	applyLane: 'Apply lane',
	resetLane: 'Reset lane',
	noLanes: 'The selected target has no automation lane.',
	liveAutomationValue: 'Live automation value',
	beginAutomationGesture: 'Begin gesture',
	previewAutomationGesture: 'Preview value',
	releaseAutomationGesture: 'Release and commit',
	cancelAutomationGesture: 'Cancel gesture',
	mixerGraphEditor: 'Mixer graph editor',
	mixerNodes: 'Mixer node collections',
	mixerGroups: 'Groups',
	mixerSends: 'Sends',
	mixerCues: 'Cues',
	mixerNodeId: 'Node ID',
	mixerNodeName: 'Node name',
	mixerChannelCount: 'Channel count',
	mixerAddNode: 'Add {collection} node',
	mixerUpdateNode: 'Update {name}',
	mixerRemoveNode: 'Remove {name}',
	mixerOutputs: 'Output placeholders',
	mixerOutputId: 'Output ID',
	mixerOutputName: 'Output name',
	mixerOutputRole: 'Output role',
	mixerOutputMain: 'Main',
	mixerOutputCue: 'Cue',
	mixerOutputControlRoom: 'Control room',
	mixerOutputAuxiliary: 'Auxiliary',
	mixerAddOutput: 'Add output placeholder',
	mixerUpdateOutput: 'Update output {name}',
	mixerRemoveOutput: 'Remove output {name}',
	mixerVcas: 'VCA membership',
	mixerVcaId: 'VCA ID',
	mixerVcaName: 'VCA name',
	mixerVcaGain: 'VCA gain',
	mixerVcaMute: 'VCA mute',
	mixerVcaMembers: 'VCA members',
	mixerAddVca: 'Add VCA',
	mixerUpdateVca: 'Update VCA {name}',
	mixerRemoveVca: 'Remove VCA {name}',
	mixerEdges: 'Routing edges',
	mixerEdgeId: 'Edge ID',
	mixerEdgeKind: 'Edge kind',
	mixerEdgeAssignment: 'Assignment',
	mixerEdgeSend: 'Send',
	mixerEdgeSidechain: 'Sidechain',
	mixerEdgeSource: 'Source endpoint',
	mixerEdgeDestination: 'Destination endpoint',
	mixerEdgePosition: 'Edge position',
	mixerEdgePreFader: 'Pre-fader',
	mixerEdgePostFader: 'Post-fader',
	mixerEdgeLevel: 'Edge level',
	mixerEdgeEnabled: 'Edge enabled',
	mixerEdgeChannelMap: 'Channel map (destination channels, comma-separated)',
	mixerAddEdge: 'Add routing edge',
	mixerUpdateEdge: 'Update edge {name}',
	mixerRemoveEdge: 'Remove edge {name}',
	mixerStructuredUpdated: 'Structured routing draft updated. Apply the routing graph to commit it.',
	mixerAdvanced: 'Advanced canonical JSON',
	mixerGraphDocument: 'Canonical mixer graph document',
	applyMixerGraph: 'Apply routing graph',
	mixerSummary: '{groups} groups, {sends} sends, {cues} cues, {vcas} VCAs, {outputs} outputs, {edges} edges',
	restorationProcessors: 'Restoration processors',
	clickRemoval: 'Click Removal',
	noiseReduction: 'Noise Reduction',
	filterCurveEq: 'Filter Curve EQ',
	captureNoiseProfile: 'Capture noise profile',
	recaptureNoiseProfile: 'Recapture noise profile',
	restorationNoiseProfileRequired: 'Capture a noise profile to enable Noise Reduction.',
	restorationNoiseProfileReady: 'Noise profile ready. Noise Reduction is available.',
	applyRestoration: 'Apply restoration chain',
	meteringDescription: 'Session-only phase, correlation, surround, and loudness history.',
	stripMeters: 'Strip meters',
	meterStrip: 'Strip',
	meterChannels: 'Channels',
	meterCorrelation: 'Correlation',
	meterPhase: 'Phase',
	noMeterData: 'No strip meter samples have been scheduled yet.',
	loudnessHistory: 'Loudness history',
	loudnessSequence: 'Sample',
	loudnessElapsed: 'Elapsed seconds',
	momentaryLufs: 'Momentary LUFS',
	shortTermLufs: 'Short-term LUFS',
	integratedLufs: 'Integrated LUFS',
	loudnessRange: 'Loudness range (LU)',
	loudnessTruePeak: 'True peak (dBTP)',
	noLoudnessHistory: 'No loudness history samples have been scheduled yet.',
	resetMeters: 'Reset meter history',
	reviewedEffectPackage: 'Reviewed effect package',
	utilityGain: 'Utility Gain',
	utilityGainAmount: 'Gain',
	applyReviewedEffect: 'Apply reviewed effect',
	operationComplete: 'Production audio change complete.',
	close: 'Close',
});

export type SoundscaperProductionCopy = Readonly<{
	[Key in keyof typeof SOUNDSCAPER_PRODUCTION_COPY]: string;
}>;

/** Resolve optional host localization without requiring a shared catalog change. */
export function resolveSoundscaperProductionCopy(
	copy: Readonly<Record<string, string | undefined>> = {},
): SoundscaperProductionCopy {
	return resolveCopyCatalogOverrides(SOUNDSCAPER_PRODUCTION_COPY, copy);
}
