/* SPDX-License-Identifier: AGPL-3.0-only */

import { resolveCopyCatalogOverrides } from '../copy-catalog-overrides.ts';

export const SOUNDSCAPER_ROUTING_GRAPH_COPY = Object.freeze({
	routing: 'Routing graph',
	channelStrips: 'Channel strips',
	routingControls: 'Routing graph controls',
	routingReady: 'Routing graph ready.',
	routingUpdated: 'Routing graph updated.',
	newNodeSelected: 'New mixer node selected.',
	addNode: 'Add node',
	addRoutingNode: 'Add routing node',
	choose: 'Choose…',
	group: 'Group',
	send: 'Send',
	cue: 'Cue',
	vca: 'VCA',
	vcaMembership: 'VCA membership from {source} to {destination}',
	output: 'Output',
	track: 'Track',
	master: 'Master',
	graphZoom: 'Graph zoom',
	zoomOut: 'Zoom out',
	zoomIn: 'Zoom in',
	zoomLevel: 'Graph zoom level',
	fit: 'Fit',
	routingInspector: 'Routing inspector',
	routingInspectorHint: 'Select a strip or connection to inspect it. Start at an output port to create a connection.',
	connectionInspector: 'Connection inspector',
	deleteRoutingItem: 'Delete {item}',
	connection: 'connection',
	confirmDelete: 'Confirm delete',
	cancel: 'Cancel',
	managedByProject: 'Managed by the project',
	masterStrip: 'Master strip',
	audioTrack: 'Audio track',
	selectedNodeMissing: 'The selected node no longer exists.',
	selectedOutputMissing: 'The selected output no longer exists.',
	selectedVcaMissing: 'The selected VCA no longer exists.',
	selectedConnectionMissing: 'The selected connection no longer exists.',
	managedByFolder: 'Managed by track folder',
	name: 'Name',
	channels: 'Channels',
	channelAbbreviation: 'ch',
	saveNode: 'Save node',
	role: 'Role',
	main: 'Main',
	controlRoom: 'Control room',
	auxiliary: 'Auxiliary',
	saveOutput: 'Save output',
	gain: 'Gain',
	mute: 'Mute',
	members: 'Members',
	saveVca: 'Save VCA',
	source: 'Source',
	destination: 'Destination',
	kind: 'Kind',
	assignment: 'Assignment',
	sidechain: 'Sidechain',
	position: 'Position',
	preFader: 'Pre-fader',
	postFader: 'Post-fader',
	levelDb: 'Level (dB)',
	enabled: 'Enabled',
	disabled: 'Disabled',
	channelMap: 'Channel map',
	destinationChannel: 'Destination {index}',
	silence: 'Silence',
	sourceChannel: 'Source {index}',
	saveConnection: 'Save connection',
	resetChannelMap: 'Reset channel map',
	removeMapRow: 'Remove row',
	technicalDetails: 'Technical details',
	connectTo: 'Connect to',
	addConnection: 'Add connection',
	chooseDestination: 'Choose a destination for {source}. Press Escape to cancel.',
	connectionCancelled: 'Connection cancelled.',
	connectionAdded: 'Connection added.',
	connectionRewired: 'Connection rewired.',
	routingItemDeleted: 'Routing item deleted.',
	routingItemAdded: 'Routing item added.',
	connectInto: 'Connect into {destination}',
	startConnection: 'Start connection from {source}',
});

export type SoundscaperRoutingGraphCopy = Readonly<{
	[Key in keyof typeof SOUNDSCAPER_ROUTING_GRAPH_COPY]: string;
}>;

export function resolveSoundscaperRoutingGraphCopy(
	copy: Readonly<Record<string, string | undefined>> = {},
): SoundscaperRoutingGraphCopy {
	return resolveCopyCatalogOverrides(SOUNDSCAPER_ROUTING_GRAPH_COPY, copy);
}
