/* SPDX-License-Identifier: AGPL-3.0-only */

import type { PhotoLibraryImportItemV1 } from '../../src/common/editor/photo-library-session-port-v1.ts';
import type { PhotoLibraryImportSettingsV1 } from '../../src/common/editor/photo-library-import-settings-port-v1.ts';
import { readImageMetadataV1 } from '../../src/common/editor/imaging/image-metadata-reader-v1.ts';
import { PhotoCatalogRepositoryV1 } from '../../src/lightscaper/catalog/repository.ts';
import { validateLightscaperDocumentV1 } from '../../src/lightscaper/catalog/documents.ts';
import { createPhotoLibrarySessionV1 } from '../../src/lightscaper/photo-library-session-runtime.ts';
import { photoImportIntentKeyV1, normalizePhotoImportIntentV1 } from '../../src/lightscaper/import/import-intent-v1.ts';
import { PhotoMediaStoreV1 } from '../../src/lightscaper/storage/photo-media-store.ts';
import { openDefaultPhotoCatalogV1 } from '../../src/lightscaper/storage/photo-library-catalog-pointer.ts';

// Budget recorded before code: <=6 photos, one <=1KiB original at a time,
// <=16 presets, one64-row scalar page, <=64KiB report; no fake decode/import.
// Committed query PNG pixels with an eXIf chunk generated by existing TIFF/PNG
// fixture helpers. Compressed image bytes remain unchanged; full source357B.
const PNG = 'iVBORw0KGgoAAAANSUhEUgAAAAIAAAACAQMAAABIeJ9nAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAAGUExURf8gAP///4DcGxUAAAABYktHRAH/Ai3eAAAAB3RJTUUH6ggZEjoj/gYZhQAAALZlWElmSUkqAAgAAAAGAA4BAgAPAAAAaAAAAA8BAgAOAAAAdwAAABIBAwABAAAAAQAAADsBAgAPAAAAhQAAAJiCAgAOAAAAlAAAAGmHBAABAAAAVgAAAAAAAAABAAOQAgAUAAAAogAAAAAAAABTb3VyY2UgY2FwdGlvbgBOYXRpdmUgY2FtZXJhAFNvdXJjZSBjcmVhdG9yAFNvdXJjZSByaWdodHMAMjAyNjoxMDowOCAxMToxMjoxMwDS1J8kAAAADElEQVQI12NgYGAAAAAEAAEnNCcKAAAAAElFTkSuQmCC';
const sourceName = 'Original ÉTÉ.png';
const sourceBytes = Uint8Array.from(atob(PNG), character => character.charCodeAt(0));
const keywordId = 'native-existing-keyword';
const file = () => new File([sourceBytes.slice()], sourceName, { type: 'image/png', lastModified: 0 });
const plain: PhotoLibraryImportSettingsV1 = { rename: null, metadata: {}, keywordIds: [] };
const recipe: PhotoLibraryImportSettingsV1 = {
	rename: { template: '{stem}-{sequence}.{extension}', sequenceStart: 7, sequencePadding: 4 },
	metadata: { title: 'Authored title', creator: '', location: 'Berlin' }, keywordIds: [keywordId],
};

/** A backend witness: the production session owns every command and original publication. */
export async function qualifyPhotoImportSettingsNativeV1(mode: 'settings' | 'cancel-recovery') {
	if (mode !== 'settings' && mode !== 'cancel-recovery') throw new TypeError('Unsupported import settings qualification.');
	let session = createPhotoLibrarySessionV1({ name: 'Native import settings' });
	try {
		if ((await session.readPage()).totalCount !== 0) throw new RangeError('Native import settings require an isolated empty catalog.');
		await session.applyDefinition(0, { type: 'create-node', nodeKind: 'keyword', id: keywordId, name: 'Native existing keyword', parentId: null });
		const reopen = async () => {
			await session.close(); session = createPhotoLibrarySessionV1({ name: 'Native import settings' });
			return session;
		};
		const result = mode === 'settings' ? await qualifySettings() : await qualifyRecovery();
		const report = { ...result, sourceName, sourceSha256: await hash(new Blob([sourceBytes])), sourceBytes: [...sourceBytes],
			sourceFacts: readImageMetadataV1(sourceBytes), keywordId };
		if (new TextEncoder().encode(JSON.stringify(report)).byteLength > 65_536) throw new RangeError('Native import settings report exceeds its scalar bound.');
		return report;

		async function qualifySettings() {
			const selected = [file(), new File([Uint8Array.of(1, 2, 3)], 'Broken.PNG', { type: 'image/png' }), file()];
			const acknowledged: PhotoLibraryImportItemV1[] = [];
			const first = await session.importFiles(selected, { settings: recipe, onAcknowledged: item => { acknowledged.push(item); } });
			const secondRecipe: PhotoLibraryImportSettingsV1 = { rename: { template: 'Second-{sequence}.{extension}', sequenceStart: 11, sequencePadding: 2 },
				metadata: { caption: '', creator: 'Authored creator', copyright: 'Authored rights' }, keywordIds: [keywordId] };
			const second = await session.importFiles([file()], { settings: secondRecipe });
			const unmodified = await session.importFiles([file()]);
			const ids = [...first, ...second, ...unmodified].filter(item => item.status === 'imported').map(item => requiredId(item));
			const before = await observe(ids);
			const saved = await session.applyImportPreset({ type: 'save', expectedRevision: 0, id: 'native-recipe', name: 'Native recipe', settings: recipe });
			await reopen();
			const reopenedPresets = await session.readImportPresets();
			const deleted = await session.applyImportPreset({ type: 'delete', expectedRevision: saved.revision, id: 'native-recipe' });
			await reopen();
			const emptyPresets = await session.readImportPresets();
			let staleMessage = '', bodyReads = 0;
			const nativeRead = Blob.prototype.arrayBuffer;
			Blob.prototype.arrayBuffer = function () { bodyReads++; return Reflect.apply(nativeRead, this, []) as Promise<ArrayBuffer>; };
			try { await session.importFiles([file()], { settings: { ...plain, keywordIds: ['native-missing-keyword'] } }); }
			catch (failure) { staleMessage = message(failure); }
			finally { Blob.prototype.arrayBuffer = nativeRead; }
			return { first, second, unmodified, acknowledged, selectedNames: selected.map(input => input.name),
				before, after: await observe(ids), saved, reopenedPresets, deleted, emptyPresets, staleMessage, bodyReads };
		}

		async function qualifyRecovery() {
			const stop = new AbortController(), acknowledged: PhotoLibraryImportItemV1[] = [];
			let interruption = '';
			try {
				await session.importFiles([file(), file()], { signal: stop.signal, settings: recipe,
					onAcknowledged: item => { acknowledged.push(item); stop.abort(); } });
			} catch (failure) { interruption = failure instanceof Error ? failure.name : String(failure); }
			const firstId = requiredId(acknowledged[0]);
			const interrupted = await observe([firstId]);
			const recoveredPage = await session.readPage();
			const recovered = await observe([firstId]);
			const next = await session.importFiles([file()], { settings: { ...plain,
				rename: { template: 'Recovered-{sequence}.{extension}', sequenceStart: 20, sequencePadding: 2 } } });
			const ids = [firstId, requiredId(next[0])], sameSession = await observe(ids);
			await reopen();
			return { interruption, acknowledged, interrupted, recoveredPage, recovered, next, sameSession,
				reopenedPage: await session.readPage(), reopened: await observe(ids) };
		}
	} finally { await session.close(); }
}

async function observe(photoIds: readonly string[]) {
	if (photoIds.length > 6) throw new RangeError('Native import observation exceeds six photos.');
	const media = new PhotoMediaStoreV1(), catalog = new PhotoCatalogRepositoryV1({ indexedDB, verifyOriginal: media.verifyOriginal });
	try {
		await media.ready();
		const root = await openDefaultPhotoCatalogV1({ catalog, settings: media.settingsRepository }, { name: 'Native import settings' });
		const value = await media.settingsRepository.get(photoImportIntentKeyV1(root.id));
		const intent = value === undefined ? null : normalizePhotoImportIntentV1(value, root.id);
		const permanent = await media.mediaRepository.catalogOriginals.readPage({ catalogId: root.id });
		const staged = intent ? await media.mediaRepository.catalogOriginals.readPage({ catalogId: root.id, importId: intent.importId }) : null;
		if (root.photoCount > 6 || permanent.afterKey !== null || staged?.afterKey) throw new RangeError('Native import observation exceeds one bounded page.');
		const photos = [];
		for (const id of photoIds) {
			const photo = validateLightscaperDocumentV1(await catalog.loadPhoto(root.id, id));
			if (photo.kind !== 'photo') throw new TypeError('Native import observation requires a photo.');
			const body = await media.mediaRepository.loadAsset(photo.original.storageKey);
			if (!(body instanceof Blob) || body.size > 1_024) throw new RangeError('Native import observation exceeds its original bound.');
			photos.push({ id: photo.id, original: photo.original, metadata: photo.metadata, extractedMetadata: photo.extractedMetadata,
				versions: photo.versions, activeVersionId: photo.activeVersionId, keywordIds: photo.keywordIds,
				actualBytes: Array.from(new Uint8Array(await body.arrayBuffer())), actualSha256: await hash(body) });
		}
		return { photoCount: root.photoCount, photos, intent: intent !== null, permanentIds: permanent.roots.map(row => row.photoId).sort(), stagedIds: staged?.roots.map(row => row.photoId).sort() ?? [] };
	} finally { await Promise.all([catalog.close(), media.close()]); }
}

function requiredId(item: PhotoLibraryImportItemV1 | undefined): string {
	if (!item || item.status !== 'imported' || item.photoId === null) throw new Error('Native import lacks a durable photo acknowledgment.');
	return item.photoId;
}
function message(failure: unknown) { return failure instanceof Error ? failure.message : String(failure); }
async function hash(body: Blob): Promise<string> {
	const digest = await crypto.subtle.digest('SHA-256', await body.arrayBuffer());
	return Array.from(new Uint8Array(digest), value => value.toString(16).padStart(2, '0')).join('');
}
