/* SPDX-License-Identifier: AGPL-3.0-only */

import type { DocumentProject, DocumentHistory } from './document-composition-types.ts';
import type { TakeCycleOpenRecoveryAppPort } from './take-cycle-open-recovery-app-port.ts';
import type { FramescaperVideoProxyActionRuntime } from '../framescaper-video-proxy-action-runtime-registry.ts';
import type { createPreferencesComposition } from './preferences-composition.ts';
import type { createEffectsComposition } from './effects-composition.ts';
import type { createTrackAudioComposition } from './track-audio-composition.ts';
import type { createClipVideoComposition } from './clip-video-composition.ts';
import type { createTransportComposition } from './transport-composition.ts';
import type { createImportComposition } from './import-composition.ts';
import type { createProjectAdminService } from './project-admin-service.ts';
import type { createDocumentComposition } from './document-composition.ts';
import type { createSourceRuntimeComposition } from './source-runtime-composition.ts';
import type { createRecordingComposition } from './recording-composition.ts';
import type { createProjectLockService } from './project-lock-service.ts';
import type { createControllerStorageCapacityService } from './storage-capacity-runtime.ts';
import type { createMicrophoneMeterService } from './microphone-meter-service.ts';
import type { createStableId } from '../stable-id.js';
import type { createEditComposition } from './edit-composition.ts';
import type { createNativeProjectService } from './native-project-service.ts';
import type { findClip } from '../project.js';
import type { findTrack } from '../project.js';
import type { createControllerPresentationState } from './presentation-state.ts';
import type { createScapeProjectFileService } from './scape-project-file-service.ts';
import type { listAudioEditorEffectPresets } from '../effect-presets.js';
import type { createProjectSwitchService } from './project-switch-service.ts';
import type { createSettingPersistence } from './setting-persistence.ts';

/** Action assembly preserves the contracts declared by the owning services. */
export interface EditorActionFunctions {
	readonly activatePanelTabPreference: ReturnType<typeof createPreferencesComposition>['actions']['activatePanelTabPreference'];
	readonly addEffect: ReturnType<typeof createEffectsComposition>['rack']['addEffect'];
	readonly addLabel: ReturnType<typeof createTrackAudioComposition>['track']['addLabel'];
	readonly addLabelTrack: ReturnType<typeof createTrackAudioComposition>['trackActions']['addLabelTrack'];
	readonly addTrack: ReturnType<typeof createTrackAudioComposition>['trackActions']['addTrack'];
	readonly addVideoClipEffect: ReturnType<typeof createClipVideoComposition>['videoEffect']['addVideoClipEffect'];
	readonly addVideoTrackPair: ReturnType<typeof createTrackAudioComposition>['trackActions']['addVideoTrackPair'];
	readonly adjustAllTrackHeights: ReturnType<typeof createTransportComposition>['view']['adjustAllTrackHeights'];
	readonly adjustTrackHeight: ReturnType<typeof createTransportComposition>['view']['adjustTrackHeight'];
	readonly applyAudacityEffectFromController: ReturnType<typeof createEffectsComposition>['applyAudacityEffectFromController'];
	readonly applyEffectPreset: ReturnType<typeof createEffectsComposition>['controls']['applyEffectPreset'];
	readonly applyProjectBinReplacement: ReturnType<typeof createImportComposition>['projectBin']['applyProjectBinReplacement'];
	readonly applySamplePencil: ReturnType<typeof createClipVideoComposition>['applySamplePencil'];
	readonly applySpectralSelection: ReturnType<typeof createEffectsComposition>['applySpectralSelection'];
	readonly assertProjectHandoffAllowed: ReturnType<typeof createProjectAdminService>['assertProjectHandoffAllowed'];
	readonly beginMacroTransaction: ReturnType<typeof createDocumentComposition>['mutation']['beginMacroTransaction'];
	readonly beginParametricEqGesture: ReturnType<typeof createEffectsComposition>['rack']['beginParametricEqGesture'];
	readonly beginRackEffectGesture: ReturnType<typeof createEffectsComposition>['rack']['beginRackEffectGesture'];
	readonly beginVideoEffectGesture: ReturnType<typeof createClipVideoComposition>['videoEffect']['beginVideoEffectGesture'];
	readonly bypassVideoClipEffect: ReturnType<typeof createClipVideoComposition>['videoEffect']['bypassVideoClipEffect'];
	readonly canRelinkLinkedAudio: ReturnType<typeof createImportComposition>['projectBin']['canRelinkLinkedAudio'];
	readonly canRelinkLinkedVideo: ReturnType<typeof createImportComposition>['projectBin']['canRelinkLinkedVideo'];
	readonly cancelAudacityEffectPreview: ReturnType<typeof createEffectsComposition>['controls']['cancelAudacityEffectPreview'];
	readonly cancelEffectMacro: ReturnType<typeof createEffectsComposition>['macro']['cancelEffectMacro'];
	readonly cancelNyquistEvaluation: ReturnType<typeof createEffectsComposition>['nyquistHost']['cancelNyquistEvaluation'];
	readonly cancelParametricEqGesture: ReturnType<typeof createEffectsComposition>['rack']['cancelParametricEqGesture'];
	readonly cancelPlaybackCachePreparation: ReturnType<typeof createSourceRuntimeComposition>['timePitchCaches']['cancelPlaybackCachePreparation'];
	readonly cancelProjectBinReplacement: ReturnType<typeof createImportComposition>['projectBin']['cancelProjectBinReplacement'];
	readonly cancelRackEffectGesture: ReturnType<typeof createEffectsComposition>['rack']['cancelRackEffectGesture'];
	readonly cancelSampleEdit: ReturnType<typeof createClipVideoComposition>['sampleEdit']['cancelSampleEdit'];
	readonly cancelTimedRecording: ReturnType<typeof createRecordingComposition>['timed']['cancelTimedRecording'];
	readonly cancelVideoEffectGesture: ReturnType<typeof createClipVideoComposition>['videoEffect']['cancelVideoEffectGesture'];
	readonly captureRackNoiseProfileFromController: ReturnType<typeof createEffectsComposition>['controls']['captureRackNoiseProfileFromController'];
	readonly captureSelectedNoiseProfile: ReturnType<typeof createEffectsComposition>['captureSelectedNoiseProfile'];
	readonly claimProjectLock: ReturnType<typeof createProjectLockService>['claimProjectLock'];
	readonly classifyLinkedAudioRelink: ReturnType<typeof createImportComposition>['projectBin']['classifyLinkedAudioRelink'];
	readonly classifyLinkedVideoRelink: ReturnType<typeof createImportComposition>['projectBin']['classifyLinkedVideoRelink'];
	readonly cleanupDerivativeCache: ReturnType<typeof createControllerStorageCapacityService>['cleanupDerivativeCache'];
	readonly cleanupDisposableStorage: ReturnType<typeof createControllerStorageCapacityService>['cleanupDisposableStorage'];
	readonly clearLocalData: ReturnType<typeof createProjectAdminService>['clearLocalData'];
	readonly clearLoopRegion: ReturnType<typeof createTransportComposition>['transport']['clearLoopRegion'];
	readonly clearRecentProjects: ReturnType<typeof createProjectAdminService>['clearRecentProjects'];
	readonly closeProjectTab: ReturnType<typeof createProjectAdminService>['closeProjectTab'];
	readonly commit: ReturnType<typeof createDocumentComposition>['mutation']['commit'];
	readonly commitParametricEqGesture: ReturnType<typeof createEffectsComposition>['rack']['commitParametricEqGesture'];
	readonly commitRackEffectGesture: ReturnType<typeof createEffectsComposition>['rack']['commitRackEffectGesture'];
	readonly commitVideoEffectGesture: ReturnType<typeof createClipVideoComposition>['videoEffect']['commitVideoEffectGesture'];
	readonly configureDisplayInput: ReturnType<typeof createRecordingComposition>['routing']['configureDisplayInput'];
	readonly continueLoudnessMeasurement: ReturnType<typeof createMicrophoneMeterService>['continueLoudnessMeasurement'];
	readonly copyEffectStack: ReturnType<typeof createEffectsComposition>['rack']['copyEffectStack'];
	readonly createStableId: typeof createStableId;
	readonly createWorkspacePreference: ReturnType<typeof createPreferencesComposition>['actions']['createWorkspacePreference'];
	readonly currentAudacityEffectParams: ReturnType<typeof createEffectsComposition>['controls']['currentAudacityEffectParams'];
	readonly deleteEffectPreset: ReturnType<typeof createEffectsComposition>['controls']['deleteEffectPreset'];
	readonly deleteProject: ReturnType<typeof createProjectAdminService>['deleteProject'];
	readonly deleteWorkspacePreference: ReturnType<typeof createPreferencesComposition>['actions']['deleteWorkspacePreference'];
	readonly discardTakeCycleRecording: (pending: Parameters<TakeCycleOpenRecoveryAppPort['resolve']>[0]) => Promise<void>;
	readonly disjoinSelectedClip: ReturnType<typeof createEditComposition>['clipboard']['disjoinSelectedClip'];
	readonly dismissAup4CompatibilitySummary: ReturnType<typeof createNativeProjectService>['dismissAup4CompatibilitySummary'];
	readonly duplicateProject: ReturnType<typeof createProjectAdminService>['duplicateProject'];
	readonly duplicateTrack: ReturnType<typeof createDocumentComposition>['trackDuplication']['duplicateTrack'];
	readonly exportEffectPreset: ReturnType<typeof createEffectsComposition>['controls']['exportEffectPreset'];
	readonly exportLabels: ReturnType<typeof createEditComposition>['labels']['exportLabels'];
	readonly exportVideo: ReturnType<typeof createTrackAudioComposition>['export']['exportVideo'];
	readonly findClip: typeof findClip;
	readonly findTrack: typeof findTrack;
	readonly flushProject: ReturnType<typeof createDocumentComposition>['mutation']['flushProject'];
	readonly generateSelectionSilence: ReturnType<typeof createEditComposition>['generateSelectionSilence'];
	readonly generateSignal: ReturnType<typeof createEditComposition>['generateSignal'];
	readonly getClipVisualData: ReturnType<typeof createSourceRuntimeComposition>['projectVisual']['getClipVisualData'];
	readonly getProject: () => DocumentProject | null;
	readonly getProjectBinClipVisualData: ReturnType<typeof createSourceRuntimeComposition>['projectVisual']['getProjectBinClipVisualData'];
	readonly getVideoSourceVisualData: ReturnType<typeof createSourceRuntimeComposition>['projectVisual']['getVideoSourceVisualData'];
	readonly getVisibleClips: ReturnType<typeof createSourceRuntimeComposition>['projectVisual']['getVisibleClips'];
	readonly handleClipAction: ReturnType<typeof createClipVideoComposition>['clipProperty']['handleClipAction'];
	readonly handleEdit: ReturnType<typeof createEditComposition>['handleEdit'];
	readonly handleError: ReturnType<typeof createControllerPresentationState>['handleError'];
	readonly handleExportAction: ReturnType<typeof createTrackAudioComposition>['export']['handleExportAction'];
	readonly handlePlayAtSpeed: ReturnType<typeof createTransportComposition>['transport']['handlePlayAtSpeed'];
	readonly handleTransport: ReturnType<typeof createTransportComposition>['transport']['handleTransport'];
	readonly hasMissingTimelineSources: ReturnType<typeof createSourceRuntimeComposition>['projectVisual']['hasMissingTimelineSources'];
	readonly importEffectPresets: ReturnType<typeof createEffectsComposition>['controls']['importEffectPresets'];
	readonly importFiles: ReturnType<typeof createImportComposition>['importFiles'];
	readonly importLabelFile: ReturnType<typeof createEditComposition>['labels']['importLabelFile'];
	readonly inspectScape: ReturnType<typeof createScapeProjectFileService>['inspectScape'];
	readonly listAudioEditorEffectPresets: typeof listAudioEditorEffectPresets;
	readonly listProjects: ReturnType<typeof createProjectAdminService>['listProjects'];
	readonly makeStereoTrack: ReturnType<typeof createTrackAudioComposition>['makeStereoTrack'];
	readonly mixAndRenderTracks: ReturnType<typeof createTrackAudioComposition>['mixAndRenderTracks'];
	readonly moveClips: ReturnType<typeof createClipVideoComposition>['clipTransform']['moveClips'];
	readonly moveClipsToNewTrack: ReturnType<typeof createClipVideoComposition>['clipTransform']['moveClipsToNewTrack'];
	readonly moveClipsToProjectBin: ReturnType<typeof createImportComposition>['projectBin']['moveClipsToProjectBin'];
	readonly movePanelPreference: ReturnType<typeof createPreferencesComposition>['actions']['movePanelPreference'];
	readonly moveToolbarPreference: ReturnType<typeof createPreferencesComposition>['actions']['moveToolbarPreference'];
	readonly moveTrack: ReturnType<typeof createTrackAudioComposition>['trackActions']['moveTrack'];
	readonly newProject: ReturnType<typeof createProjectSwitchService>['newProject'];
	readonly normalizePlaybackFrame: ReturnType<typeof createTransportComposition>['transport']['normalizePlaybackFrame'];
	readonly openAudacityProject: ReturnType<typeof createNativeProjectService>['openAudacityProject'];
	readonly openAup4: ReturnType<typeof createNativeProjectService>['openAudacityProject'];
	readonly openDawproject: ReturnType<typeof createNativeProjectService>['openDawproject'];
	readonly openProject: ReturnType<typeof createProjectSwitchService>['openProject'];
	readonly openScape: ReturnType<typeof createNativeProjectService>['openScape'];
	readonly openScapeFile: ReturnType<typeof createScapeProjectFileService>['openScapeFile'];
	readonly overwriteClips: ReturnType<typeof createClipVideoComposition>['clipTransform']['overwriteClips'];
	readonly pasteEffectStack: ReturnType<typeof createEffectsComposition>['rack']['pasteEffectStack'];
	readonly pauseLoudnessMeasurement: ReturnType<typeof createMicrophoneMeterService>['pauseLoudnessMeasurement'];
	readonly persistSetting: ReturnType<typeof createSettingPersistence>['persist'];
	readonly placeProjectBinClip: ReturnType<typeof createImportComposition>['projectBin']['placeProjectBinClip'];
	readonly playPauseProjectBinClip: ReturnType<typeof createImportComposition>['projectBin']['playPauseProjectBinClip'];
	readonly prepareProjectBinReplacement: ReturnType<typeof createImportComposition>['projectBin']['prepareProjectBinReplacement'];
	readonly prepareProjectHandoff: ReturnType<typeof createProjectAdminService>['prepareProjectHandoff'];
	readonly previewAudacityEffectFromController: ReturnType<typeof createEffectsComposition>['execution']['previewAudacityEffectFromController'];
	readonly previewParametricEq: ReturnType<typeof createEffectsComposition>['rack']['previewParametricEq'];
	readonly previewRackEffect: ReturnType<typeof createEffectsComposition>['rack']['previewRackEffect'];
	readonly previewVideoEffectGesture: ReturnType<typeof createClipVideoComposition>['videoEffect']['previewVideoEffectGesture'];
	readonly projectBinInstanceCount: ReturnType<typeof createImportComposition>['projectBin']['projectBinInstanceCount'];
	readonly projectSampleRate: ReturnType<typeof createTransportComposition>['transport']['projectSampleRate'];
	readonly publishDocumentSnapshot: (options?: Readonly<{ force?: boolean }>) => void;
	readonly recoverTakeCycleRecording: (pending: Parameters<TakeCycleOpenRecoveryAppPort['resolve']>[0]) => Promise<void>;
	readonly refreshAudioDevices: ReturnType<typeof createRecordingComposition>['routing']['refreshAudioDevices'];
	readonly refreshRecordingInputs: ReturnType<typeof createRecordingComposition>['routing']['refreshRecordingInputs'];
	readonly refreshStorageUsage: ReturnType<typeof createControllerStorageCapacityService>['refreshStorageUsage'];
	readonly releaseInputs: ReturnType<typeof createRecordingComposition>['routing']['releaseInputs'];
	readonly releaseVideoSourceVisual: ReturnType<typeof createSourceRuntimeComposition>['projectVisual']['revokeVideoVisual'];
	readonly relinkLinkedAudio: ReturnType<typeof createImportComposition>['projectBin']['relinkLinkedAudio'];
	readonly relinkLinkedVideo: ReturnType<typeof createImportComposition>['projectBin']['relinkLinkedVideo'];
	readonly reloadVideoSourceVisual: (sourceId: string) => ReturnType<ReturnType<typeof createSourceRuntimeComposition>['projectVisual']['activateVideoSource']>;
	readonly removeProjectBinClip: ReturnType<typeof createImportComposition>['projectBin']['removeProjectBinClip'];
	readonly removeProjectBinSource: ReturnType<typeof createImportComposition>['projectBin']['removeProjectBinSource'];
	readonly removeVideoClipEffect: ReturnType<typeof createClipVideoComposition>['videoEffect']['removeVideoClipEffect'];
	readonly renameProject: ReturnType<typeof createProjectAdminService>['renameProject'];
	readonly renameProjectBinClip: ReturnType<typeof createImportComposition>['projectBin']['renameProjectBinClip'];
	readonly renderClipPitchSpeed: ReturnType<typeof createClipVideoComposition>['renderClipPitchSpeed'];
	readonly reorderTrack: ReturnType<typeof createTrackAudioComposition>['trackActions']['reorderTrack'];
	readonly reorderVideoClipEffect: ReturnType<typeof createClipVideoComposition>['videoEffect']['reorderVideoClipEffect'];
	readonly repeatLastAudacityEffect: ReturnType<typeof createEffectsComposition>['repeatLastAudacityEffect'];
	readonly repeatLastGenerator: ReturnType<typeof createEditComposition>['repeatLastGenerator'];
	readonly reportVideoPreviewPressure: (...args: Parameters<FramescaperVideoProxyActionRuntime['reportPreviewPressure']>) => ReturnType<FramescaperVideoProxyActionRuntime['reportPreviewPressure']> | undefined;
	readonly requestInputAccess: ReturnType<typeof createRecordingComposition>['routing']['requestInputAccess'];
	readonly requestStoragePersistence: ReturnType<typeof createControllerStorageCapacityService>['requestStoragePersistence'];
	readonly requestWaveformPcmWindow: ReturnType<typeof createSourceRuntimeComposition>['sourceLifecycle']['requestWaveformPcmWindow'];
	readonly resampleClip: ReturnType<typeof createTrackAudioComposition>['resampleClip'];
	readonly resampleTrack: ReturnType<typeof createTrackAudioComposition>['resampleTrack'];
	readonly resetClipPitchSpeed: ReturnType<typeof createClipVideoComposition>['clipProperty']['resetClipPitchSpeed'];
	readonly resetLoudnessMeasurement: ReturnType<typeof createMicrophoneMeterService>['resetLoudnessMeasurement'];
	readonly resizeTrackHeight: ReturnType<typeof createTransportComposition>['view']['resizeTrackHeight'];
	readonly revertFactorySettings: ReturnType<typeof createPreferencesComposition>['service']['revertFactorySettings'];
	readonly runEffectMacro: ReturnType<typeof createEffectsComposition>['runEffectMacro'];
	readonly runNyquistEvaluation: ReturnType<typeof createEffectsComposition>['runNyquistEvaluation'];
	readonly saveAup4: ReturnType<typeof createNativeProjectService>['saveAup4'];
	readonly saveDawproject: ReturnType<typeof createNativeProjectService>['saveDawproject'];
	readonly saveEffectPreset: ReturnType<typeof createEffectsComposition>['controls']['saveEffectPreset'];
	readonly saveNow: ReturnType<typeof createDocumentComposition>['mutation']['saveNow'];
	readonly saveScape: ReturnType<typeof createNativeProjectService>['saveScape'];
	readonly scheduleTimedRecording: ReturnType<typeof createRecordingComposition>['timed']['scheduleTimedRecording'];
	readonly selectAllTracks: ReturnType<typeof createTrackAudioComposition>['selectionView']['selectAllTracks'];
	readonly selectAtZeroCrossings: ReturnType<typeof createTrackAudioComposition>['selectionView']['selectAtZeroCrossings'];
	readonly selectClip: ReturnType<typeof createTrackAudioComposition>['selectionView']['selectClip'];
	readonly selectCursorToTrackEnd: ReturnType<typeof createTrackAudioComposition>['selectionView']['selectCursorToTrackEnd'];
	readonly selectLeftOfPlaybackPosition: ReturnType<typeof createTrackAudioComposition>['selectionView']['selectLeftOfPlaybackPosition'];
	readonly selectProjectBinInstances: ReturnType<typeof createImportComposition>['projectBin']['selectProjectBinInstances'];
	readonly selectRightOfPlaybackPosition: ReturnType<typeof createTrackAudioComposition>['selectionView']['selectRightOfPlaybackPosition'];
	readonly selectTrack: ReturnType<typeof createTrackAudioComposition>['selectionView']['selectTrack'];
	readonly selectTrackStartToCursor: ReturnType<typeof createTrackAudioComposition>['selectionView']['selectTrackStartToCursor'];
	readonly selectTrackStartToEnd: ReturnType<typeof createTrackAudioComposition>['selectionView']['selectTrackStartToEnd'];
	readonly sessionTab: ReturnType<typeof createDocumentComposition>['session']['sessionTab'];
	readonly setAllTracksView: ReturnType<typeof createDocumentComposition>['view']['setAllTracksView'];
	readonly setAudacityControlTrack: ReturnType<typeof createEffectsComposition>['controls']['setAudacityControlTrack'];
	readonly setAudacityEffectParamsFromController: ReturnType<typeof createEffectsComposition>['controls']['setAudacityEffectParamsFromController'];
	readonly setAudacityEffectType: ReturnType<typeof createEffectsComposition>['controls']['setAudacityEffectType'];
	readonly setAudioOutputDevice: ReturnType<typeof createRecordingComposition>['routing']['setAudioOutputDevice'];
	readonly setAutoFitTrackHeight: ReturnType<typeof createTransportComposition>['view']['setAutoFitTrackHeight'];
	readonly setClipTimePitch: ReturnType<typeof createClipVideoComposition>['clipProperty']['setClipTimePitch'];
	readonly setExactSelection: ReturnType<typeof createTrackAudioComposition>['selectionView']['setExactSelection'];
	readonly setLatencyOffset: ReturnType<typeof createRecordingComposition>['setLatencyOffset'];
	readonly setLoopRegion: ReturnType<typeof createTransportComposition>['transport']['setLoopRegion'];
	readonly setLoopRegionInOut: ReturnType<typeof createTransportComposition>['transport']['setLoopRegionInOut'];
	readonly setLoopRegionToSelection: ReturnType<typeof createTransportComposition>['transport']['setLoopRegionToSelection'];
	readonly setMicrophoneMetering: ReturnType<typeof createMicrophoneMeterService>['setMicrophoneMetering'];
	readonly setMonitoring: ReturnType<typeof createRecordingComposition>['setMonitoring'];
	readonly setPanelDockExtentPreference: ReturnType<typeof createPreferencesComposition>['actions']['setPanelDockExtentPreference'];
	readonly setPanelFrameSizePreference: ReturnType<typeof createPreferencesComposition>['actions']['setPanelFrameSizePreference'];
	readonly setPanelPreference: ReturnType<typeof createPreferencesComposition>['actions']['setPanelPreference'];
	readonly setPanelVisibilityPreference: ReturnType<typeof createPreferencesComposition>['actions']['setPanelVisibilityPreference'];
	readonly setPlayAtSpeedRate: ReturnType<typeof createTransportComposition>['transport']['setPlayAtSpeedRate'];
	readonly setPreferredInputChannelCount: ReturnType<typeof createRecordingComposition>['routing']['setPreferredInputChannelCount'];
	readonly setPreferredInputDevice: ReturnType<typeof createRecordingComposition>['routing']['setPreferredInputDevice'];
	readonly setProjectBinClipColor: ReturnType<typeof createImportComposition>['projectBin']['setProjectBinClipColor'];
	readonly setRecordingInputGain: ReturnType<typeof createRecordingComposition>['setRecordingInputGain'];
	readonly setRecordingSourceLatency: ReturnType<typeof createRecordingComposition>['routing']['setRecordingSourceLatency'];
	readonly setRecordingTrackInput: ReturnType<typeof createRecordingComposition>['inputs']['setRecordingTrackInput'];
	readonly setRetainInputs: ReturnType<typeof createRecordingComposition>['routing']['setRetainInputs'];
	readonly setSampleEditMode: ReturnType<typeof createClipVideoComposition>['sampleEdit']['setSampleEditMode'];
	readonly setSelection: ReturnType<typeof createTrackAudioComposition>['selectionView']['setSelection'];
	readonly setSelectionToLoopRegion: ReturnType<typeof createTransportComposition>['transport']['setSelectionToLoopRegion'];
	readonly setShortcutPreference: ReturnType<typeof createPreferencesComposition>['actions']['setShortcutPreference'];
	readonly setSnapSettings: ReturnType<typeof createTrackAudioComposition>['selectionView']['setSnapSettings'];
	readonly setStatus: ReturnType<typeof createControllerPresentationState>['setStatus'];
	readonly setTimelineView: ReturnType<typeof createDocumentComposition>['view']['setTimelineView'];
	readonly setTimelineViewportWidth: ReturnType<typeof createTransportComposition>['view']['setTimelineViewportWidth'];
	readonly setToolbarButtonPreference: ReturnType<typeof createPreferencesComposition>['actions']['setToolbarButtonPreference'];
	readonly setTrackDisplayMode: ReturnType<typeof createTrackAudioComposition>['trackActions']['setTrackDisplayMode'];
	readonly setTrackRate: ReturnType<typeof createTrackAudioComposition>['trackActions']['setTrackRate'];
	readonly setVisibleTrackHeights: ReturnType<typeof createTransportComposition>['view']['setVisibleTrackHeights'];
	readonly setWorkspacePreference: ReturnType<typeof createPreferencesComposition>['actions']['setWorkspacePreference'];
	readonly setZoom: ReturnType<typeof createTrackAudioComposition>['selectionView']['setZoom'];
	readonly smoothSelectedSamples: ReturnType<typeof createClipVideoComposition>['smoothSelectedSamples'];
	readonly snapTimelineFrame: ReturnType<typeof createTrackAudioComposition>['selectionView']['snapTimelineFrame'];
	readonly splitAtFrame: ReturnType<typeof createEditComposition>['clipboard']['splitAtFrame'];
	readonly splitStereoTrack: ReturnType<typeof createTrackAudioComposition>['splitStereoTrack'];
	readonly startRecording: ReturnType<typeof createRecordingComposition>['session']['startRecording'];
	readonly startRecordingOnNewTrack: ReturnType<typeof createRecordingComposition>['session']['startRecordingOnNewTrack'];
	readonly startTakeCycleRecording: ReturnType<typeof createRecordingComposition>['session']['startTakeCycleRecording'];
	readonly stopProjectBinPreview: ReturnType<typeof createImportComposition>['projectBin']['stopProjectBinPreview'];
	readonly stopRecording: ReturnType<typeof createRecordingComposition>['session']['stopRecording'];
	readonly stretchClip: ReturnType<typeof createClipVideoComposition>['clipProperty']['stretchClip'];
	readonly swapTrackChannels: ReturnType<typeof createTrackAudioComposition>['swapTrackChannels'];
	readonly switchProject: ReturnType<typeof createProjectSwitchService<DocumentProject, DocumentHistory>>['switchProject'];
	readonly timelineDurationFrames: () => number;
	readonly toggleLeadInRecording: ReturnType<typeof createRecordingComposition>['session']['toggleLeadInRecording'];
	readonly toggleMetronome: ReturnType<typeof createTransportComposition>['transport']['toggleMetronome'];
	readonly togglePanelPreference: ReturnType<typeof createPreferencesComposition>['actions']['togglePanelPreference'];
	readonly togglePinnedPlayhead: ReturnType<typeof createTrackAudioComposition>['selectionView']['togglePinnedPlayhead'];
	readonly toggleRecordingPause: ReturnType<typeof createRecordingComposition>['session']['toggleRecordingPause'];
	readonly toggleRmsWaveform: ReturnType<typeof createTrackAudioComposition>['selectionView']['toggleRmsWaveform'];
	readonly toggleRulerPlayback: ReturnType<typeof createTrackAudioComposition>['selectionView']['toggleRulerPlayback'];
	readonly toggleSelectionFollowsLoop: ReturnType<typeof createTransportComposition>['transport']['toggleSelectionFollowsLoop'];
	readonly toggleStretchToTempo: ReturnType<typeof createClipVideoComposition>['clipProperty']['toggleStretchToTempo'];
	readonly toggleToolbarPreference: ReturnType<typeof createPreferencesComposition>['actions']['toggleToolbarPreference'];
	readonly toggleScrollViewToPlayhead: ReturnType<typeof createTrackAudioComposition>['selectionView']['toggleScrollViewToPlayhead'];
	readonly toggleVerticalRulers: ReturnType<typeof createTrackAudioComposition>['selectionView']['toggleVerticalRulers'];
	readonly toggleVideoClipEffect: ReturnType<typeof createClipVideoComposition>['videoEffect']['toggleVideoClipEffect'];
	readonly trimClips: ReturnType<typeof createClipVideoComposition>['clipTransform']['trimClips'];
	readonly updatePreferences: ReturnType<typeof createPreferencesComposition>['service']['update'];
	readonly updateRackEffect: ReturnType<typeof createEffectsComposition>['rack']['updateRackEffect'];
	readonly updateVideoClipEffect: ReturnType<typeof createClipVideoComposition>['videoEffect']['updateVideoClipEffect'];
	readonly updateWorkspacePreference: ReturnType<typeof createPreferencesComposition>['actions']['updateWorkspacePreference'];
	readonly updateZoom: ReturnType<typeof createTransportComposition>['view']['updateZoom'];
}
