/* SPDX-License-Identifier: AGPL-3.0-only */

import type { EditorControllerPhase } from './lifecycle.ts';
import { createInitialStorageCapacitySnapshot } from './storage-capacity-service.ts';
import type { TakeCyclePendingOpenRecovery } from './take-cycle-capture-orchestrator.ts';

export interface EditorControllerStateOptions<Preferences, RecordingRouting, EffectPresets> {
	readonly preferences: Preferences;
	readonly recordingRouting: RecordingRouting;
	readonly effectPresets: EffectPresets;
	readonly initialEffectType: string;
	readonly phase: EditorControllerPhase;
	readonly readyMessage: string;
	readonly mobile: boolean;
	readonly defaultPixelsPerSecond: number;
	readonly timelineMinimumSeconds: number;
	readonly recordingInputGain: number;
	readonly preferredInputDeviceId: string;
}

/**
 * Creates all mutable controller state in one place. Keeping initialization out
 * of the composition root makes additions visible in review and gives tests a
 * deterministic state model without booting storage, workers, or Web Audio.
 */
export function createEditorControllerState<Preferences, RecordingRouting, EffectPresets>({
	preferences,
	recordingRouting,
	effectPresets,
	initialEffectType,
	phase,
	readyMessage,
	mobile,
	defaultPixelsPerSecond,
	timelineMinimumSeconds,
	recordingInputGain,
	preferredInputDeviceId,
}: EditorControllerStateOptions<Preferences, RecordingRouting, EffectPresets>) {
	return {
		history: null,
		preferences,
		preferencesReadOnly: false,
		selectedTrackId: null,
		selectedClipId: null,
		selectedAnnotationId: null,
		clipboard: null,
		effectClipboard: null,
		pixelsPerSecond: defaultPixelsPerSecond,
		timelineViewportWidth: 0,
		autoFitTrackHeight: true,
		visibleTrackHeights: {},
		mobile,
		timelineWidth: timelineMinimumSeconds * defaultPixelsPerSecond,
		timelineView: 'waveform',
		readOnly: false,
		takeCycleRecovery: null as TakeCyclePendingOpenRecovery | null,
		takeCycleRecoveryInspecting: false,
		projectLock: null,
		projectLockRetryTimer: 0,
		autosaveTimer: 0,
		sourceGcTimer: 0,
		saveGeneration: 0,
		pendingSaveSnapshots: new Set<unknown>(),
		saveQueue: Promise.resolve(),
		recorder: null,
		recordingKind: null as 'ordinary' | 'take-cycle' | null,
		recordingWriter: null,
		recordingStream: null,
		recordingStarting: false,
		recordingStartGeneration: 0,
		recordingStartPromise: null,
		timedRecording: null,
		timedRecordingTimer: null,
		timedRecordingGeneration: 0,
		timedRecordingPreparing: false,
		timedRecordingCancelling: false,
		recordingPaused: false,
		recordingInputGain,
		leadInRecording: false,
		importing: false,
		projectBinPreview: null,
		recordingSourceId: null,
		recordingStartFrame: 0,
		recordingSourceOffsetFrames: 0,
		recordingSampleRate: null,
		recordingTrackId: null,
		recordingSelection: null,
		recordingResampler: null,
		recordingPreview: null,
		recordingPreviews: [] as unknown[],
		recordingEntries: null,
		recordingPreviewLastPublishedAt: 0,
		recordingCleanup: null,
		recordingFinishing: false,
		recordingFinalizePromise: null,
		recordingFatalError: null,
		recordingDiscardRequested: false,
		recordingReleaseAfterStop: false,
		recordingRouting,
		recordingDevices: [] as unknown[],
		recordingEnumeratedDeviceIds: new Set<string>(),
		audioInputDevices: [] as unknown[],
		audioOutputDevices: [] as unknown[],
		audioInputAccess: false,
		preferredInputDeviceId,
		preferredInputChannelCount: 1,
		preferredOutputDeviceId: '',
		activeOutputDeviceId: '',
		audioOutputStatus: 'default',
		recordingRouteHealth: {},
		recordingPoolSources: [] as unknown[],
		inputMeters: {},
		playbackCacheAbort: null,
		playbackCacheGeneration: 0,
		playAtSpeedRate: 1,
		playAtSpeedAbort: null,
		playAtSpeedGeneration: 0,
		exportAbort: null,
		exportGeneration: 0,
		outputUrl: null,
		outputCleanup: null,
		projectQueue: Promise.resolve(),
		missingSourceIds: new Set<string>(),
		audacityEffectType: initialEffectType,
		audacityEffectParams: {},
		audacityEffectTouchedParams: new Map<string, Set<string>>(),
		effectPresets,
		rackEffectGestures: new Map<string, unknown>(),
		parametricEqGestures: new Map<string, unknown>(),
		videoEffectGestures: new Map<string, unknown>(),
		audacityControlTrackId: null,
		audacityNoiseProfile: null,
		audacityEffectProcessing: false,
		audacityPreviewSource: null,
		audacityPreviewAuditionBandId: null,
		audacityPreviewGeneration: 0,
		lastAudacityEffect: null,
		lastGeneratorRequest: null,
		audacityEffectWorker: null,
		nyquistAbort: null,
		nyquistResult: null,
		spectralWorker: null,
		phase,
		projects: [] as unknown[],
		recentProjectIds: [] as string[],
		status: { message: readyMessage, state: 'info' },
		saveState: 'saved',
		storageEstimate: createInitialStorageCapacitySnapshot(),
		analysisResult: null,
		analysisVisuals: null,
		analysisReport: null,
		analysisProcessing: false,
		lastAnalysisRequest: null,
		contrastSelections: { foreground: null, background: null },
		sampleEditMode: null,
		sampleEditAvailable: false,
		sampleEditProcessing: false,
		sampleEditAbort: null,
		taskProgress: null,
		exportProgress: 0,
		exportOutput: null,
		monitoring: false,
		microphoneMetering: false,
		latencyOffsetMs: 0,
		showRms: false,
		showVerticalRulers: true,
		updateDisplayWhilePlaying: true,
		pinnedPlayhead: false,
		playbackOnRulerClick: true,
		metronomeEnabled: false,
		selectionFollowsLoop: false,
		metronomeTimer: 0,
		positionFrame: 0,
		durationFrames: 0,
		transportState: 'stopped',
		meters: { tracks: {}, master: null },
		inputMeterDb: -60,
		inputMeter: null,
		inputLoudnessMeasurementManuallyPaused: false,
		inputLoudnessMeasurementExplicitlyRunning: false,
		disposed: false,
	};
}
