/* SPDX-License-Identifier: AGPL-3.0-only */

import type { createLocalDiagnosticsErrorJournal } from '../local-diagnostics-error-journal.ts';
import type { DeliveryPresetState } from '../delivery-preset-store.ts';
import type { AnalysisState, AnalysisDependencies } from './analysis-service.ts';
import type { EditorDocumentSnapshotRuntime, SnapshotProject } from './document-snapshot.ts';
import type { EffectsCompositionState } from './effects-composition-types.ts';
import type { createInitialEffectMacroLibrary } from './effect-macro-library-service.ts';
import type { AudioGeneratorServiceDependencies } from './generator-service.ts';
import type { EditorCancellableHandle, EditorControllerPhase } from './lifecycle.ts';
import type { createInitialMacroScriptLibrary } from './macro-script-library-service.ts';
import type { ProjectBinPreview } from './project-bin-types.ts';
import type { ProjectLifecycleLock } from './project-lifecycle-types.ts';
import type { ControllerRuntimeHistory } from './project-runtime.ts';
import type { ProjectViewState } from './project-view-service.ts';
import type { ProjectSaveStatus } from './project-save-service.ts';
import type { createInitialStorageCapacitySnapshot } from './storage-capacity-service.ts';
import type { EditorTaskProgress } from './task-progress.ts';
import type { TakeCyclePendingOpenRecovery } from './take-cycle-capture-orchestrator.ts';
import type { VideoEffectServiceRuntime } from './video-effect-service.ts';
import type { AudioEditorClipboard } from '../commands/protocol.ts';
import type { ExportActionState } from './export-action-group.ts';

/** Mutable workspace slots retain their owners' contracts after initialization. */
export interface ControllerWorkspaceState<Preferences, EffectPresets, History = ControllerRuntimeHistory> extends ExportActionState {
	localDiagnostics: ReturnType<typeof createLocalDiagnosticsErrorJournal>;
	history: History | null;
	preferences: Preferences;
	effectPresets: EffectPresets;
	selectedTrackId: string | null;
	selectedClipId: string | null;
	selectedAnnotationId: string | null;
	clipboard: AudioEditorClipboard | null;
	visibleTrackHeights: Record<string, number>;
	timelineView: ProjectViewState['timelineView'];
	takeCycleRecovery: TakeCyclePendingOpenRecovery | null;
	projectLock: ProjectLifecycleLock | null;
	projectBinPreview: ProjectBinPreview | null;
	exportAbort: EditorCancellableHandle | null;
	outputUrl: string | null;
	outputCleanup: (() => PromiseLike<unknown> | unknown) | null;
	projectQueue: Promise<void>;
	missingSourceIds: Set<string>;
	effectMacros: ReturnType<typeof createInitialEffectMacroLibrary>;
	macroScripts: ReturnType<typeof createInitialMacroScriptLibrary>;
	videoEffectGestures: VideoEffectServiceRuntime['state']['videoEffectGestures'];
	lastGeneratorRequest: AudioGeneratorServiceDependencies['state']['lastGeneratorRequest'];
	nyquistResult: unknown;
	phase: EditorControllerPhase;
	projects: EditorDocumentSnapshotRuntime<SnapshotProject>['state']['projects'];
	recentProjectIds: string[];
	status: { message: string; state: string };
	saveState: ProjectSaveStatus;
	storageEstimate: ReturnType<typeof createInitialStorageCapacitySnapshot>;
	analysisResult: unknown;
	analysisVisuals: unknown;
	analysisReport: unknown;
	lastAnalysisRequest: AnalysisState['lastAnalysisRequest'];
	contrastSelections: ReturnType<AnalysisDependencies['getContrastSelections']>;
	sampleEditMode: 'pencil' | null;
	sampleEditAbort: EditorCancellableHandle | null;
	taskProgress: EditorTaskProgress | null;
	exportOutput: unknown;
	effectClipboard: EffectsCompositionState['effectClipboard'];
	audacityEffectType: EffectsCompositionState['audacityEffectType'];
	audacityEffectParams: EffectsCompositionState['audacityEffectParams'];
	audacityEffectTouchedParams: EffectsCompositionState['audacityEffectTouchedParams'];
	rackEffectGestures: EffectsCompositionState['rackEffectGestures'];
	parametricEqGestures: EffectsCompositionState['parametricEqGestures'];
	audacityControlTrackId: EffectsCompositionState['audacityControlTrackId'];
	audacityNoiseProfile: EffectsCompositionState['audacityNoiseProfile'];
	audacityPreviewSource: EffectsCompositionState['audacityPreviewSource'];
	audacityPreviewAuditionBandId: EffectsCompositionState['audacityPreviewAuditionBandId'];
	lastAudacityEffect: EffectsCompositionState['lastAudacityEffect'];
	audacityEffectWorker: EffectsCompositionState['audacityEffectWorker'];
	nyquistAbort: EffectsCompositionState['nyquistAbort'];
	spectralWorker: EffectsCompositionState['spectralWorker'];
	preferencesReadOnly: boolean;
	pixelsPerSecond: number;
	timelineViewportWidth: number;
	autoFitTrackHeight: boolean;
	timelineWidth: number;
	readOnly: boolean;
	writeAuthorityGeneration: number;
	takeCycleRecoveryInspecting: boolean;
	projectLockRetryTimer: number;
	sourceGcTimer: number;
	importing: boolean;
	exportGeneration: number;
	audacityEffectProcessing: boolean;
	audacityPreviewGeneration: number;
	analysisProcessing: boolean;
	sampleEditAvailable: boolean;
	sampleEditProcessing: boolean;
	exportProgress: number;
	showRms: boolean;
	showVerticalRulers: boolean;
	disposed: boolean;
	mobile: boolean;
	deliveryPresets: DeliveryPresetState;
}
