/* SPDX-License-Identifier: AGPL-3.0-only */

// Generated by scripts/i18n-ai.mjs from the catalogs beside this file; do not
// edit by hand. Each loader is a lazy JSON chunk so a locale's machine
// translations cost nothing until that locale is opened. The imports carry
// no type attribute on purpose: Vite bundles a JSON module into a JavaScript
// chunk, which the browser would refuse under a JSON attribute. Node reads
// these files through scripts/i18n-ai/catalog.mjs; the test runner's tsx
// loader resolves the attribute-free imports.

export const MACHINE_CATALOG_LOCALES = Object.freeze([
	'ar',
	'cs',
	'el',
	'es',
	'fa',
	'fi',
	'fr',
	'gl',
	'he',
	'hi',
	'hy',
	'id',
	'it',
	'ja',
	'ko',
	'nl',
	'pl',
	'pt-BR',
	'pt-PT',
	'ro',
	'ru',
	'tr',
	'uk',
	'vi',
	'zh-CN',
]);

export const MACHINE_CATALOG_LOADERS = Object.freeze({
	ar: () => import('./ar.json'),
	cs: () => import('./cs.json'),
	el: () => import('./el.json'),
	es: () => import('./es.json'),
	fa: () => import('./fa.json'),
	fi: () => import('./fi.json'),
	fr: () => import('./fr.json'),
	gl: () => import('./gl.json'),
	he: () => import('./he.json'),
	hi: () => import('./hi.json'),
	hy: () => import('./hy.json'),
	id: () => import('./id.json'),
	it: () => import('./it.json'),
	ja: () => import('./ja.json'),
	ko: () => import('./ko.json'),
	nl: () => import('./nl.json'),
	pl: () => import('./pl.json'),
	'pt-BR': () => import('./pt-BR.json'),
	'pt-PT': () => import('./pt-PT.json'),
	ro: () => import('./ro.json'),
	ru: () => import('./ru.json'),
	tr: () => import('./tr.json'),
	uk: () => import('./uk.json'),
	vi: () => import('./vi.json'),
	'zh-CN': () => import('./zh-CN.json'),
});
