/* SPDX-License-Identifier: AGPL-3.0-only */

// Generated by scripts/i18n-ai.mjs from the catalogs beside this file; do not
// edit by hand. Each loader is a lazy JSON chunk so a locale's machine
// translations cost nothing until that locale is opened. The imports carry
// no type attribute on purpose: Vite bundles a JSON module into a JavaScript
// chunk, which the browser would refuse under a JSON attribute. Node reads
// these files through scripts/i18n-ai/catalog.mjs; the test runner's tsx
// loader resolves the attribute-free imports.

export const MACHINE_CATALOG_LOCALES = Object.freeze([
	'ar',
	'es',
]);

export const MACHINE_CATALOG_LOADERS = Object.freeze({
	ar: () => import('./ar.json'),
	es: () => import('./es.json'),
});
